// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:2ee744a3c426fd286a3c23e56f4ee990cf6949391c205275d0afc352e33797d3
// crate: aep-envelope-walls
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-001: compile lattice-policy.rego into Admit walls. Stop live OPA on action_path.

use aep_admit::{
    admit_collect_all, compile_lattice_policy, default_rego_path, load_policy_sets,
    prove_rego_source, LatticeCompileInput,
};
use std::fs;
use std::path::{Path, PathBuf};

fn extract_filter_crossing(src: &str) -> String {
    let start = match src.find("async filterCrossing") {
        Some(v) => v,
        None => return String::new(),
    };
    src[start..].to_string()
}

pub fn live_opa_absent(filter_source: &str) -> Result<String, String> {
    let body = extract_filter_crossing(filter_source);
    if body.is_empty() {
        return Err(String::from("filterCrossing not found"));
    }
    if body.contains("latticePolicy.evaluate") || body.contains("evaluateLatticePolicyWithOpa") {
        return Err(String::from(
            "filterCrossing still calls live OPA evaluate on action_path",
        ));
    }
    if body.contains("compileLatticePolicy") == false
        && body.contains("compileLatticeWalls") == false
    {
        return Err(String::from(
            "filterCrossing does not compile lattice-policy walls",
        ));
    }
    Ok(String::from("ok live OPA absent on filterCrossing"))
}

pub fn default_filter_ts() -> PathBuf {
    let mut p = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| String::from(".")),
    );
    p.push("../../dynAEP/bridge/hyperlattice/HyperlatticeFilter.ts");
    p
}

pub fn run_gate(rego: &Path, filter: &Path) -> Result<i32, String> {
    let text = match fs::read_to_string(rego) {
        Ok(t) => t,
        Err(e) => return Err(e.to_string()),
    };
    let proof = prove_rego_source(&text)?;
    let filter_src = match fs::read_to_string(filter) {
        Ok(t) => t,
        Err(e) => return Err(e.to_string()),
    };
    let absent = live_opa_absent(&filter_src)?;
    let sets = load_policy_sets(rego)?;
    let mut input = LatticeCompileInput::default();
    input.action_path = String::from("bogus:path");
    input.trust_tier = 3;
    input.category = String::from("agent_action");
    input.all_actions.push(String::from("webhook:incoming"));
    let compiled = compile_lattice_policy(&input, &sets);
    let admit = admit_collect_all(&compiled.walls);
    if admit.allow {
        return Err(String::from("unknown path must close compiled walls"));
    }
    if compiled
        .deny
        .iter()
        .any(|d| d.contains("Unknown action path"))
        == false
    {
        return Err(String::from("former Rego unknown-path deny missing"));
    }
    println!(
        "aep-envelope-walls ok proof={} absent={} closed={}",
        proof,
        absent,
        admit.closed.len()
    );
    Ok(0)
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: compile_lattice_walls domain:admit type:service
pub mod compile_lattice_walls {
    use super::*;

    pub struct CompileLatticeWalls {
        pub source: String,
        pub scan: String,
    }

    impl CompileLatticeWalls {
        pub fn new() -> Self {
            Self {
                source: String::new(),
                scan: String::new(),
            }
        }

        /// Compile lattice-policy.rego deny_lattice rules into Admit walls
        pub fn process(&mut self) -> anyhow::Result<()> {
            let path = if self.source.is_empty() {
                default_rego_path()
            } else {
                PathBuf::from(&self.source)
            };
            let sets = load_policy_sets(&path).map_err(anyhow::Error::msg)?;
            let mut input = LatticeCompileInput::default();
            input.action_path = String::from("bogus:path");
            input.all_actions.push(String::from("webhook:incoming"));
            let compiled = compile_lattice_policy(&input, &sets);
            let admit = admit_collect_all(&compiled.walls);
            let mut scan = String::from("allow=");
            scan.push_str(if admit.allow { "true" } else { "false" });
            self.scan = scan;
            Ok(())
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: prove_rego_source domain:admit type:service
pub mod prove_rego_source {
    use super::*;

    pub struct ProveRegoSource {
        pub policy_path: String,
        pub proof: String,
    }

    impl ProveRegoSource {
        pub fn new() -> Self {
            Self {
                policy_path: String::new(),
                proof: String::new(),
            }
        }

        /// Prove lattice-policy.rego is the source of compiled Admit walls at boot and CI
        pub fn process(&mut self) -> anyhow::Result<()> {
            let path = if self.policy_path.is_empty() {
                default_rego_path()
            } else {
                PathBuf::from(&self.policy_path)
            };
            let text = fs::read_to_string(&path).map_err(anyhow::Error::msg)?;
            self.proof = prove_rego_source(&text).map_err(anyhow::Error::msg)?;
            Ok(())
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: live_opa_absent domain:admit type:service
pub mod live_opa_absent {
    use super::*;

    pub struct LiveOpaAbsent {
        pub filter_source: String,
        pub scan: String,
    }

    impl LiveOpaAbsent {
        pub fn new() -> Self {
            Self {
                filter_source: String::new(),
                scan: String::new(),
            }
        }

        /// Prove HyperlatticeFilter.filterCrossing does not call LatticePolicyEvaluator.evaluate
        pub fn process(&mut self) -> anyhow::Result<()> {
            let src = if self.filter_source.is_empty() {
                fs::read_to_string(default_filter_ts()).map_err(anyhow::Error::msg)?
            } else if Path::new(&self.filter_source).is_file() {
                fs::read_to_string(&self.filter_source).map_err(anyhow::Error::msg)?
            } else {
                self.filter_source.clone()
            };
            self.scan = live_opa_absent(&src).map_err(anyhow::Error::msg)?;
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unknown_path_former_rego_reason_is_closed_wall() -> Result<(), String> {
        let sets = load_policy_sets(&default_rego_path())?;
        let mut input = LatticeCompileInput::default();
        input.action_path = String::from("bogus:path");
        input.trust_tier = 3;
        input.category = String::from("agent_action");
        input.all_actions.push(String::from("webhook:incoming"));
        let compiled = compile_lattice_policy(&input, &sets);
        let admit = admit_collect_all(&compiled.walls);
        if admit.allow {
            return Err(String::from("expected closed walls"));
        }
        if admit
            .closed
            .iter()
            .any(|w| w.reason.contains("Unknown action path"))
            == false
        {
            return Err(String::from("former Rego deny missing as closed wall"));
        }
        Ok(())
    }

    #[test]
    fn filter_crossing_does_not_call_evaluate() -> Result<(), String> {
        let path = default_filter_ts();
        if path.is_file() == false {
            return Ok(());
        }
        let src = fs::read_to_string(&path).map_err(|e| e.to_string())?;
        live_opa_absent(&src).map(|_| ())
    }

    #[test]
    fn rego_source_proves_at_boot() -> Result<(), String> {
        let text = fs::read_to_string(default_rego_path()).map_err(|e| e.to_string())?;
        prove_rego_source(&text).map(|_| ())
    }
}
