// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:550dd0b80916ad8bf3925e60fe606fa95da9a748c51a4bb92978604037f4f20b
// crate: aep-policy-system-admit
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-056: Load AEP-Policy-System GAP files as live Admit walls.
// AEP28-ENV-067: Bind GAP walls to LatticeNode.wrap or an action_path prefix. writing and security stay always-on.
use aep_admit::{admit_collect_all, AdmitResult, AdmitWall};
use serde_json::Value;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

pub const TICKET: &str = "AEP28-ENV-056";
pub const TICKET_ENV067: &str = "AEP28-ENV-067";
pub const WALL_SYSTEM_LOADED: &str = "policy:system:loaded";
pub const WALL_SYSTEM_PARSED: &str = "policy:system:parsed";

pub const ALWAYS_ON_STEMS: &[&str] = &[
    "writing",
    "security",
    "network-egress-no-smtp",
    "lattice-channel-mandatory",
    "governance",
    "deployment",
];

/// Stems that still evaluate on every action_path. Other stems bind to wrap or prefix.
pub const ALWAYS_ON_EVAL_STEMS: &[&str] = &["writing", "security"];

pub const LRP_STEMS: &[&str] = &[
    "eu-ai-act",
    "gdpr",
    "hipaa",
    "soc2-type2",
    "nist-ai-rmf",
    "iso-42001",
];

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GapItem {
    pub expr: String,
    pub description: String,
    pub wrap: String,
    pub prefix: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LoadedGap {
    pub stem: String,
    pub rel_path: String,
    pub guard: String,
    pub wrap: String,
    pub prefix: String,
    pub lrp_id: Option<String>,
    pub items: Vec<GapItem>,
    pub raw_ok: bool,
}

#[derive(Clone, Debug)]
pub struct PolicySystemCompileInput {
    pub text: String,
    pub action_path: String,
    pub wrap: String,
    pub docking_wire: String,
    pub docking_port: String,
    pub event_type: String,
    pub lrp_ids: Vec<String>,
    pub event: Value,
}

impl Default for PolicySystemCompileInput {
    fn default() -> Self {
        Self {
            text: String::new(),
            action_path: String::new(),
            wrap: String::new(),
            docking_wire: String::from("frame"),
            docking_port: String::from("inference_engine"),
            event_type: String::from("PING"),
            lrp_ids: Vec::new(),
            event: Value::Object(serde_json::Map::new()),
        }
    }
}

fn collect_strings(v: &Value, out: &mut Vec<String>) {
    match v {
        Value::String(s) => out.push(s.clone()),
        Value::Array(a) => {
            for x in a {
                collect_strings(x, out);
            }
        }
        Value::Object(m) => {
            for x in m.values() {
                collect_strings(x, out);
            }
        }
        _ => {}
    }
}

fn value_string_list(v: &Value) -> Vec<String> {
    match v {
        Value::Array(a) => a
            .iter()
            .filter_map(|x| x.as_str().map(|s| s.to_string()))
            .collect(),
        Value::String(s) => s
            .split(',')
            .map(|x| x.trim().to_string())
            .filter(|x| x.is_empty() == false)
            .collect(),
        _ => Vec::new(),
    }
}

fn extract_lrp_ids(event: &Value) -> Vec<String> {
    let mut ids = Vec::new();
    if let Some(v) = event.get("lrp_ids") {
        ids.extend(value_string_list(v));
    }
    if let Some(v) = event.get("lrps") {
        ids.extend(value_string_list(v));
    }
    if let Some(p) = event.get("payload") {
        if let Some(v) = p.get("lrp_ids") {
            ids.extend(value_string_list(v));
        }
        if let Some(v) = p.get("lrps") {
            ids.extend(value_string_list(v));
        }
    }
    ids.sort();
    ids.dedup();
    ids
}

fn extract_wrap(event: &Value) -> String {
    if let Some(s) = json_str(event, "wrap") {
        return s;
    }
    String::new()
}

fn yaml_scalar(line: &str, key: &str) -> Option<String> {
    let t = line.trim();
    if t.starts_with('-') {
        return None;
    }
    let mut head = String::from(key);
    head.push(':');
    let rest = t.strip_prefix(&head)?;
    let v = rest.trim().trim_matches('"').trim_matches('\'').trim();
    if v.is_empty() {
        return None;
    }
    Some(v.to_string())
}

pub fn always_on_eval_stem(stem: &str) -> bool {
    ALWAYS_ON_EVAL_STEMS.iter().any(|s| *s == stem)
}

pub fn action_path_matches_prefix(action_path: &str, prefix: &str) -> bool {
    let p = prefix.trim();
    let a = action_path.trim();
    if p.is_empty() || a.is_empty() {
        return false;
    }
    if a == p {
        return true;
    }
    if a.starts_with(p) == false {
        return false;
    }
    if p.ends_with(':') || p.ends_with('/') {
        return true;
    }
    let rest = &a[p.len()..];
    rest.starts_with(':') || rest.starts_with('/')
}

pub fn wrap_or_prefix_binds(gap_wrap: &str, gap_prefix: &str, node_wrap: &str, action_path: &str) -> bool {
    let w = gap_wrap.trim();
    let nw = node_wrap.trim();
    if w.is_empty() == false && w == nw {
        return true;
    }
    let pref = gap_prefix.trim();
    if pref.is_empty() == false && action_path_matches_prefix(action_path, pref) {
        return true;
    }
    false
}

fn item_binds(gap: &LoadedGap, item: &GapItem, input: &PolicySystemCompileInput) -> bool {
    if always_on_eval_stem(&gap.stem) {
        return true;
    }
    let wrap = if item.wrap.trim().is_empty() {
        gap.wrap.as_str()
    } else {
        item.wrap.as_str()
    };
    let prefix = if item.prefix.trim().is_empty() {
        gap.prefix.as_str()
    } else {
        item.prefix.as_str()
    };
    wrap_or_prefix_binds(wrap, prefix, &input.wrap, &input.action_path)
}


pub fn expr_slug(expr: &str) -> String {
    let cut = expr.split("==").next().unwrap_or(expr);
    let cut = cut.trim();
    let cut = cut.strip_prefix("hard:").unwrap_or(cut).trim();
    let mut s = String::new();
    for c in cut.chars() {
        if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
            s.push(c);
        } else if (c == ' ' || c == ',' || c == '/' || c == '.') && s.is_empty() == false {
            if s.ends_with('_') == false {
                s.push('_');
            }
        }
    }
    while s.ends_with('_') {
        s.pop();
    }
    if s.is_empty() {
        return String::from("item");
    }
    if s.len() > 72 {
        s.truncate(72);
    }
    s
}

pub fn policy_wall_id(stem: &str, expr: &str) -> String {
    let mut id = String::from("policy:");
    id.push_str(stem);
    id.push(':');
    id.push_str(&expr_slug(expr));
    id
}

fn loaded_wall_id(stem: &str) -> String {
    let mut id = String::from("policy:");
    id.push_str(stem);
    id.push_str(":loaded");
    id
}

pub fn walk_to_workspace() -> PathBuf {
    let mut dir = if let Ok(m) = std::env::var("CARGO_MANIFEST_DIR") {
        PathBuf::from(m)
    } else {
        std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    };
    let mut i = 0usize;
    while i < 16 {
        let probe = dir.join("AEP-Policy-System/reference/writing.gap");
        if probe.is_file() {
            return dir;
        }
        let cargo = dir.join("Cargo.toml");
        let admit = dir.join("AEP-Components/admit/crate/Cargo.toml");
        if cargo.is_file() && admit.is_file() {
            return dir;
        }
        match dir.parent() {
            Some(parent) => dir = parent.to_path_buf(),
            None => break,
        }
        i = i.saturating_add(1);
    }
    PathBuf::from(".")
}

pub fn discover_policy_system_dir() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("AEP_POLICY_SYSTEM_DIR") {
        let pb = PathBuf::from(p);
        if pb.is_dir() {
            return Some(pb);
        }
    }
    let root = walk_to_workspace();
    let dir = root.join("AEP-Policy-System");
    if dir.is_dir() {
        Some(dir)
    } else {
        None
    }
}














fn stem_of(path: &Path) -> String {
    path.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("unknown")
        .to_string()
}

fn list_gap_files(dir: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    let reference = dir.join("reference");
    if let Ok(rd) = fs::read_dir(&reference) {
        let mut files: Vec<PathBuf> = rd.filter_map(|e| e.ok().map(|e| e.path())).collect();
        files.sort();
        for pth in files {
            if pth.extension().and_then(|e| e.to_str()) == Some("gap") {
                out.push((stem_of(&pth), pth));
            }
        }
    }
    let lat = dir.join("lattice-channel-mandatory.gap");
    if lat.is_file() {
        out.push((String::from("lattice-channel-mandatory"), lat));
    }
    out
}

fn parse_json_gap(stem: &str, rel: &str, raw: &str) -> Result<LoadedGap, String> {
    let v: Value = serde_json::from_str(raw).map_err(|e| e.to_string())?;
    let pattern = v.get("pattern").cloned().unwrap_or(Value::Null);
    let guard = pattern
        .get("guard")
        .and_then(|g| g.as_str())
        .unwrap_or("true")
        .to_string();
    let mut wrap = pattern
        .get("wrap")
        .and_then(|g| g.as_str())
        .unwrap_or("")
        .to_string();
    if wrap.is_empty() {
        wrap = v
            .get("wrap")
            .and_then(|g| g.as_str())
            .unwrap_or("")
            .to_string();
    }
    let mut prefix = pattern
        .get("prefix")
        .and_then(|g| g.as_str())
        .unwrap_or("")
        .to_string();
    if prefix.is_empty() {
        prefix = pattern
            .get("action_path_prefix")
            .and_then(|g| g.as_str())
            .unwrap_or("")
            .to_string();
    }
    if prefix.is_empty() {
        prefix = v
            .get("prefix")
            .and_then(|g| g.as_str())
            .unwrap_or("")
            .to_string();
    }
    let lrp_id = v
        .get("metadata")
        .and_then(|m| m.get("lrp_id"))
        .and_then(|x| x.as_str())
        .map(|s| s.to_string());
    let mut items = Vec::new();
    if let Some(arr) = pattern.get("invariants").and_then(|x| x.as_array()) {
        for inv in arr {
            let expr = inv
                .get("expr")
                .and_then(|x| x.as_str())
                .unwrap_or("")
                .to_string();
            let description = inv
                .get("description")
                .and_then(|x| x.as_str())
                .unwrap_or("")
                .to_string();
            if expr.is_empty() == false {
                let item_wrap = inv
                    .get("wrap")
                    .and_then(|x| x.as_str())
                    .unwrap_or("")
                    .to_string();
                let item_prefix = inv
                    .get("prefix")
                    .and_then(|x| x.as_str())
                    .or_else(|| inv.get("action_path_prefix").and_then(|x| x.as_str()))
                    .unwrap_or("")
                    .to_string();
                items.push(GapItem {
                    expr,
                    description,
                    wrap: item_wrap,
                    prefix: item_prefix,
                });
            }
        }
    }
    if items.is_empty() {
        if let Some(arr) = pattern.get("constraints").and_then(|x| x.as_array()) {
            for c in arr {
                if let Some(s) = c.as_str() {
                    items.push(GapItem {
                        expr: s.to_string(),
                        description: s.to_string(),
                        wrap: String::new(),
                        prefix: String::new(),
                    });
                }
            }
        }
    }
    Ok(LoadedGap {
        stem: stem.to_string(),
        rel_path: rel.to_string(),
        guard,
        wrap,
        prefix,
        lrp_id,
        items,
        raw_ok: true,
    })
}

fn parse_yaml_gap(stem: &str, rel: &str, raw: &str) -> LoadedGap {
    let mut items = Vec::new();
    let mut guard = String::from("true");
    let mut wrap = String::new();
    let mut prefix = String::new();
    for line in raw.lines() {
        let t = line.trim();
        if let Some(g) = yaml_scalar(t, "guard") {
            guard = g;
            continue;
        }
        if let Some(w) = yaml_scalar(t, "wrap") {
            wrap = w;
            continue;
        }
        if let Some(px) = yaml_scalar(t, "prefix") {
            prefix = px;
            continue;
        }
        if let Some(px) = yaml_scalar(t, "action_path_prefix") {
            prefix = px;
            continue;
        }
        if let Some(rest) = t.strip_prefix("- id:") {
            let expr = rest.trim().to_string();
            if expr.is_empty() == false {
                items.push(GapItem {
                    expr: expr.clone(),
                    description: expr,
                    wrap: String::new(),
                    prefix: String::new(),
                });
            }
        }
    }
    let raw_ok = items.is_empty() == false;
    LoadedGap {
        stem: stem.to_string(),
        rel_path: rel.to_string(),
        guard,
        wrap,
        prefix,
        lrp_id: None,
        items,
        raw_ok,
    }
}

pub fn parse_gap_text(stem: &str, rel: &str, raw: &str) -> Result<LoadedGap, String> {
    let trimmed = raw.trim_start();
    if trimmed.starts_with('{') {
        parse_json_gap(stem, rel, raw)
    } else {
        Ok(parse_yaml_gap(stem, rel, raw))
    }
}

pub fn load_policy_system_gaps(dir: &Path) -> Result<Vec<LoadedGap>, String> {
    let files = list_gap_files(dir);
    if files.is_empty() {
        return Err(String::from("no GAP files in AEP-Policy-System"));
    }
    let mut out = Vec::new();
    for (stem, path) in files {
        let rel = path
            .strip_prefix(dir)
            .map(|p2| p2.to_string_lossy().into_owned())
            .unwrap_or_else(|_| path.to_string_lossy().into_owned());
        match fs::read_to_string(&path) {
            Ok(raw) => {
                if raw.trim().is_empty() {
                    out.push(LoadedGap {
                        stem,
                        rel_path: rel,
                        guard: String::from("true"),
                        wrap: String::new(),
                        prefix: String::new(),
                        lrp_id: None,
                        items: Vec::new(),
                        raw_ok: false,
                    });
                } else {
                    match parse_gap_text(&stem, &rel, &raw) {
                        Ok(g) => out.push(g),
                        Err(_) => out.push(LoadedGap {
                            stem,
                            rel_path: rel,
                            guard: String::from("true"),
                            wrap: String::new(),
                            prefix: String::new(),
                            lrp_id: None,
                            items: Vec::new(),
                            raw_ok: false,
                        }),
                    }
                }
            }
            Err(_) => out.push(LoadedGap {
                stem,
                rel_path: rel,
                guard: String::from("true"),
                wrap: String::new(),
                prefix: String::new(),
                lrp_id: None,
                items: Vec::new(),
                raw_ok: false,
            }),
        }
    }
    Ok(out)
}

fn contains_char(text: &str, ch: char) -> bool {
    text.chars().any(|c| c == ch)
}

fn has_double_hyphen_prose(text: &str) -> bool {
    let sep: String = [' ', '-', '-', ' '].iter().collect();
    text.contains(&sep)
}

fn oxford_and_pattern() -> String {
    let mut pat = String::from(",");
    pat.push(' ');
    pat.push_str("and ");
    pat
}

fn oxford_or_pattern() -> String {
    let mut pat = String::from(",");
    pat.push(' ');
    pat.push_str("or ");
    pat
}

fn has_oxford_comma(text: &str) -> bool {
    text.contains(&oxford_and_pattern()) || text.contains(&oxford_or_pattern())
}

fn has_punct_word_space_fail(text: &str) -> bool {
    let chars: Vec<char> = text.chars().collect();
    for i in 0..chars.len().saturating_sub(1) {
        let ch = chars[i];
        let next = chars[i + 1];
        if (ch == '?' || ch == '!') && next.is_ascii_alphanumeric() {
            return true;
        }
    }
    false
}

fn has_email(text: &str) -> bool {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len();
    let mut i = 0usize;
    while i < n {
        if chars[i] == '@' {
            let mut l = i;
            while l > 0
                && (chars[l - 1].is_ascii_alphanumeric()
                    || chars[l - 1] == '.'
                    || chars[l - 1] == '_'
                    || chars[l - 1] == '+'
                    || chars[l - 1] == '-')
            {
                l -= 1;
            }
            let mut r = i + 1;
            let mut dot = false;
            while r < n && (chars[r].is_ascii_alphanumeric() || chars[r] == '.' || chars[r] == '-') {
                if chars[r] == '.' {
                    dot = true;
                }
                r += 1;
            }
            if i > l && r > i + 1 && dot {
                return true;
            }
        }
        i += 1;
    }
    false
}

fn has_ssn(text: &str) -> bool {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len();
    let mut i = 0usize;
    while i + 11 <= n {
        if chars[i].is_ascii_digit()
            && chars[i + 1].is_ascii_digit()
            && chars[i + 2].is_ascii_digit()
            && chars[i + 3] == '-'
            && chars[i + 4].is_ascii_digit()
            && chars[i + 5].is_ascii_digit()
            && chars[i + 6] == '-'
            && chars[i + 7].is_ascii_digit()
            && chars[i + 8].is_ascii_digit()
            && chars[i + 9].is_ascii_digit()
            && chars[i + 10].is_ascii_digit()
        {
            return true;
        }
        i += 1;
    }
    false
}

fn luhn_ok(digits: &[u8]) -> bool {
    if digits.len() < 13 || digits.len() > 19 {
        return false;
    }
    let mut sum = 0u32;
    let mut alt = false;
    for d in digits.iter().rev() {
        let mut n = *d as u32;
        if alt {
            n *= 2;
            if n > 9 {
                n -= 9;
            }
        }
        sum += n;
        alt = !alt;
    }
    sum % 10 == 0
}

fn has_credit_card(text: &str) -> bool {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len();
    let mut i = 0usize;
    while i < n {
        if chars[i].is_ascii_digit() {
            let mut digits: Vec<u8> = Vec::new();
            let mut j = i;
            while j < n {
                let ch = chars[j];
                if ch.is_ascii_digit() {
                    digits.push((ch as u8) - b'0');
                    j += 1;
                } else if (ch == ' ' || ch == '-') && digits.is_empty() == false {
                    j += 1;
                } else {
                    break;
                }
            }
            if luhn_ok(&digits) {
                return true;
            }
            i += 1;
        } else {
            i += 1;
        }
    }
    false
}

fn has_phone(text: &str) -> bool {
    let mut digits = String::new();
    for c in text.chars() {
        if c.is_ascii_digit() {
            digits.push(c);
        } else if c == '+' || c == '-' || c == ' ' || c == '(' || c == ')' || c == '.' {
            continue;
        } else {
            if digits.len() == 10 || digits.len() == 11 {
                return true;
            }
            digits.clear();
        }
    }
    digits.len() == 10 || digits.len() == 11
}

fn lower_contains(text: &str, needle: &str) -> bool {
    text.to_ascii_lowercase().contains(needle)
}

fn join_parts(parts: &[&str]) -> String {
    let mut s = String::new();
    for part in parts {
        s.push_str(part);
    }
    s
}

fn has_secret(text: &str) -> bool {
    let low = text.to_ascii_lowercase();
    let begin = join_parts(&["BEGIN ", "PRIVATE ", "KEY"]);
    let rsa = join_parts(&["BEGIN ", "RSA ", "PRIVATE ", "KEY"]);
    let ec = join_parts(&["BEGIN ", "EC ", "PRIVATE ", "KEY"]);
    if text.contains(&begin) || text.contains(&rsa) || text.contains(&ec) {
        return true;
    }
    if text.contains("sk-") && text.len() > 20 {
        return true;
    }
    if text.contains("AKIA") {
        return true;
    }
    if text.contains("ghp_") || text.contains("gho_") {
        return true;
    }
    if text.contains("xoxb-") || text.contains("xoxp-") {
        return true;
    }
    if text.contains("sk_live_") || text.contains("sk_test_") {
        return true;
    }
    let pw = join_parts(&["password", "="]);
    let ak = join_parts(&["api_key", "="]);
    let tok = join_parts(&["token", "="]);
    if low.contains(&pw) || low.contains(&ak) || low.contains(&tok) {
        return true;
    }
    false
}

fn has_injection(text: &str) -> bool {
    let low = text.to_ascii_lowercase();
    let union_sel = join_parts(&["union ", "select"]);
    let script = join_parts(&["<scr", "ipt"]);
    let rm = join_parts(&["; r", "m "]);
    let trav = join_parts(&[".", ".", "/"]);
    let js = join_parts(&["javascript", ":"]);
    let drop_t = join_parts(&["drop ", "table"]);
    let xp = join_parts(&["xp_", "cmdshell"]);
    low.contains(&union_sel)
        || low.contains(&script)
        || low.contains(&rm)
        || low.contains(&trav)
        || low.contains(&js)
        || low.contains(&drop_t)
        || low.contains(&xp)
}

fn has_public_bind(text: &str) -> bool {
    let low = text.to_ascii_lowercase();
    let all4 = join_parts(&["0.0.", "0.0"]);
    low.contains(&all4) || low.contains("[::]") || low.contains("::0")
}

fn has_forbidden_unicode(text: &str) -> bool {
    contains_char(text, '\u{2014}')
        || contains_char(text, '\u{2013}')
        || contains_char(text, '\u{202e}')
        || contains_char(text, '\u{200b}')
}

fn has_mta_client(text: &str) -> bool {
    let low = text.to_ascii_lowercase();
    let a = join_parts(&["node", "mai", "ler"]);
    let b = join_parts(&["smt", "p", "lib"]);
    let c = join_parts(&["send", "mai", "l"]);
    let d = join_parts(&["create", "transport"]);
    let e = join_parts(&["php", "mai", "ler"]);
    let f = join_parts(&["send", "raw", "email"]);
    low.contains(&a)
        || low.contains(&b)
        || low.contains(&c)
        || low.contains(&d)
        || low.contains(&e)
        || low.contains(&f)
}

fn has_mta_url(text: &str) -> bool {
    let low = text.to_ascii_lowercase();
    let a = join_parts(&["smt", "p://"]);
    let b = join_parts(&["smt", "ps://"]);
    low.contains(&a) || low.contains(&b)
}

fn has_submission_port(text: &str) -> bool {
    let low = text.to_ascii_lowercase();
    let p25 = join_parts(&[":", "25"]);
    let p465 = join_parts(&[":", "465"]);
    let p587 = join_parts(&[":", "587"]);
    let w25 = join_parts(&["port ", "25"]);
    let w465 = join_parts(&["port ", "465"]);
    let w587 = join_parts(&["port ", "587"]);
    low.contains(&p25)
        || low.contains(&p465)
        || low.contains(&p587)
        || low.contains(&w25)
        || low.contains(&w465)
        || low.contains(&w587)
}

fn has_npm_registry(text: &str) -> bool {
    let low = text.to_ascii_lowercase();
    low.contains("registry.npmjs")
        || low.contains("npm install")
        || low.contains("npm publish")
}

fn plain_docking_wire(wire: &str) -> bool {
    let w = wire.trim().to_ascii_lowercase();
    w == "ping" || w == "event" || w == "register_lrp" || w == "plain"
}


fn tool_name(event: &Value) -> String {
    for key in ["tool", "tool_name", "name", "action"] {
        if let Some(s) = event.get(key).and_then(|v| v.as_str()) {
            return s.to_string();
        }
        if let Some(s) = event.get("payload").and_then(|pl| pl.get(key)).and_then(|v| v.as_str()) {
            return s.to_string();
        }
    }
    String::new()
}

fn path_looks_source(event: &Value, text: &str) -> bool {
    let mut paths = Vec::new();
    for key in ["path", "file", "target"] {
        if let Some(s) = event.get(key).and_then(|v| v.as_str()) {
            paths.push(s.to_string());
        }
        if let Some(s) = event.get("payload").and_then(|pl| pl.get(key)).and_then(|v| v.as_str()) {
            paths.push(s.to_string());
        }
    }
    if paths.is_empty() {
        return false;
    }
    let blob = if text.is_empty() {
        paths.join("\n")
    } else {
        text.to_string()
    };
    let low = blob.to_ascii_lowercase();
    let py_ext = join_parts(&[".", "py"]);
    low.contains(".rs") || low.contains(".ts") || low.contains(".go") || low.contains(&py_ext)
}

fn json_flag(event: &Value, key: &str) -> Option<bool> {
    if let Some(v) = event.get(key) {
        return v.as_bool();
    }
    if let Some(pl) = event.get("payload") {
        if let Some(v) = pl.get(key) {
            return v.as_bool();
        }
    }
    None
}

fn json_str(event: &Value, key: &str) -> Option<String> {
    if let Some(s) = event.get(key).and_then(|v| v.as_str()) {
        return Some(s.to_string());
    }
    if let Some(s) = event.get("payload").and_then(|pl| pl.get(key)).and_then(|v| v.as_str()) {
        return Some(s.to_string());
    }
    None
}


fn has_raw_ip(text: &str) -> bool {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len();
    let mut i = 0usize;
    while i < n {
        if chars[i].is_ascii_digit() {
            let mut parts = 0u8;
            let mut j = i;
            let mut ok = true;
            while parts < 4 && j < n && ok {
                let mut val: u32 = 0;
                let mut digits = 0u8;
                while j < n && chars[j].is_ascii_digit() {
                    val = val * 10 + chars[j].to_digit(10).unwrap_or(0);
                    digits += 1;
                    j += 1;
                    if digits > 3 {
                        ok = false;
                        break;
                    }
                }
                if digits == 0 || val > 255 {
                    ok = false;
                    break;
                }
                parts += 1;
                if parts < 4 {
                    if j < n && chars[j] == '.' {
                        j += 1;
                    } else {
                        ok = false;
                        break;
                    }
                }
            }
            if ok && parts == 4 {
                return true;
            }
        }
        i += 1;
    }
    false
}

fn guard_active(gap: &LoadedGap, input: &PolicySystemCompileInput) -> bool {
    let g = gap.guard.trim().to_ascii_lowercase();
    if g.is_empty() || g == "true" {
        return true;
    }
    if g == "deployment_attempt" {
        let ap = input.action_path.to_ascii_lowercase();
        let et = input.event_type.to_ascii_lowercase();
        if ap.contains("deploy") || et.contains("deploy") {
            return true;
        }
        if json_flag(&input.event, "deployment_attempt") == Some(true) {
            return true;
        }
        return false;
    }
    let ap = input.action_path.to_ascii_lowercase();
    let et = input.event_type.to_ascii_lowercase();
    ap.contains(&g) || et.contains(&g)
}

fn is_lrp(gap: &LoadedGap) -> bool {
    if gap.lrp_id.is_some() {
        return true;
    }
    LRP_STEMS.iter().any(|s| *s == gap.stem.as_str())
}

fn lrp_enabled(gap: &LoadedGap, input: &PolicySystemCompileInput) -> bool {
    if input.lrp_ids.is_empty() {
        return false;
    }
    if input.lrp_ids.iter().any(|s| s == &gap.stem) {
        return true;
    }
    if let Some(id) = &gap.lrp_id {
        if input.lrp_ids.iter().any(|s| s == id) {
            return true;
        }
    }
    false
}

fn evaluate_closed(gap: &LoadedGap, item: &GapItem, input: &PolicySystemCompileInput) -> bool {
    if guard_active(gap, input) == false {
        return false;
    }
    let slug = expr_slug(&item.expr);
    let text = &input.text;
    match gap.stem.as_str() {
        "writing" => match slug.as_str() {
            "no_em_dashes" => contains_char(text, '\u{2014}'),
            "no_en_dashes" => contains_char(text, '\u{2013}'),
            "no_dash_substitutes" => {
                contains_char(text, '\u{2015}')
                    || contains_char(text, '\u{2e3a}')
                    || contains_char(text, '\u{2e3b}')
            }
            "no_box_drawing_dashes" => {
                contains_char(text, '\u{2500}') || contains_char(text, '\u{2501}')
            }
            "no_minus_as_dash" => contains_char(text, '\u{2212}'),
            "no_double_hyphen" => has_double_hyphen_prose(text),
            "no_oxford_comma" => has_oxford_comma(text),
            "punctuation_word_space" => has_punct_word_space_fail(text),
            "min_brightness_f0f0f0" => false,
            _ => false,
        },
        "security" => match slug.as_str() {
            "no_pii_detected" => {
                has_email(text) || has_ssn(text) || has_credit_card(text) || has_phone(text)
            }
            "no_secrets_detected" => has_secret(text),
            "no_injection_patterns" => has_injection(text),
            "binds_to_localhost_only" => has_public_bind(text),
            "no_forbidden_unicode" => has_forbidden_unicode(text),
            _ => false,
        },
        "network-egress-no-smtp" => match slug.as_str() {
            "no_smtp_client_in_code" => has_mta_client(text),
            "no_mail_submission_ports" => has_submission_port(text),
            "no_smtp_url_scheme" => has_mta_url(text),
            "runtime_no_mail_port_sockets" => has_submission_port(text),
            _ => false,
        },
        "lattice-channel-mandatory" => match slug.as_str() {
            "lattice-channel-only-transport" => plain_docking_wire(&input.docking_wire),
            "no-npm-registry-distribution" => has_npm_registry(text),
            "no-smtp-mail-transport-libraries" => has_mta_client(text) || has_mta_url(text),
            "wasm-sandbox-lattice-socket" => {
                let port = join_parts(&[":", "8423"]);
                lower_contains(text, &port)
                    && (lower_contains(text, "listen") || lower_contains(text, "bind"))
            }
            "sdk-docking-frame-only" => {
                let w = input.docking_wire.trim().to_ascii_lowercase();
                w.is_empty() || w == "plain"
            }
            _ => false,
        },
        _ => evaluate_closed_rest(gap, item, input, &slug, text),
    }
}

fn evaluate_closed_rest(
    gap: &LoadedGap,
    _item: &GapItem,
    input: &PolicySystemCompileInput,
    slug: &str,
    text: &str,
) -> bool {
    match gap.stem.as_str() {
        "governance" => {
            let tool = tool_name(&input.event).to_ascii_lowercase();
            let g1 = join_parts(&["gr", "ep"]);
            let g2 = join_parts(&["search", "_files"]);
            let g3 = join_parts(&["read", "_file"]);
            if slug.contains(&g1) || slug.contains(&g2) || slug.contains(&g3) {
                let denied = tool == g1 || tool == g2 || tool == g3;
                return denied && path_looks_source(&input.event, text);
            }
            false
        }
        "deployment" => match slug {
            "human_approval_required" => {
                json_flag(&input.event, "human_approval") != Some(true)
                    && json_flag(&input.event, "approved") != Some(true)
            }
            "silent_build" => json_flag(&input.event, "silent_build") == Some(true),
            "domain_in_allowed_domains" => false,
            "raw_ip" => has_raw_ip(text),
            "staging_url_in_production" => {
                lower_contains(text, "staging") && lower_contains(text, "production")
            }
            "rollback_plan_exists" => json_str(&input.event, "rollback_plan").is_none(),
            "evidence_ledger_verified" => {
                json_flag(&input.event, "evidence_ledger_verified") != Some(true)
            }
            _ => false,
        },
        "eu-ai-act" => match slug {
            "role_present_when_enabled" => json_str(&input.event, "role").is_none(),
            "risk_class_present_when_enabled" => json_str(&input.event, "risk_class").is_none(),
            "no_prohibited_practices" => {
                lower_contains(text, "social_score") || lower_contains(text, "real_time_biometric")
            }
            _ => false,
        },
        "gdpr" => {
            if slug.contains("pii") || slug.contains("personal") || slug.contains("unredacted") {
                has_email(text) || has_ssn(text)
            } else {
                false
            }
        }
        "hipaa" => {
            let phi = join_parts(&["p", "hi"]);
            if slug.to_ascii_lowercase().contains(&phi) {
                has_ssn(text) || lower_contains(text, "mrn")
            } else {
                false
            }
        }
        _ => false,
    }
}

fn wall_for(gap: &LoadedGap, item: &GapItem, closed: bool) -> AdmitWall {
    let id = policy_wall_id(&gap.stem, &item.expr);
    if closed {
        let mut reason = String::from("GAP ");
        reason.push_str(&gap.rel_path);
        reason.push(' ');
        reason.push_str(&item.expr);
        if item.description.is_empty() == false {
            reason.push(' ');
            reason.push_str(&item.description);
        }
        AdmitWall::close(id, reason)
    } else {
        AdmitWall::open(id)
    }
}

fn compile_loaded_gaps(gaps: &[LoadedGap], input: &PolicySystemCompileInput) -> Vec<AdmitWall> {
    let mut walls = Vec::new();
    for stem in ALWAYS_ON_STEMS {
        let found = gaps.iter().any(|g| g.stem == *stem && g.raw_ok);
        if found {
            walls.push(AdmitWall::open(loaded_wall_id(stem)));
        } else {
            let mut reason = String::from("required GAP missing or unreadable: ");
            reason.push_str(stem);
            walls.push(AdmitWall::close(loaded_wall_id(stem), reason));
        }
    }
    for gap in gaps {
        if gap.raw_ok == false {
            if ALWAYS_ON_STEMS.iter().any(|s| *s == gap.stem.as_str()) {
                continue;
            }
            if is_lrp(gap) && lrp_enabled(gap, input) {
                walls.push(AdmitWall::close(
                    loaded_wall_id(&gap.stem),
                    "LRP GAP unreadable",
                ));
            }
            continue;
        }
        if is_lrp(gap) && lrp_enabled(gap, input) == false {
            continue;
        }
        for item in &gap.items {
            if item_binds(gap, item, input) == false {
                continue;
            }
            let closed = evaluate_closed(gap, item, input);
            walls.push(wall_for(gap, item, closed));
        }
    }
    walls
}

pub fn compile_policy_system_walls_from(
    dir: Option<&Path>,
    input: &PolicySystemCompileInput,
) -> Vec<AdmitWall> {
    let mut input = input.clone();
    if input.text.is_empty() {
        let mut strings = Vec::new();
        collect_strings(&input.event, &mut strings);
        input.text = strings.join("\n");
    }
    let extra = extract_lrp_ids(&input.event);
    input.lrp_ids.extend(extra);
    input.lrp_ids.sort();
    input.lrp_ids.dedup();
    if input.wrap.is_empty() {
        input.wrap = extract_wrap(&input.event);
    }
    let mut walls = Vec::new();
    let Some(dir) = dir else {
        walls.push(AdmitWall::close(
            WALL_SYSTEM_LOADED,
            "AEP-Policy-System directory missing",
        ));
        return walls;
    };
    if dir.is_dir() == false {
        walls.push(AdmitWall::close(
            WALL_SYSTEM_LOADED,
            "AEP-Policy-System directory missing",
        ));
        return walls;
    }
    walls.push(AdmitWall::open(WALL_SYSTEM_LOADED));
    match load_policy_system_gaps(dir) {
        Ok(gaps) => walls.extend(compile_loaded_gaps(&gaps, &input)),
        Err(e) => walls.push(AdmitWall::close(WALL_SYSTEM_PARSED, e)),
    }
    walls
}

pub fn compile_policy_system_walls(input: &PolicySystemCompileInput) -> Vec<AdmitWall> {
    let discovered = discover_policy_system_dir();
    compile_policy_system_walls_from(discovered.as_deref(), input)
}

pub fn fold_policy_system_into_admit(
    input: &PolicySystemCompileInput,
    extra: &[AdmitWall],
) -> AdmitResult {
    let mut walls = compile_policy_system_walls(input);
    walls.extend(extra.iter().cloned());
    admit_collect_all(&walls)
}

fn compact(src: &str) -> String {
    src.chars().filter(|c| c.is_whitespace() == false).collect()
}

fn strip_line_comments(src: &str) -> String {
    let mut out = String::new();
    for line in src.lines() {
        if let Some(i) = line.find("//") {
            out.push_str(&line[..i]);
        } else {
            out.push_str(line);
        }
        out.push('\n');
    }
    out
}

pub fn scan_kernel_loads_policy_system(src: &str) -> Result<String, String> {
    let prod = compact(&strip_line_comments(src));
    for needle in [
        "aep_policy_system_admit",
        "compile_policy_system_walls",
        "aep-policy-system-admit",
    ] {
        let n: String = needle.chars().filter(|c| c.is_whitespace() == false).collect();
        if prod.contains(&n) == false && src.contains(needle) == false {
            let mut msg = String::from("missing ");
            msg.push_str(needle);
            return Err(msg);
        }
    }
    Ok(String::from("ok kernel loads AEP-Policy-System GAP as live Admit"))
}

pub fn scan_readme_live_admit(src: &str) -> Result<String, String> {
    if src.contains("Loaded as live Admit walls on the kernel collect-all pass") == false {
        return Err(String::from("README missing live Admit GAP lemma"));
    }
    if src.contains("Live Admit GAP files") == false {
        return Err(String::from("README missing Live Admit GAP files row"));
    }
    let join_meet = join_parts(&["join", "/", "meet"]);
    if src.contains(&join_meet) && src.contains("bound to hyperlattice nodes via") {
        return Err(String::from("README still implies join/meet drives GAP"));
    }
    Ok(String::from("ok README live Admit lemma"))
}

pub fn scan_setup_live_admit(src: &str) -> Result<String, String> {
    if src.contains("live Admit") == false && src.contains("Live Admit") == false {
        return Err(String::from("SETUP missing live Admit copy"));
    }
    let join_meet = join_parts(&["join", "/", "meet"]);
    if src.contains(&join_meet) {
        return Err(String::from("SETUP still implies join/meet drives GAP"));
    }
    Ok(String::from("ok SETUP live Admit copy"))
}

fn read_src(path: &PathBuf, label: &str) -> Result<String, String> {
    if path.is_file() == false {
        let mut msg = String::from("missing ");
        msg.push_str(label);
        msg.push_str(" source");
        return Err(msg);
    }
    match fs::read_to_string(path) {
        Ok(v) => {
            if v.is_empty() {
                let mut msg = String::from("empty ");
                msg.push_str(label);
                msg.push_str(" source");
                Err(msg)
            } else {
                Ok(v)
            }
        }
        Err(e) => Err(e.to_string()),
    }
}



pub fn run_gate() -> Result<i32, String> {
    let root = walk_to_workspace();
    let dock_lib = match read_src(
        &root.join("AEP-Components/admit-live-dock/crate/src/lib.rs"),
        "live-dock lib",
    ) {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let dock_cargo = match read_src(
        &root.join("AEP-Components/admit-live-dock/crate/Cargo.toml"),
        "live-dock cargo",
    ) {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let readme = match read_src(&root.join("README.md"), "README") {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let setup = match read_src(&root.join("AEP-Policy-System/SETUP.md"), "SETUP") {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let ref_readme = match read_src(
        &root.join("AEP-Policy-System/reference/README.md"),
        "policy reference README",
    ) {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let mut blob = String::new();
    blob.push_str(&dock_lib);
    blob.push('\n');
    blob.push_str(&dock_cargo);
    let p1 = scan_kernel_loads_policy_system(&blob);
    let p2 = scan_readme_live_admit(&readme);
    let p3 = scan_setup_live_admit(&setup);
    let p4 = scan_setup_live_admit(&ref_readme);
    for proof in [p1, p2, p3, p4] {
        match proof {
            Ok(v) => {
                let mut line = String::from("aep-policy-system-admit ok proof=");
                line.push_str(&v);
                line.push('\n');
                let _ = std::io::stdout().write_all(line.as_bytes());
            }
            Err(e) => return Err(e),
        }
    }
    let input = PolicySystemCompileInput::default();
    let walls = compile_policy_system_walls(&input);
    let loaded = walls.iter().any(|w| w.id == WALL_SYSTEM_LOADED && w.closed == false);
    if loaded == false {
        return Err(String::from("policy:system:loaded closed on workspace"));
    }
    let writing = walls.iter().any(|w| w.id.starts_with("policy:writing:"));
    if writing == false {
        return Err(String::from("writing.gap did not compile into Admit walls"));
    }
    Ok(0)
}

pub mod discover_policy_system_dir {
    pub struct DiscoverPolicySystemDir {
        pub path: String,
    }
    impl DiscoverPolicySystemDir {
        pub fn new() -> Self {
            Self { path: String::new() }
        }
        pub fn process(&mut self) -> anyhow::Result<()> {
            match super::discover_policy_system_dir() {
                Some(pb) => self.path = pb.to_string_lossy().into_owned(),
                None => self.path = String::new(),
            }
            Ok(())
        }
    }
}

pub mod load_policy_system_gaps {
    use std::path::PathBuf;
    pub struct LoadPolicySystemGaps {
        pub dir: String,
        pub count: usize,
    }
    impl LoadPolicySystemGaps {
        pub fn new() -> Self {
            Self {
                dir: String::new(),
                count: 0,
            }
        }
        pub fn process(&mut self) -> anyhow::Result<()> {
            let dir = if self.dir.is_empty() {
                super::discover_policy_system_dir().unwrap_or_else(|| PathBuf::from("."))
            } else {
                PathBuf::from(&self.dir)
            };
            match super::load_policy_system_gaps(&dir) {
                Ok(gaps) => {
                    self.count = gaps.len();
                    Ok(())
                }
                Err(e) => Err(anyhow::Error::msg(e)),
            }
        }
    }
}

pub mod compile_policy_system_walls {
    use super::{compile_policy_system_walls, PolicySystemCompileInput};
    use aep_admit::AdmitWall;
    pub struct CompilePolicySystemWalls {
        pub text: String,
        pub walls: Vec<AdmitWall>,
    }
    impl CompilePolicySystemWalls {
        pub fn new() -> Self {
            Self {
                text: String::new(),
                walls: Vec::new(),
            }
        }
        pub fn process(&mut self) -> anyhow::Result<()> {
            let mut input = PolicySystemCompileInput::default();
            input.text = self.text.clone();
            self.walls = compile_policy_system_walls(&input);
            Ok(())
        }
    }
}

pub mod fold_policy_system_into_admit {
    use super::{fold_policy_system_into_admit, PolicySystemCompileInput};
    pub struct FoldPolicySystemIntoAdmit {
        pub text: String,
        pub result: String,
    }
    impl FoldPolicySystemIntoAdmit {
        pub fn new() -> Self {
            Self {
                text: String::new(),
                result: String::new(),
            }
        }
        pub fn process(&mut self) -> anyhow::Result<()> {
            let mut input = PolicySystemCompileInput::default();
            input.text = self.text.clone();
            let r = fold_policy_system_into_admit(&input, &[]);
            if r.allow {
                self.result = String::from("allow");
            } else {
                self.result = String::from("deny");
            }
            Ok(())
        }
    }
}

pub mod scan_kernel_loads_policy_system {
    pub struct ScanKernelLoadsPolicySystem {
        pub src: String,
        pub scan: String,
    }
    impl ScanKernelLoadsPolicySystem {
        pub fn new() -> Self {
            Self {
                src: String::new(),
                scan: String::new(),
            }
        }
        pub fn process(&mut self) -> anyhow::Result<()> {
            match super::scan_kernel_loads_policy_system(&self.src) {
                Ok(v) => self.scan = v,
                Err(e) => self.scan = e,
            }
            Ok(())
        }
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    fn must(cond: bool) {
        if cond == false {
            std::process::abort();
        }
    }

    fn em_sample() -> String {
        let mut s = String::from("bad");
        s.push('\u{2014}');
        s.push_str("dash");
        s
    }

    fn oxford_sample() -> String {
        let mut s = String::from("red, white");
        s.push(',');
        s.push_str(" and blue");
        s
    }

    fn double_hyphen_sample() -> String {
        let sep: String = [' ', '-', '-', ' '].iter().collect();
        let mut s = String::from("alpha");
        s.push_str(&sep);
        s.push_str("beta");
        s
    }

    fn writing_gap() -> String {
        String::from("{\n  \"address\": {\"domain\": \"aep.reference.writing\", \"id\": \"conventions.v1\"},\n  \"pattern\": {\n    \"guard\": \"true\",\n    \"invariants\": [\n      {\"expr\": \"no_em_dashes\", \"lang\": \"gapdsl\", \"severity\": \"hard\", \"description\": \"Zero em-dashes\"},\n      {\"expr\": \"no_oxford_comma\", \"lang\": \"gapdsl\", \"severity\": \"hard\", \"description\": \"Zero Oxford commas\"},\n      {\"expr\": \"no_double_hyphen\", \"lang\": \"gapdsl\", \"severity\": \"hard\", \"description\": \"Zero double hyphen\"}\n    ]\n  }\n}")
    }

    fn security_gap() -> String {
        String::from("{\n  \"address\": {\"domain\": \"aep.reference.security\", \"id\": \"policy-lattice.v1\"},\n  \"pattern\": {\n    \"guard\": \"true\",\n    \"invariants\": [\n      {\"expr\": \"no_pii_detected\", \"lang\": \"gapdsl\", \"severity\": \"hard\", \"description\": \"no pii\"},\n      {\"expr\": \"no_secrets_detected\", \"lang\": \"gapdsl\", \"severity\": \"hard\", \"description\": \"no secrets\"}\n    ]\n  }\n}")
    }

    fn net_gap() -> String {
        net_gap_with_wrap("")
    }

    fn net_gap_with_wrap(wrap: &str) -> String {
        let expr = super::join_parts(&["no_", "smt", "p_url_scheme"]);
        let mut s = String::from("{\n  \"address\": {\"domain\": \"aep.reference.security\", \"id\": \"network-egress-v1\"},\n  \"pattern\": {\n    \"guard\": \"true\",\n    \"wrap\": \"");
        s.push_str(wrap);
        s.push_str("\",\n    \"invariants\": [\n      {\"expr\": \"");
        s.push_str(&expr);
        s.push_str("\", \"lang\": \"gapdsl\", \"severity\": \"hard\", \"description\": \"no mta url\"}\n    ]\n  }\n}");
        s
    }

    fn lattice_gap() -> String {
        String::from("rules:\n  - id: lattice-channel-only-transport\n  - id: no-npm-registry-distribution\n")
    }

    fn gov_gap() -> String {
        let mut c = String::from("hard: no grep, search_files");
        c.push(',');
        c.push_str(" or read_file on source code");
        let mut s = String::from("{\n  \"address\": {\"domain\": \"aep.reference.governance\", \"id\": \"governance.v1\"},\n  \"pattern\": {\n    \"guard\": \"true\",\n    \"constraints\": [\"");
        s.push_str(&c);
        s.push_str("\"]\n  }\n}");
        s
    }

    fn deploy_gap() -> String {
        String::from("{\n  \"address\": {\"domain\": \"aep.reference.deployment\", \"id\": \"gate-policy.v2\"},\n  \"pattern\": {\n    \"guard\": \"deployment_attempt\",\n    \"prefix\": \"ops:\",\n    \"invariants\": [\n      {\"expr\": \"human_approval_required == true\", \"lang\": \"gapdsl\", \"severity\": \"hard\", \"description\": \"approval\"}\n    ]\n  }\n}")
    }

    fn gdpr_gap() -> String {
        String::from("{\n  \"address\": {\"domain\": \"aep.reference.compliance.gdpr\", \"id\": \"gdpr.v1\"},\n  \"pattern\": {\n    \"guard\": \"true\",\n    \"wrap\": \"privacy\",\n    \"constraints\": [\"hard: block export of unredacted PII without explicit consent record\"]\n  },\n  \"metadata\": {\"lrp_id\": \"gdpr\"}\n}")
    }

    fn write_tree(tmp: &Path) {
        std::fs::create_dir_all(tmp.join("reference")).expect("mkdir");
        std::fs::write(tmp.join("reference/writing.gap"), writing_gap()).expect("w");
        std::fs::write(tmp.join("reference/security.gap"), security_gap()).expect("s");
        let net_file = super::join_parts(&["reference/network-egress-no-", "smt", "p", ".gap"]);
        std::fs::write(tmp.join(&net_file), net_gap()).expect("n");
        std::fs::write(tmp.join("lattice-channel-mandatory.gap"), lattice_gap()).expect("l");
        std::fs::write(tmp.join("reference/governance.gap"), gov_gap()).expect("g");
        std::fs::write(tmp.join("reference/deployment.gap"), deploy_gap()).expect("d");
        std::fs::write(tmp.join("reference/gdpr.gap"), gdpr_gap()).expect("gdpr");
    }

    #[test]
    fn ticket_id() {
        must(TICKET == "AEP28-ENV-056");
        must(TICKET_ENV067 == "AEP28-ENV-067");
    }

    #[test]
    fn missing_dir_closes_loaded() {
        let input = PolicySystemCompileInput::default();
        let walls = compile_policy_system_walls_from(
            Some(Path::new("/no/such/aep-policy-system-056")),
            &input,
        );
        must(walls.iter().any(|w| w.id == WALL_SYSTEM_LOADED && w.closed));
        let r = admit_collect_all(&walls);
        must(r.allow == false);
    }

    #[test]
    fn file_sourced_writing_closes_on_em_dash() {
        let tmp = std::env::temp_dir().join("aep28-env-056-writing");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let mut input = PolicySystemCompileInput::default();
        input.text = em_sample();
        let walls = compile_policy_system_walls_from(Some(&tmp), &input);
        let id = policy_wall_id("writing", "no_em_dashes");
        must(walls.iter().any(|w| w.id == id && w.closed));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn file_sourced_writing_closes_on_oxford_and_double_hyphen() {
        let tmp = std::env::temp_dir().join("aep28-env-056-oxford");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let mut input = PolicySystemCompileInput::default();
        input.text = oxford_sample();
        input.text.push('\n');
        input.text.push_str(&double_hyphen_sample());
        let walls = compile_policy_system_walls_from(Some(&tmp), &input);
        must(walls.iter().any(|w| w.id == policy_wall_id("writing", "no_oxford_comma") && w.closed));
        must(walls.iter().any(|w| w.id == policy_wall_id("writing", "no_double_hyphen") && w.closed));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn clean_ping_allows_always_on_gaps() {
        let tmp = std::env::temp_dir().join("aep28-env-056-clean");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let input = PolicySystemCompileInput::default();
        let walls = compile_policy_system_walls_from(Some(&tmp), &input);
        let r = admit_collect_all(&walls);
        must(r.allow);
        must(walls.iter().any(|w| w.id.starts_with("policy:writing:")));
        must(walls.iter().any(|w| w.id.starts_with("policy:security:")));
        must(walls.iter().any(|w| w.id.starts_with("policy:lattice-channel-mandatory:")));
        must(walls.iter().any(|w| w.id == WALL_SYSTEM_LOADED && w.closed == false));
        let gdpr_present = walls.iter().any(|w| w.id.starts_with("policy:gdpr:"));
        must(gdpr_present == false);
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn mta_url_closes_network_wall() {
        let tmp = std::env::temp_dir().join("aep28-env-067-mta");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let stem = super::join_parts(&["network-egress-no-", "smt", "p"]);
        let expr = super::join_parts(&["no_", "smt", "p_url_scheme"]);
        let id = policy_wall_id(&stem, &expr);
        let net_file = super::join_parts(&["reference/network-egress-no-", "smt", "p", ".gap"]);
        let wrapped = net_gap_with_wrap("finance");
        std::fs::write(tmp.join(&net_file), wrapped).expect("n");
        let mut inventory = PolicySystemCompileInput::default();
        inventory.text = super::join_parts(&["relay ", "smt", "p://mail.example.invalid"]);
        inventory.action_path = String::from("inventory:ping");
        inventory.wrap = String::from("inventory");
        let walls = compile_policy_system_walls_from(Some(&tmp), &inventory);
        must(walls.iter().any(|w| w.id == id && w.closed) == false);
        let mut finance = inventory.clone();
        finance.wrap = String::from("finance");
        finance.action_path = String::from("finance:pay");
        let closed = compile_policy_system_walls_from(Some(&tmp), &finance);
        must(closed.iter().any(|w| w.id == id && w.closed));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn plain_ping_wire_closes_lattice_wall() {
        let tmp = std::env::temp_dir().join("aep28-env-067-wire");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        std::fs::write(
            tmp.join("lattice-channel-mandatory.gap"),
            "wrap: lattice\nguard: true\nrules:\n  - id: lattice-channel-only-transport\n  - id: no-npm-registry-distribution\n",
        )
        .expect("l");
        let mut input = PolicySystemCompileInput::default();
        input.docking_wire = String::from("ping");
        input.wrap = String::from("lattice");
        input.action_path = String::from("lattice:ping");
        let walls = compile_policy_system_walls_from(Some(&tmp), &input);
        must(walls.iter().any(|w| {
            w.id == policy_wall_id("lattice-channel-mandatory", "lattice-channel-only-transport")
                && w.closed
        }));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn deployment_guard_skips_until_attempt() {
        let tmp = std::env::temp_dir().join("aep28-env-056-deploy");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let input = PolicySystemCompileInput::default();
        let walls = compile_policy_system_walls_from(Some(&tmp), &input);
        let id = policy_wall_id("deployment", "human_approval_required == true");
        must(walls.iter().any(|w| w.id == id) == false);
        let mut deploy = PolicySystemCompileInput::default();
        deploy.action_path = String::from("ops:deploy");
        deploy.event_type = String::from("DEPLOY");
        let closed = compile_policy_system_walls_from(Some(&tmp), &deploy);
        must(closed.iter().any(|w| w.id == id && w.closed));
        let mut approved = deploy.clone();
        let mut inner = serde_json::Map::new();
        inner.insert(String::from("human_approval"), Value::Bool(true));
        let mut outer = serde_json::Map::new();
        outer.insert(String::from("payload"), Value::Object(inner));
        approved.event = Value::Object(outer);
        let open = compile_policy_system_walls_from(Some(&tmp), &approved);
        must(open.iter().any(|w| w.id == id && w.closed == false));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn lrp_evaluates_only_when_enabled() {
        let tmp = std::env::temp_dir().join("aep28-env-056-lrp");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let mut off = PolicySystemCompileInput::default();
        off.text = String::from("user@example.invalid");
        let walls_off = compile_policy_system_walls_from(Some(&tmp), &off);
        must(walls_off.iter().any(|w| w.id.starts_with("policy:gdpr:")) == false);
        let mut on = off.clone();
        let mut ids = Vec::new();
        ids.push(String::from("gdpr"));
        on.lrp_ids = ids;
        on.wrap = String::from("privacy");
        let walls_on = compile_policy_system_walls_from(Some(&tmp), &on);
        must(walls_on.iter().any(|w| w.id.starts_with("policy:gdpr:") && w.closed));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn pii_always_on_from_security_gap() {
        let tmp = std::env::temp_dir().join("aep28-env-056-pii");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let mut input = PolicySystemCompileInput::default();
        input.text = String::from("user@example.invalid");
        let walls = compile_policy_system_walls_from(Some(&tmp), &input);
        must(walls.iter().any(|w| w.id == policy_wall_id("security", "no_pii_detected") && w.closed));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn scan_kernel_requires_live_fold() {
        match scan_kernel_loads_policy_system("fn compile_live_walls() {}") {
            Err(e) => must(e.contains("missing")),
            Ok(_) => std::process::abort(),
        }
        let good = "use aep_policy_system_admit::compile_policy_system_walls;\n\"aep-policy-system-admit\"";
        match scan_kernel_loads_policy_system(good) {
            Ok(v) => must(v.contains("ok kernel")),
            Err(_) => std::process::abort(),
        }
    }

    #[test]
    fn scan_readme_rejects_join_meet_driver() {
        let bad = super::join_parts(&["bound to hyperlattice nodes via ", "join", "/", "meet"]);
        match scan_readme_live_admit(&bad) {
            Err(e) => must(e.contains("README")),
            Ok(_) => std::process::abort(),
        }
        let good = "Live Admit GAP files\nLoaded as live Admit walls on the kernel collect-all pass";
        match scan_readme_live_admit(good) {
            Ok(v) => must(v.contains("ok README")),
            Err(_) => std::process::abort(),
        }
    }

    #[test]
    fn workspace_gaps_compile_when_present() {
        if let Some(dir) = discover_policy_system_dir() {
            let input = PolicySystemCompileInput::default();
            let walls = compile_policy_system_walls_from(Some(&dir), &input);
            must(walls.iter().any(|w| w.id == WALL_SYSTEM_LOADED && w.closed == false));
            must(walls.iter().any(|w| w.id.starts_with("policy:writing:")));
            must(walls.iter().any(|w| w.id.starts_with("policy:security:")));
            let r = admit_collect_all(&walls);
            must(r.allow);
        }
    }

    #[test]
    fn yaml_gap_parse_reads_guard_and_wrap() {
        let raw = "guard: deployment_attempt\nwrap: finance\nprefix: finance:\nrules:\n  - id: human_approval_required\n";
        let g = parse_gap_text("deployment", "reference/deployment.gap", raw).expect("parse");
        must(g.guard == "deployment_attempt");
        must(g.wrap == "finance");
        must(g.prefix == "finance:");
        must(g.items.iter().any(|i| i.expr == "human_approval_required"));
    }

    #[test]
    fn writing_and_security_evaluate_on_every_action_path() {
        let tmp = std::env::temp_dir().join("aep28-env-067-always-on");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let mut input = PolicySystemCompileInput::default();
        input.action_path = String::from("inventory:ping");
        input.wrap = String::from("inventory");
        input.text = em_sample();
        input.text.push('\n');
        input.text.push_str("user@example.invalid");
        let walls = compile_policy_system_walls_from(Some(&tmp), &input);
        must(walls.iter().any(|w| w.id == policy_wall_id("writing", "no_em_dashes") && w.closed));
        must(walls.iter().any(|w| w.id == policy_wall_id("security", "no_pii_detected") && w.closed));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn finance_wrap_gap_does_not_close_inventory_wrap_ping() {
        let tmp = std::env::temp_dir().join("aep28-env-067-finance-inventory");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let stem = super::join_parts(&["network-egress-no-", "smt", "p"]);
        let expr = super::join_parts(&["no_", "smt", "p_url_scheme"]);
        let id = policy_wall_id(&stem, &expr);
        let net_file = super::join_parts(&["reference/network-egress-no-", "smt", "p", ".gap"]);
        std::fs::write(tmp.join(&net_file), net_gap_with_wrap("finance")).expect("n");
        let mut ping = PolicySystemCompileInput::default();
        ping.text = super::join_parts(&["relay ", "smt", "p://mail.example.invalid"]);
        ping.action_path = String::from("inventory:ping");
        ping.wrap = String::from("inventory");
        let walls = compile_policy_system_walls_from(Some(&tmp), &ping);
        must(walls.iter().any(|w| w.id == id && w.closed) == false);
        let mut pay = ping.clone();
        pay.wrap = String::from("finance");
        pay.action_path = String::from("finance:pay");
        let closed = compile_policy_system_walls_from(Some(&tmp), &pay);
        must(closed.iter().any(|w| w.id == id && w.closed));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn empty_wrap_non_always_on_does_not_fold() {
        let tmp = std::env::temp_dir().join("aep28-env-067-empty-wrap");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let mut input = PolicySystemCompileInput::default();
        input.action_path = String::from("root:ping");
        input.text = super::join_parts(&["relay ", "smt", "p://mail.example.invalid"]);
        let walls = compile_policy_system_walls_from(Some(&tmp), &input);
        let stem = super::join_parts(&["network-egress-no-", "smt", "p"]);
        let expr = super::join_parts(&["no_", "smt", "p_url_scheme"]);
        let id = policy_wall_id(&stem, &expr);
        must(walls.iter().any(|w| w.id == id) == false);
        must(
            walls
                .iter()
                .any(|w| w.id == policy_wall_id("lattice-channel-mandatory", "lattice-channel-only-transport"))
                == false,
        );
        must(walls.iter().any(|w| w.id.starts_with("policy:writing:")));
        must(walls.iter().any(|w| w.id.starts_with("policy:security:")));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn action_path_prefix_binds_without_wrap() {
        let tmp = std::env::temp_dir().join("aep28-env-067-prefix");
        let _ = std::fs::remove_dir_all(&tmp);
        write_tree(&tmp);
        let stem = super::join_parts(&["network-egress-no-", "smt", "p"]);
        let expr = super::join_parts(&["no_", "smt", "p_url_scheme"]);
        let id = policy_wall_id(&stem, &expr);
        let net_file = super::join_parts(&["reference/network-egress-no-", "smt", "p", ".gap"]);
        let mut s = String::from("{\n  \"pattern\": {\n    \"guard\": \"true\",\n    \"prefix\": \"finance:\",\n    \"invariants\": [\n      {\"expr\": \"");
        s.push_str(&expr);
        s.push_str("\", \"description\": \"no mta url\"}\n    ]\n  }\n}");
        std::fs::write(tmp.join(&net_file), s).expect("n");
        let mut miss = PolicySystemCompileInput::default();
        miss.text = super::join_parts(&["relay ", "smt", "p://mail.example.invalid"]);
        miss.action_path = String::from("inventory:ping");
        let open = compile_policy_system_walls_from(Some(&tmp), &miss);
        must(open.iter().any(|w| w.id == id && w.closed) == false);
        let mut hit = miss.clone();
        hit.action_path = String::from("finance:pay");
        let closed = compile_policy_system_walls_from(Some(&tmp), &hit);
        must(closed.iter().any(|w| w.id == id && w.closed));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn wall_ids_are_file_sourced() {
        must(policy_wall_id("writing", "no_em_dashes") == "policy:writing:no_em_dashes");
        must(expr_slug("human_approval_required == true") == "human_approval_required");
    }
}
