//go:build integration

package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestDetect_Integration_AllFormats(t *testing.T) {
	formats := []string{"table", "json", "yaml"}

	for _, format := range formats {
		t.Run(format, func(t *testing.T) {
			cmd := newDetectCmd()
			buf := new(bytes.Buffer)
			cmd.SetOut(buf)
			cmd.SetErr(buf)
			cmd.SetArgs([]string{"--output", format})

			err := cmd.Execute()
			if err != nil {
				t.Fatalf("Execute() error: %v", err)
			}

			output := buf.String()
			if len(output) == 0 {
				t.Error("empty output")
			}

			// Validate format
			switch format {
			case "json":
				var result map[string]any
				if err := json.Unmarshal([]byte(output), &result); err != nil {
					t.Errorf("invalid JSON: %v", err)
				}
			case "yaml":
				var result map[string]any
				if err := yaml.Unmarshal([]byte(output), &result); err != nil {
					t.Errorf("invalid YAML: %v", err)
				}
			}
		})
	}
}

func TestDetectConfig_Integration_WriteFile(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "test-config.yaml")

	cmd := newDetectCmd()
	buf := new(bytes.Buffer)
	cmd.SetOut(buf)
	cmd.SetErr(buf)
	cmd.SetArgs([]string{"config", "--output", configPath})

	err := cmd.Execute()
	if err != nil {
		t.Fatalf("Execute() error: %v", err)
	}

	// Verify file was created
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error: %v", err)
	}

	if len(content) == 0 {
		t.Error("config file is empty")
	}

	// Verify it's valid YAML
	var config map[string]any
	if err := yaml.Unmarshal(content, &config); err != nil {
		t.Errorf("invalid YAML in config: %v", err)
	}

	// Verify security section exists
	if _, ok := config["security"]; !ok {
		t.Error("config missing security section")
	}
}

func TestDetectConfig_Integration_Stdout(t *testing.T) {
	cmd := newDetectCmd()
	buf := new(bytes.Buffer)
	cmd.SetOut(buf)
	cmd.SetErr(buf)
	cmd.SetArgs([]string{"config"})

	err := cmd.Execute()
	if err != nil {
		t.Fatalf("Execute() error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "Generated by: aep-caw detect config") {
		t.Error("output missing header")
	}
}
