// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:63d4d095acc96081241c70d0f3be21ccf211c00d6b0491d7753cdcb4975f84c7
// crate: aep-live-crossing-lab-off
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-013: HyperlatticeFilter.filterCrossing never calls latticeFilter.filterAsync, including when AEP_LAB_LATTICE_FILTER is on.
// Bound extract to the filterCrossing method. Comment skip is JSDoc-safe. Apply satisfied-action is not lab filterAsync.

use std::fs;
use std::path::{Path, PathBuf};

fn find_filter_crossing_sig(src: &str) -> Option<usize> {
    if let Some(i) = src.find("async filterCrossing") {
        return Some(i);
    }
    let mut offset = 0usize;
    for line in src.lines() {
        if is_comment_line(line) == false {
            if let Some(col) = line.find("filterCrossing(") {
                let before = line[..col].trim_end();
                if before.ends_with('.') == false {
                    return Some(offset + col);
                }
            }
        }
        offset = offset.saturating_add(line.len()).saturating_add(1);
    }
    None
}

fn extract_filter_crossing(src: &str) -> String {
    let sig = match find_filter_crossing_sig(src) {
        Some(v) => v,
        None => return String::new(),
    };
    if sig >= src.len() {
        return String::new();
    }
    let rest = &src[sig..];
    extract_balanced_method(rest)
}

fn extract_balanced_method(rest: &str) -> String {
    let bytes = rest.as_bytes();
    let start = match rest.find('{') {
        Some(v) => v,
        None => return String::new(),
    };
    let mut i = start;
    let mut depth: i32 = 0;
    let mut mode: u8 = 0;
    let mut tmpl_expr: i32 = 0;
    while i < bytes.len() {
        let c = bytes[i];
        let n = if i + 1 < bytes.len() { bytes[i + 1] } else { 0 };
        match mode {
            1 => {
                if c == b'\\' {
                    i = i.saturating_add(2);
                    continue;
                }
                if c == b'\'' {
                    mode = 0;
                }
            }
            2 => {
                if c == b'\\' {
                    i = i.saturating_add(2);
                    continue;
                }
                if c == b'"' {
                    mode = 0;
                }
            }
            3 => {
                if c == b'\\' {
                    i = i.saturating_add(2);
                    continue;
                }
                if c == b'`' && tmpl_expr == 0 {
                    mode = 0;
                } else if c == b'$' && n == b'{' {
                    tmpl_expr = tmpl_expr.saturating_add(1);
                    i = i.saturating_add(2);
                    continue;
                } else if tmpl_expr > 0 {
                    if c == b'{' {
                        tmpl_expr = tmpl_expr.saturating_add(1);
                    } else if c == b'}' {
                        tmpl_expr = tmpl_expr.saturating_sub(1);
                    }
                }
            }
            4 => {
                if c == b'\n' {
                    mode = 0;
                }
            }
            5 => {
                if c == b'*' && n == b'/' {
                    mode = 0;
                    i = i.saturating_add(2);
                    continue;
                }
            }
            _ => {
                if c == b'/' && n == b'/' {
                    mode = 4;
                    i = i.saturating_add(2);
                    continue;
                }
                if c == b'/' && n == b'*' {
                    mode = 5;
                    i = i.saturating_add(2);
                    continue;
                }
                if c == b'\'' {
                    mode = 1;
                } else if c == b'"' {
                    mode = 2;
                } else if c == b'`' {
                    mode = 3;
                    tmpl_expr = 0;
                } else if c == b'{' {
                    depth = depth.saturating_add(1);
                } else if c == b'}' {
                    depth = depth.saturating_sub(1);
                    if depth == 0 {
                        return rest[..=i].to_string();
                    }
                }
            }
        }
        i = i.saturating_add(1);
    }
    String::new()
}

fn is_comment_line(line: &str) -> bool {
    let t = line.trim_start();
    if t.starts_with("//") || t.starts_with("/*") || t.starts_with("*/") {
        return true;
    }
    if let Some(rest) = t.strip_prefix('*') {
        return rest.is_empty() || rest.starts_with(' ') || rest.starts_with('/');
    }
    false
}

pub fn scan_live_lab_filter(filter_source: &str) -> Result<String, String> {
    let body = extract_filter_crossing(filter_source);
    if body.is_empty() {
        return Err(String::from("filterCrossing not found"));
    }
    for line in body.lines() {
        if is_comment_line(line) {
            continue;
        }
        if line.contains("latticeFilter.filterAsync") {
            return Err(String::from(
                "filterCrossing still calls latticeFilter.filterAsync when AEP_LAB_LATTICE_FILTER is on",
            ));
        }
        if line.contains("labLatticeFilterEnabled") {
            return Err(String::from(
                "filterCrossing still branches on labLatticeFilterEnabled",
            ));
        }
    }
    if body.contains("admitCollectAll") == false {
        return Err(String::from("filterCrossing does not admitCollectAll"));
    }
    Ok(String::from("ok live lab filter absent on filterCrossing"))
}

pub fn default_filter_ts() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../dynAEP/bridge/hyperlattice/HyperlatticeFilter.ts")
}

pub fn run_gate(filter: &Path) -> Result<i32, String> {
    if filter.is_file() == false {
        return Ok(0);
    }
    let src = fs::read_to_string(filter).map_err(|e| e.to_string())?;
    let proof = scan_live_lab_filter(&src)?;
    println!("aep-live-crossing-lab-off ok proof={}", proof);
    Ok(0)
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: live_lab_filter_absent domain:dynaep type:service
pub mod live_lab_filter_absent {
    use super::*;

    pub struct LiveLabFilterAbsent {
        pub filter_source: String,
        pub scan: String,
    }

    impl LiveLabFilterAbsent {
        pub fn new() -> Self {
            Self {
                filter_source: String::new(),
                scan: String::new(),
            }
        }

        /// Fail CI if HyperlatticeFilter.filterCrossing still calls latticeFilter.filterAsync when AEP_LAB_LATTICE_FILTER is on
        pub fn process(&mut self) -> anyhow::Result<()> {
            if Path::new(&self.filter_source).is_file() == false && self.filter_source.contains('/') {
                self.scan = String::from("parked");
                return Ok(());
            }
            if Path::new(&self.filter_source).is_file() == false && self.filter_source.contains('/') {
                self.scan = String::from("parked");
                return Ok(());
            }
            let src = if self.filter_source.is_empty() {
                fs::read_to_string(default_filter_ts()).map_err(anyhow::Error::msg)?
            } else if Path::new(&self.filter_source).is_file() {
                fs::read_to_string(&self.filter_source).map_err(anyhow::Error::msg)?
            } else {
                self.filter_source.clone()
            };
            self.scan = scan_live_lab_filter(&src).map_err(anyhow::Error::msg)?;
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn good_filter() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    const admit = admitCollectAll(walls);\n    const applied = admit.allow;\n    if (applied) { this.latticeFilter.markSatisfied(event.action_path, event.agent_id); }\n    return { admit, applied };\n  }\n}\n"
    }

    fn lab_filter() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    const admit = admitCollectAll(walls);\n    const applied = admit.allow;\n    if (labLatticeFilterEnabled()) {\n      await this.latticeFilter.filterAsync(event);\n    }\n    return { admit, applied };\n  }\n}\n"
    }

    fn skip_filter() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    if (labLatticeFilterEnabled()) { return this.latticeFilter.filterAsync(event); }\n    return runEvaluationChain(event);\n  }\n}\n"
    }

    fn helper_after() -> String {
        let mut s = String::from(good_filter());
        s.push_str("export function labLatticeFilterEnabled() { return false; }\n");
        s.push_str("  *[Symbol.iterator]() { return this.latticeFilter.filterAsync; }\n");
        s
    }

    fn commented_lab() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    const admit = admitCollectAll(walls);\n    // await this.latticeFilter.filterAsync(event);\n    const applied = admit.allow;\n    return { admit, applied };\n  }\n}\n"
    }

    fn template_walls() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    walls.push(admitWallOpen(\x60constraint:${ok}\x60));\n    const admit = admitCollectAll(walls);\n    const applied = admit.allow;\n    return { admit, applied };\n  }\n}\n"
    }

    #[test]
    fn lab_call_fails_gate() {
        let err = scan_live_lab_filter(lab_filter()).unwrap_err();
        assert_eq!(err.contains("filterAsync") || err.contains("labLatticeFilterEnabled"), true);
    }

    #[test]
    fn lab_skip_fails_gate() {
        let err = scan_live_lab_filter(skip_filter()).unwrap_err();
        assert_eq!(err.contains("filterAsync") || err.contains("labLatticeFilterEnabled"), true);
    }

    #[test]
    fn good_filter_passes() {
        assert_eq!(scan_live_lab_filter(good_filter()).is_ok(), true);
    }

    #[test]
    fn helper_after_method_does_not_false_refuse() {
        assert_eq!(scan_live_lab_filter(&helper_after()).is_ok(), true);
    }

    #[test]
    fn commented_lab_call_does_not_fail() {
        assert_eq!(scan_live_lab_filter(commented_lab()).is_ok(), true);
    }

    #[test]
    fn template_literal_braces_do_not_truncate_method() {
        assert_eq!(scan_live_lab_filter(template_walls()).is_ok(), true);
    }

    #[test]
    fn star_iterator_is_not_a_comment() {
        assert_eq!(is_comment_line("    *[Symbol.iterator]() { }"), false);
        assert_eq!(is_comment_line("   * JSDoc line"), true);
        assert_eq!(is_comment_line("    // note"), true);
    }

    #[test]
    fn live_filter_has_no_lab_call_when_present() {
        std::env::set_var("AEP_LAB_LATTICE_FILTER", "1");
        let path = default_filter_ts();
        if path.is_file() == false { return; }
        let src = fs::read_to_string(&path).unwrap_or_default();
        assert_eq!(src.is_empty(), false);
        assert_eq!(scan_live_lab_filter(&src).is_ok(), true);
    }
}
