// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:b3c4cfa53d76cef31f0ac4f3a8c68fa6c6f12f98b5685ce061ee0e177cb0a8a1
// crate: aep-envelope-wrap-journals
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-016: Journals after residual wrap tickets land.
// Residual wrap tickets have not landed, so journals for that residual are not due.

use std::fs;
use std::path::{Path, PathBuf};

pub const RESIDUAL_WRAP_TICKETS: &[&str] = &[
    "AEP28-ENV-012",
    "AEP28-ENV-013",
    "AEP28-ENV-014",
    "AEP28-ENV-015",
];

pub const ADMIT_CRATE_REL: &str = "admit/crate";
pub const SKIP_SELF: &str = "envelope-wrap-journals";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TicketLanded {
    pub ticket: String,
    pub landed: bool,
    pub evidence: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WaveReport {
    pub landed: Vec<TicketLanded>,
    pub missing: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct JournalVerdict {
    pub allow: bool,
    pub reason: String,
    pub wave: WaveReport,
}

pub fn ticket_in_source(source: &str, ticket: &str) -> bool {
    source.contains(ticket)
}

pub fn default_components_root() -> PathBuf {
    let dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| String::from("."));
    PathBuf::from(dir).join("../..")
}

pub fn default_admit_crate() -> PathBuf {
    default_components_root().join(ADMIT_CRATE_REL)
}

fn is_scan_name(name: &str) -> bool {
    name.ends_with(".rs")
        || name.ends_with(".gaplune")
        || name.ends_with(".ts")
        || name.ends_with(".mjs")
        || name.ends_with(".md")
        || name.ends_with(".sh")
}

fn skip_dir_name(name: &str) -> bool {
    name == ".git" || name == "target" || name == "node_modules"
}

fn collect_sources(root: &Path, out: &mut Vec<(String, String)>) {
    let mut stack = Vec::new();
    stack.push(root.to_path_buf());
    while let Some(dir) = stack.pop() {
        let rd = match fs::read_dir(&dir) {
            Ok(v) => v,
            Err(_) => continue,
        };
        for ent in rd.flatten() {
            let path = ent.path();
            let name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("")
                .to_string();
            if skip_dir_name(&name) {
                continue;
            }
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if is_scan_name(&name) == false {
                continue;
            }
            if let Ok(src) = fs::read_to_string(&path) {
                out.push((path.to_string_lossy().into_owned(), src));
            }
        }
    }
}

pub fn evidence_for_ticket(files: &[(String, String)], ticket: &str) -> Option<String> {
    for (path, src) in files {
        if path.contains(SKIP_SELF) {
            continue;
        }
        if ticket_in_source(src, ticket) {
            return Some(path.clone());
        }
    }
    None
}

pub fn scan_wave(root: &Path) -> WaveReport {
    let mut files = Vec::new();
    collect_sources(root, &mut files);
    let mut landed = Vec::new();
    let mut missing = Vec::new();
    for ticket in RESIDUAL_WRAP_TICKETS {
        if let Some(ev) = evidence_for_ticket(&files, ticket) {
            landed.push(TicketLanded {
                ticket: (*ticket).to_string(),
                landed: true,
                evidence: ev,
            });
            continue;
        }
        missing.push((*ticket).to_string());
        landed.push(TicketLanded {
            ticket: (*ticket).to_string(),
            landed: false,
            evidence: String::new(),
        });
    }
    WaveReport { landed, missing }
}

pub fn journal_allow(wave: &WaveReport) -> JournalVerdict {
    if wave.missing.is_empty() {
        JournalVerdict {
            allow: true,
            reason: String::from(
                "residual wrap wave landed; journals allowed on residual wrap crates",
            ),
            wave: wave.clone(),
        }
    } else {
        let mut reason = String::from(
            "journals denied until residual wrap tickets land; journals for that residual are not due: ",
        );
        reason.push_str(&wave.missing.join(","));
        JournalVerdict {
            allow: false,
            reason,
            wave: wave.clone(),
        }
    }
}

pub fn run_gate(root: &Path) -> JournalVerdict {
    let wave = scan_wave(root);
    journal_allow(&wave)
}

pub fn format_verdict(v: &JournalVerdict) -> String {
    let mut out = String::new();
    if v.allow {
        out.push_str("allow\n");
    } else {
        out.push_str("deny\n");
    }
    out.push_str(&v.reason);
    out.push('\n');
    for t in &v.wave.landed {
        out.push_str(&t.ticket);
        if t.landed {
            out.push_str(" landed ");
            out.push_str(&t.evidence);
        } else {
            out.push_str(" missing");
        }
        out.push('\n');
    }
    out
}

fn err_msg(msg: String) -> anyhow::Error {
    anyhow::Error::msg(msg)
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: residual_wrap_ticket_landed domain:admit type:service
pub mod residual_wrap_ticket_landed {
    use super::{err_msg, ticket_in_source};

    pub struct ResidualWrapTicketLanded {
        pub source: String,
        pub ticket: String,
        pub landed: String,
    }

    impl ResidualWrapTicketLanded {
        pub fn new() -> Self {
            Self {
                source: String::new(),
                ticket: String::from("AEP28-ENV-012"),
                landed: String::new(),
            }
        }

        /// Prove one residual wrap ticket landed from registration or crate source
        pub fn process(&mut self) -> anyhow::Result<()> {
            if ticket_in_source(&self.source, &self.ticket) {
                self.landed = String::from("true");
                Ok(())
            } else {
                self.landed = String::from("false");
                let mut msg = String::from("residual wrap ticket not landed: ");
                msg.push_str(&self.ticket);
                Err(err_msg(msg))
            }
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: residual_wrap_wave_landed domain:admit type:service
pub mod residual_wrap_wave_landed {
    use super::{err_msg, scan_wave, WaveReport};
    use std::path::Path;

    pub struct ResidualWrapWaveLanded {
        pub tree: String,
        pub report: String,
    }

    impl ResidualWrapWaveLanded {
        pub fn new() -> Self {
            Self {
                tree: String::new(),
                report: String::new(),
            }
        }

        /// Prove AEP28-ENV-012 through AEP28-ENV-015 all landed before residual wrap journals
        pub fn process(&mut self) -> anyhow::Result<()> {
            let wave: WaveReport = scan_wave(Path::new(&self.tree));
            if wave.missing.is_empty() {
                self.report = String::from("landed");
                Ok(())
            } else {
                self.report = wave.missing.join(",");
                let mut msg = String::from("residual wrap wave missing ");
                msg.push_str(&wave.missing.join(","));
                Err(err_msg(msg))
            }
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: residual_wrap_journal_gate domain:admit type:service
pub mod residual_wrap_journal_gate {
    use super::{err_msg, journal_allow, scan_wave};
    use std::path::Path;

    pub struct ResidualWrapJournalGate {
        pub wave: String,
        pub allow: String,
    }

    impl ResidualWrapJournalGate {
        pub fn new() -> Self {
            Self {
                wave: String::new(),
                allow: String::new(),
            }
        }

        /// Deny residual wrap journals until residual wrap tickets land. Journals for that residual are not due while tickets are missing.
        pub fn process(&mut self) -> anyhow::Result<()> {
            let report = scan_wave(Path::new(&self.wave));
            let v = journal_allow(&report);
            if v.allow {
                self.allow = String::from("true");
                Ok(())
            } else {
                self.allow = String::from("false");
                Err(err_msg(v.reason.clone()))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn must(cond: bool) {
        if cond == false {
            std::process::abort();
        }
    }

    fn temp_root(tag: &str) -> PathBuf {
        let n = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(1);
        let mut name = String::from("aep-env-016-");
        name.push_str(tag);
        name.push('-');
        name.push_str(&n.to_string());
        let p = PathBuf::from("/tmp").join(name);
        let _ = fs::create_dir_all(&p);
        p
    }

    fn write_file(root: &Path, rel: &str, body: &str) {
        let p = root.join(rel);
        if let Some(parent) = p.parent() {
            let _ = fs::create_dir_all(parent);
        }
        fs::write(&p, body.as_bytes()).expect("write fixture");
    }

    fn plant_wave(root: &Path) {
        write_file(
            root,
            "envelope-wrap-disabled/aep-registration.gaplune",
            "ticket: AEP28-ENV-012\n",
        );
        write_file(
            root,
            "live-crossing-lab-off/aep-registration.gaplune",
            "ticket: AEP28-ENV-013\n",
        );
        write_file(
            root,
            "process-event-admit-walls/aep-registration.gaplune",
            "ticket: AEP28-ENV-014\n",
        );
        write_file(
            root,
            "live-crossing-reject-copy/aep-registration.gaplune",
            "ticket: AEP28-ENV-015\n",
        );
    }

    #[test]
    fn ticket_in_source_detects_registration() {
        must(ticket_in_source("ticket: AEP28-ENV-012\n", "AEP28-ENV-012") == true);
        must(ticket_in_source("ticket: AEP28-ENV-013\n", "AEP28-ENV-012") == false);
    }

    #[test]
    fn missing_tickets_deny_journals() {
        let root = temp_root("missing");
        write_file(&root, "only.md", "nothing\n");
        let v = run_gate(&root);
        must(v.allow == false);
        must(v.wave.missing.is_empty() == false);
        must(v.reason.contains("journals for that residual are not due") == true);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn full_wave_allows_journals() {
        let root = temp_root("full");
        plant_wave(&root);
        let v = run_gate(&root);
        must(v.allow == true);
        must(v.wave.missing.is_empty() == true);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn journal_before_wave_denied() {
        let root = temp_root("before");
        write_file(
            &root,
            "envelope-wrap-disabled/crate/src/lib.rs",
            "// AEP28-ENV-012\n",
        );
        let v = run_gate(&root);
        must(v.allow == false);
        must(v.reason.contains("journals denied") == true);
        let mut gate = residual_wrap_journal_gate::ResidualWrapJournalGate::new();
        gate.wave = root.to_string_lossy().into_owned();
        must(gate.process().is_err() == true);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn self_crate_does_not_count_as_landing() {
        let root = temp_root("self");
        write_file(
            &root,
            "envelope-wrap-journals/crate/src/lib.rs",
            "ticket: AEP28-ENV-012\nticket: AEP28-ENV-013\nticket: AEP28-ENV-014\nticket: AEP28-ENV-015\n",
        );
        let v = run_gate(&root);
        must(v.allow == false);
        must(v.wave.missing.len() == 4);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn modules_process_on_planted_wave() {
        let root = temp_root("mods");
        plant_wave(&root);
        let mut one = residual_wrap_ticket_landed::ResidualWrapTicketLanded::new();
        one.ticket = String::from("AEP28-ENV-012");
        one.source = String::from("ticket: AEP28-ENV-012\n");
        must(one.process().is_ok() == true);
        must(one.landed.as_str() == "true");
        let mut wave = residual_wrap_wave_landed::ResidualWrapWaveLanded::new();
        wave.tree = root.to_string_lossy().into_owned();
        must(wave.process().is_ok() == true);
        let mut gate = residual_wrap_journal_gate::ResidualWrapJournalGate::new();
        gate.wave = root.to_string_lossy().into_owned();
        must(gate.process().is_ok() == true);
        must(gate.allow.as_str() == "true");
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn live_components_tree_when_present() {
        let root = default_components_root();
        if root.is_dir() == false {
            return;
        }
        let v = run_gate(&root);
        if v.allow == false {
            let formatted = format_verdict(&v);
            must(formatted.contains("deny") == true);
            must(v.reason.contains("not due") == true);
            return;
        }
        must(v.allow == true);
        must(v.wave.missing.is_empty() == true);
    }
}
