//go:build linux || darwin || windows

package capabilities

import (
	"strings"
	"testing"
)

func TestGenerateConfig_LinuxLandlockOnly(t *testing.T) {
	result := &DetectResult{
		Platform:        "linux",
		SecurityMode:    "landlock-only",
		ProtectionScore: 80,
		Capabilities: map[string]any{
			"landlock":         true,
			"landlock_abi":     4,
			"landlock_network": true,
			"seccomp":          false,
			"fuse":             false,
		},
	}

	config, err := GenerateConfig(result)
	if err != nil {
		t.Fatalf("GenerateConfig() error: %v", err)
	}

	configStr := string(config)

	// Should have header comment
	if !strings.Contains(configStr, "Generated by: aep-caw detect config") {
		t.Error("missing header comment")
	}

	// Should have security section
	if !strings.Contains(configStr, "security:") {
		t.Error("missing security section")
	}

	// Should have landlock section
	if !strings.Contains(configStr, "landlock:") {
		t.Error("missing landlock section")
	}

	// Should have network section (ABI v4)
	if !strings.Contains(configStr, "network:") {
		t.Error("missing network section for ABI v4")
	}

	// Should have capabilities section
	if !strings.Contains(configStr, "capabilities:") {
		t.Error("missing capabilities section")
	}
}

func TestGenerateConfig_LinuxLandlockNoNetwork(t *testing.T) {
	result := &DetectResult{
		Platform:        "linux",
		SecurityMode:    "landlock-only",
		ProtectionScore: 75,
		Capabilities: map[string]any{
			"landlock":         true,
			"landlock_abi":     3,
			"landlock_network": false,
		},
	}

	config, err := GenerateConfig(result)
	if err != nil {
		t.Fatalf("GenerateConfig() error: %v", err)
	}

	configStr := string(config)

	// Should NOT have network section (ABI v3)
	if strings.Contains(configStr, "allow_connect_tcp") {
		t.Error("should not have network config for ABI v3")
	}

	// Should have comment about network
	if !strings.Contains(configStr, "kernel 6.7") {
		t.Error("missing comment about network requiring kernel 6.7")
	}
}

func TestGenerateConfig_LinuxFull(t *testing.T) {
	result := &DetectResult{
		Platform:        "linux",
		SecurityMode:    "full",
		ProtectionScore: 100,
		Capabilities: map[string]any{
			"seccomp": true,
			"ebpf":    true,
			"fuse":    true,
		},
	}

	config, err := GenerateConfig(result)
	if err != nil {
		t.Fatalf("GenerateConfig() error: %v", err)
	}

	configStr := string(config)

	// Should have mode: full
	if !strings.Contains(configStr, "mode: full") {
		t.Error("missing mode: full")
	}

	// Should NOT have landlock section (full mode uses seccomp)
	if strings.Contains(configStr, "landlock:") {
		t.Error("should not have landlock section in full mode")
	}
}
