//go:build linux || darwin || windows

package capabilities

import (
	"bytes"
	"fmt"
	"text/template"
)

const linuxLandlockConfigTemplate = `# Generated by: aep-caw detect config
# Platform: {{ .Platform }}
# Security mode: {{ .SecurityMode }}
# Protection score: ~{{ .ProtectionScore }}%
{{- if .NetworkNote }}
# Note: {{ .NetworkNote }}
{{- end }}

security:
  mode: {{ .SecurityMode }}
  strict: true
  warn_degraded: true

landlock:
  enabled: true
  allow_execute:
    - /usr/bin
    - /bin
    - /usr/local/bin
  allow_read:
    - /etc
    - /lib
    - /lib64
    - /usr/lib
  deny_paths:
    - /var/run/docker.sock
    - /run/containerd/containerd.sock
{{- if .HasNetwork }}
  network:
    allow_connect_tcp: true
    allow_bind_tcp: false
{{- else }}
  # network section omitted - requires kernel 6.7+ (Landlock ABI v4)
{{- end }}

capabilities:
  allow: []
`

const linuxFullConfigTemplate = `# Generated by: aep-caw detect config
# Platform: {{ .Platform }}
# Security mode: {{ .SecurityMode }}
# Protection score: {{ .ProtectionScore }}%

security:
  mode: full
  strict: true

# Full mode uses seccomp + eBPF + FUSE - no landlock section needed
# Configure sandbox settings in sandbox: section of main config

capabilities:
  allow: []
`

const linuxMinimalConfigTemplate = `# Generated by: aep-caw detect config
# Platform: {{ .Platform }}
# Security mode: {{ .SecurityMode }}
# Protection score: ~{{ .ProtectionScore }}%
# Warning: Limited security - only capability dropping available

security:
  mode: minimal
  strict: false
  warn_degraded: true

capabilities:
  allow: []
`

const darwinConfigTemplate = `# Generated by: aep-caw detect config
# Platform: {{ .Platform }}
# Security mode: {{ .SecurityMode }}
# Protection score: ~{{ .ProtectionScore }}%

security:
  mode: auto
  strict: false
  warn_degraded: true

sandbox:
  capabilities: []
  # Add 'network' capability if outbound access needed:
  # capabilities:
  #   - network
`

const windowsConfigTemplate = `# Generated by: aep-caw detect config
# Platform: {{ .Platform }}
# Security mode: {{ .SecurityMode }}
# Protection score: ~{{ .ProtectionScore }}%

security:
  mode: auto
  strict: false

sandbox:
  windows:
    use_app_container: {{ .HasAppContainer }}
    use_minifilter: {{ .HasMinifilter }}
    network_access: none
`

type configData struct {
	Platform        string
	SecurityMode    string
	ProtectionScore int
	HasNetwork      bool
	NetworkNote     string
	HasAppContainer bool
	HasMinifilter   bool
	HasWinFsp       bool
}

// GenerateConfig creates a configuration snippet from detection results.
func GenerateConfig(result *DetectResult) ([]byte, error) {
	data := configData{
		Platform:        result.Platform,
		SecurityMode:    result.SecurityMode,
		ProtectionScore: result.ProtectionScore,
	}

	var tmplStr string

	switch result.Platform {
	case "linux":
		tmplStr = selectLinuxTemplate(result, &data)
	case "darwin":
		tmplStr = darwinConfigTemplate
	case "windows":
		data.HasAppContainer, _ = result.Capabilities["app_container"].(bool)
		data.HasMinifilter, _ = result.Capabilities["minifilter"].(bool)
		data.HasWinFsp, _ = result.Capabilities["winfsp"].(bool)
		tmplStr = windowsConfigTemplate
	default:
		return nil, fmt.Errorf("unsupported platform: %s", result.Platform)
	}

	tmpl, err := template.New("config").Parse(tmplStr)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	return buf.Bytes(), nil
}

func selectLinuxTemplate(result *DetectResult, data *configData) string {
	switch result.SecurityMode {
	case "full":
		return linuxFullConfigTemplate
	case "minimal":
		return linuxMinimalConfigTemplate
	default:
		// landlock or landlock-only
		data.HasNetwork, _ = result.Capabilities["landlock_network"].(bool)
		if !data.HasNetwork {
			data.NetworkNote = "Network restrictions unavailable (requires kernel 6.7+)"
		}
		return linuxLandlockConfigTemplate
	}
}
