// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:46457904cdfc05cde59672f9e4882546ccd3815135b3464b1a962c5eff8ae626
// crate: aep-live-entry
// Generated by GAPLUNE Creation PAD ( zero-LLM )
// tokens: 0
// HVVCAS: live_entry domain:envelope type:service
// AEP28-ENV-025 Rust live entry. aep_envelope admit in-process. Fail-closed for empty action_path when lattice is loaded.
// AEP28-ENV-034: missing lattice, unreadable lattice and empty action_path on an empty lattice are Deny.
// AEP28-ENV-042: empty lattice closes dag.membership and gap.agent_may. Do not reopen AEP28-ENV-034.
// AEP28-ENV-066: unbound scene, channel, time and sequence close. dest_dock may bind from the opened frame docking port.
// AEP28-ENV-065: freeze_temporal_snapshot keeps bridge_ts_ms at seal so a 1000 ms hold still meets 50 ms drift.
// AEP28-ENV-043: partition satisfied_actions by agent or session so parent closure cannot leak across agents.
// AEP28-ENV-049: extra_walls is AdmitWall id. One Admit function. Drop conversion from a second admit_collect_all.
// AEP28-ENV-035: collect-all Deny for empty action_path runs before Apply. process_event must not mutate LiveEntry then return Event.
// AEP28-ENV-036: a template target_id is not a skip. Every opened frame runs collect-all Admit then Apply.
use aep_envelope::{
    action_is_satisfied, admit, admit_with_extra, apply_admit, closed_reasons, dest_dock_from_opened_frame, load_lattice_yaml, load_lattice_yaml_file, plan_apply,
    snapshot_from_nodes, AdmitWall, EnvelopeAction, Snapshot,
};
use serde_json::Value;
use thiserror::Error;
use std::collections::{BTreeSet, HashMap, HashSet};
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};
pub const TICKET: &str = "AEP28-ENV-025";
pub const TICKET_ENV031: &str = "AEP28-ENV-031";
pub const TICKET_ENV034: &str = "AEP28-ENV-034";
pub const TICKET_ENV035: &str = "AEP28-ENV-035";
pub const TICKET_ENV036: &str = "AEP28-ENV-036";
pub const TICKET_ENV037: &str = "AEP28-ENV-037";
pub const TICKET_ENV038: &str = "AEP28-ENV-038";
pub const TICKET_ENV049: &str = "AEP28-ENV-049";
pub const TICKET_ENV065: &str = "AEP28-ENV-065";
const TYPE_TO_PREFIX: &[(&str, &str)] = &[
    ("shell", "SH"), ("panel", "PN"), ("component", "CP"), ("navigation", "NV"),
    ("cell_zone", "CZ"), ("cell_node", "CN"), ("toolbar", "TB"), ("widget", "WD"),
    ("overlay", "OV"), ("modal", "MD"), ("dropdown", "DD"), ("tooltip", "TT"),
    ("form", "FM"), ("icon", "IC"),
];
pub fn z_band_for_prefix(prefix: &str) -> (i64, i64) {
    match prefix {
        "SH" => (0, 9), "PN" | "NV" => (10, 19), "CP" | "FM" | "IC" => (20, 29),
        "CZ" | "CN" => (30, 39), "TB" => (40, 49), "WD" => (50, 59), "OV" => (60, 69),
        "MD" | "DD" => (70, 79), "TT" => (80, 89), _ => (0, 99),
    }
}
fn s(a: &str, b: &str) -> String { let mut o = String::from(a); o.push_str(b); o }
#[derive(Debug, Clone, Error)]
pub enum LiveEntryError {
    #[error("{0}")]
    Envelope(String),
    #[error("Unknown element type: {0}")]
    UnknownElementType(String),
    #[error("Unregistered element: {0}")]
    UnregisteredElement(String),
    #[error("z-band violation: {0}")]
    ZBand(String),
    #[error("non-existent parent: {0}")]
    MissingParentField(String),
    #[error("Parent missing: {0}")]
    ParentMissing(String),
    #[error("z outside band for {0}")]
    ZOutsideBand(String),
}
fn pad5(n: u32) -> String {
    let raw = n.to_string();
    let mut o = String::new();
    let mut i = raw.len();
    while i < 5 { o.push('0'); i += 1; }
    o.push_str(&raw);
    o
}
#[derive(Debug, Clone)]
pub struct Element {
    pub id: String, pub kind: String, pub z: i64, pub parent: Option<String>,
    pub children: Vec<String>, pub visible: bool, pub layout: Value,
}
#[derive(Debug, Clone)]
pub struct Rejection { pub target_id: String, pub error: String, pub closed: Vec<AdmitWall> }
#[derive(Debug, Clone)]
pub enum ProcessOut { Event(Value), Reject(Rejection) }
pub struct LiveEntry {
    pub event: String, pub result: String, pub snapshot: Snapshot,
    pub live: HashMap<String, Element>, pub versions: HashMap<String, u64>,
    pub id_counters: HashMap<String, u32>, pub registry: HashSet<String>,
    pub styles: HashSet<String>, pub templates: HashSet<String>,
    pub forecast: HashMap<String, Value>, pub overwrite_timestamps: bool,
    pub jit_on_every_delta: bool, pub conflict_mode: String,
    clock_override_ms: Option<i64>,
    frozen_bridge_ts_ms: Option<i64>,
    pub extra_walls: Vec<AdmitWall>,
    pub opened_dest_dock: String,
}
impl Default for LiveEntry { fn default() -> Self { Self::new() } }
impl LiveEntry {
    pub fn new() -> Self {
        Self {
            event: String::new(), result: String::new(), snapshot: Snapshot::default(),
            live: HashMap::new(), versions: HashMap::new(), id_counters: HashMap::new(),
            registry: HashSet::new(), styles: HashSet::new(), templates: HashSet::new(),
            forecast: HashMap::new(), overwrite_timestamps: true, jit_on_every_delta: true,
            conflict_mode: String::from("last_write_wins"), clock_override_ms: None, frozen_bridge_ts_ms: None, extra_walls: Vec::new(), opened_dest_dock: String::new(),
        }
    }
    pub fn from_yaml(text: &str) -> Result<Self, LiveEntryError> {
        let nodes = match load_lattice_yaml(text) {
            Ok(v) => v,
            Err(e) => return Err(LiveEntryError::Envelope(e.to_string())),
        };
        let mut st = Self::new();
        let now = st.now_ms();
        st.snapshot = snapshot_from_nodes(nodes, BTreeSet::new(), now);
        Ok(st)
    }
    pub fn from_yaml_file(path: &Path) -> Result<Self, LiveEntryError> {
        let nodes = match load_lattice_yaml_file(path) {
            Ok(v) => v,
            Err(e) => return Err(LiveEntryError::Envelope(e.to_string())),
        };
        let mut st = Self::new();
        let now = st.now_ms();
        st.snapshot = snapshot_from_nodes(nodes, BTreeSet::new(), now);
        Ok(st)
    }
    pub fn bind_opened_frame(&mut self, scene: &str, dock: &str) {
        self.opened_dest_dock = String::from(dock);
        if dock.is_empty() == false {
            self.snapshot.allowed_docks.insert(String::from(dock));
        }
        if scene.is_empty() == false {
            self.snapshot.proven_scene_ids.insert(String::from(scene));
        }
    }
    pub fn set_clock_ms(&mut self, ms: i64) {
        self.clock_override_ms = Some(ms);
        if self.frozen_bridge_ts_ms.is_none() {
            self.snapshot.bridge_ts_ms = ms;
        }
    }
    pub fn freeze_temporal_snapshot(&mut self, bridge_ts_ms: i64) {
        self.frozen_bridge_ts_ms = Some(bridge_ts_ms);
        self.snapshot.bridge_ts_ms = bridge_ts_ms;
    }
    pub fn clear_temporal_freeze(&mut self) {
        self.frozen_bridge_ts_ms = None;
    }
    pub fn frozen_bridge_ts_ms(&self) -> Option<i64> {
        self.frozen_bridge_ts_ms
    }
    pub fn wall_bridge_ts_ms(&self) -> i64 {
        match self.frozen_bridge_ts_ms {
            Some(ms) => ms,
            None => self.now_ms(),
        }
    }
    pub fn now_ms(&self) -> i64 {
        if let Some(ms) = self.clock_override_ms { return ms; }
        match SystemTime::now().duration_since(UNIX_EPOCH) {
            Ok(d) => d.as_millis() as i64,
            Err(_) => 0,
        }
    }
    pub fn mint_element_id(&mut self, element_type: &str) -> Result<String, LiveEntryError> {
        let prefix = match TYPE_TO_PREFIX.iter().find(|(t, _)| *t == element_type).map(|(_, p)| *p) {
            Some(p) => p,
            None => return Err(LiveEntryError::UnknownElementType(element_type.to_string())),
        };
        let next = self.id_counters.get(prefix).copied().unwrap_or(0) + 1;
        self.id_counters.insert(prefix.to_string(), next);
        let mut id = String::from(prefix);
        id.push('-');
        id.push_str(&pad5(next));
        Ok(id)
    }
    pub fn process(&mut self) -> anyhow::Result<()> {
        let event: Value = match serde_json::from_str(&self.event) {
            Ok(v) => v,
            Err(e) => return Err(anyhow::Error::msg(e.to_string())),
        };
        match self.process_event(event) {
            ProcessOut::Event(v) => self.result = v.to_string(),
            ProcessOut::Reject(r) => {
                let mut m = serde_json::Map::new();
                m.insert(String::from("dynaep_type"), Value::String(String::from("DYNAEP_REJECTION")));
                m.insert(String::from("target_id"), Value::String(r.target_id));
                m.insert(String::from("error"), Value::String(r.error.clone()));
                let closed_vals: Vec<Value> = r.closed.iter().map(|w| {
                    let mut row = serde_json::Map::new();
                    row.insert(String::from("id"), Value::String(w.id.clone()));
                    row.insert(String::from("reason"), Value::String(w.reason.clone()));
                    Value::Object(row)
                }).collect();
                m.insert(String::from("closed"), Value::Array(closed_vals));
                self.result = Value::Object(m).to_string();
            }
        }
        Ok(())
    }
    pub fn process_event(&mut self, mut event: Value) -> ProcessOut {
        let pending_extra = std::mem::take(&mut self.extra_walls);
        let action_path = event.get("action_path").and_then(|v| v.as_str()).unwrap_or("").to_string();
        // AEP28-ENV-034: empty lattice is Deny for every opened frame, including empty action_path.
        if self.snapshot.lattice_nodes.is_empty() {
            return ProcessOut::Reject(Rejection {
                target_id: action_path,
                error: String::from("Lattice required but ActionLattice is not initialised"),
                closed: vec![
                    AdmitWall::close("dag.membership", "empty lattice closes membership"),
                    AdmitWall::close("gap.agent_may", "empty lattice closes agent_may"),
                ],
            });
        }
        // AEP28-ENV-035: collect-all Deny before Apply. Empty action_path must not mutate LiveEntry.
        if action_path.is_empty() {
            return ProcessOut::Reject(Rejection {
                target_id: action_path,
                error: String::from("Admit collect-all walls then Apply: missing action_path"),
                closed: vec![AdmitWall::close("action.path", "missing action_path")],
            });
        }
        // AEP28-ENV-036: a template target_id is not a skip. Fall through to collect-all Admit then Apply.
        // AEP28-ENV-025: collect-all AND for every opened frame. No empty-path skip when lattice is loaded.
        self.snapshot.bridge_ts_ms = match self.frozen_bridge_ts_ms {
            Some(ms) => ms,
            None => self.now_ms(),
        };
        let action = action_from_event(&event, &self.opened_dest_dock);
        let extra = pending_extra;
        let result = if extra.is_empty() {
            admit(&action, &self.snapshot)
        } else {
            admit_with_extra(&action, &self.snapshot, extra)
        };
        if result.allow == false {
            let reasons = closed_reasons(&result);
            let closed: Vec<AdmitWall> = result
                .closed_walls
                .iter()
                .map(|w| AdmitWall {
                    id: w.id.clone(),
                    closed: true,
                    reason: w.reason.clone(),
                })
                .collect();
            return ProcessOut::Reject(Rejection {
                target_id: action_path,
                error: s("Admit collect-all walls then Apply: ", &reasons.join("; ")),
                closed,
            });
        }
        if action_path.is_empty() == false {
            let plan = plan_apply(&result, &self.snapshot);
            apply_admit(&mut self.snapshot, &action, &plan);
        }
        let now = self.now_ms();
        let agent_ts = event.get("timestamp").and_then(|v| v.as_i64());
        if self.overwrite_timestamps {
            if let Some(obj) = event.as_object_mut() {
                obj.insert(String::from("timestamp"), Value::from(now));
            }
        }
        let ty = event.get("type").and_then(|v| v.as_str()).unwrap_or("");
        let dt = event.get("dynaep_type").and_then(|v| v.as_str()).unwrap_or("");
        if ty == "CUSTOM" && dt == "AEP_RUNTIME_COORDINATES" {
            if let (Some(tid), Some(coords)) = (
                event.get("target_id").and_then(|v| v.as_str()).map(|x| x.to_string()),
                event.get("coordinates").cloned(),
            ) {
                self.forecast.insert(tid, coords);
            }
        }
        let et = ty.to_string();
        let dyna = dt.to_string();
        let out = if et == "STATE_DELTA" {
            self.apply_state_delta(event)
        } else if et == "CUSTOM" && dyna.is_empty() == false {
            self.apply_dynaep_event(event)
        } else {
            ProcessOut::Event(event)
        };
        match out {
            ProcessOut::Event(mut ev) => {
                if let Some(obj) = ev.as_object_mut() {
                    let mut t = serde_json::Map::new();
                    t.insert(String::from("bridgeTimeMs"), Value::from(now));
                    if let Some(a) = agent_ts {
                        t.insert(String::from("agentTimeMs"), Value::from(a));
                    }
                    obj.insert(String::from("_temporal"), Value::Object(t));
                }
                ProcessOut::Event(ev)
            }
            other => other,
        }
    }
    fn apply_state_delta(&mut self, event: Value) -> ProcessOut {
        if self.jit_on_every_delta == false { return ProcessOut::Event(event); }
        let deltas = match event.get("delta").and_then(|v| v.as_array()).cloned() {
            Some(d) => d,
            None => return ProcessOut::Event(event),
        };
        for op in &deltas {
            let path = op.get("path").and_then(|v| v.as_str()).unwrap_or("");
            let parts: Vec<&str> = path.split('/').filter(|p| p.is_empty() == false).collect();
            if parts.len() < 2 { continue; }
            let layer = parts[0];
            let target_id = parts[1];
            let field = if parts.len() > 2 { Some(parts[2]) } else { None };
            let value = op.get("value").cloned().unwrap_or(Value::Null);
            if layer == "elements" {
                match self.validate_structure_delta(target_id, field, &value) {
                    Err(err) => {
                        return ProcessOut::Reject(Rejection { target_id: target_id.to_string(), error: err.to_string(), closed: Vec::new(), });
                    }
                    Ok(()) => {}
                }
                if self.conflict_mode == "optimistic_locking" {
                    if let Some(exp) = event.get("expected_version").and_then(|v| v.as_u64()) {
                        let cur = self.versions.get(target_id).copied().unwrap_or(0);
                        if exp != cur {
                            return ProcessOut::Reject(Rejection {
                                target_id: target_id.to_string(),
                                error: s("Optimistic lock conflict on ", target_id),
                             closed: Vec::new(), });
                        }
                    }
                }
            } else if layer == "registry" {
                if self.registry.contains(target_id) == false && target_id.starts_with("CN-") == false {
                    return ProcessOut::Reject(Rejection {
                        target_id: target_id.to_string(),
                        error: s("Cannot mutate behaviour: ", target_id),
                     closed: Vec::new(), });
                }
            }
        }
        for op in &deltas {
            let path = op.get("path").and_then(|v| v.as_str()).unwrap_or("");
            let parts: Vec<&str> = path.split('/').filter(|p| p.is_empty() == false).collect();
            if parts.len() >= 3 && parts[0] == "elements" {
                if let Some(el) = self.live.get_mut(parts[1]) {
                    if parts[2] == "z" {
                        if let Some(z) = op.get("value").and_then(|v| v.as_i64()) { el.z = z; }
                    }
                    if parts[2] == "parent" {
                        if let Some(p) = op.get("value").and_then(|v| v.as_str()) { el.parent = Some(p.to_string()); }
                    }
                    if parts[2] == "visible" {
                        if let Some(v) = op.get("value").and_then(|v| v.as_bool()) { el.visible = v; }
                    }
                    *self.versions.entry(parts[1].to_string()).or_insert(0) += 1;
                }
            }
        }
        ProcessOut::Event(event)
    }
    fn validate_structure_delta(&self, target_id: &str, field: Option<&str>, value: &Value) -> Result<(), LiveEntryError> {
        if self.live.contains_key(target_id) == false && target_id.starts_with("CN-") == false {
            return Err(LiveEntryError::UnregisteredElement(target_id.to_string()));
        }
        if field == Some("z") {
            if let Some(z) = value.as_i64() {
                let prefix = if target_id.len() >= 2 { &target_id[..2] } else { "" };
                let (lo, hi) = z_band_for_prefix(prefix);
                if z < lo || z > hi { return Err(LiveEntryError::ZBand(target_id.to_string())); }
            }
        }
        if field == Some("parent") {
            if let Some(p) = value.as_str() {
                if self.live.contains_key(p) == false {
                    return Err(LiveEntryError::MissingParentField(p.to_string()));
                }
            }
        }
        Ok(())
    }
    fn apply_dynaep_event(&mut self, event: Value) -> ProcessOut {
        let dt = event.get("dynaep_type").and_then(|v| v.as_str()).unwrap_or("");
        match dt {
            "AEP_MUTATE_STRUCTURE" => self.mutate_structure(event),
            "AEP_MUTATE_BEHAVIOUR" => self.mutate_behaviour(event),
            "AEP_MUTATE_SKIN" => self.mutate_skin(event),
            "AEP_QUERY" => ProcessOut::Event(self.handle_query(&event)),
            _ => ProcessOut::Event(event),
        }
    }
    fn mutate_structure(&mut self, event: Value) -> ProcessOut {
        let tid = event.get("target_id").and_then(|v| v.as_str()).unwrap_or("").to_string();
        if self.live.contains_key(&tid) == false && tid.starts_with("CN-") == false {
            return ProcessOut::Reject(Rejection { target_id: tid.clone(), error: s("Unknown element: ", &tid), closed: Vec::new(), });
        }
        if let Some(parent) = event.pointer("/mutation/parent").and_then(|v| v.as_str()) {
            if self.live.contains_key(parent) == false {
                return ProcessOut::Reject(Rejection { target_id: tid.clone(), error: s("Cannot move; parent missing: ", parent), closed: Vec::new(), });
            }
            let old = self.live.get(&tid).and_then(|e| e.parent.clone());
            if let Some(op) = old {
                if let Some(p) = self.live.get_mut(&op) { p.children.retain(|c| c != &tid); }
            }
            if let Some(p) = self.live.get_mut(parent) {
                if p.children.iter().any(|c| c == &tid) == false { p.children.push(tid.clone()); }
            }
            if let Some(el) = self.live.get_mut(&tid) { el.parent = Some(parent.to_string()); }
        }
        *self.versions.entry(tid).or_insert(0) += 1;
        ProcessOut::Event(event)
    }
    fn mutate_behaviour(&self, event: Value) -> ProcessOut {
        let tid = event.get("target_id").and_then(|v| v.as_str()).unwrap_or("");
        if self.registry.contains(tid) == false && tid.starts_with("CN-") == false {
            return ProcessOut::Reject(Rejection { target_id: tid.into(), error: s("Cannot mutate behaviour: ", tid), closed: Vec::new(), });
        }
        ProcessOut::Event(event)
    }
    fn mutate_skin(&self, event: Value) -> ProcessOut {
        let tid = event.get("target_id").and_then(|v| v.as_str()).unwrap_or("");
        if self.styles.is_empty() == false && self.styles.contains(tid) == false {
            return ProcessOut::Reject(Rejection { target_id: tid.into(), error: s("Cannot mutate skin: ", tid), closed: Vec::new(), });
        }
        ProcessOut::Event(event)
    }
    fn handle_query(&self, event: &Value) -> Value {
        let q = event.get("query").and_then(|v| v.as_str()).unwrap_or("");
        let tid = event.get("target_id").and_then(|v| v.as_str()).unwrap_or("");
        let el = self.live.get(tid);
        let result = match q {
            "children_of" => Value::from(el.map(|e| e.children.clone()).unwrap_or_default()),
            "parent_of" => match el.and_then(|e| e.parent.clone()) {
                Some(p) => Value::String(p),
                None => Value::Null,
            },
            "z_band_of" => {
                let p = if tid.len() >= 2 { &tid[..2] } else { "" };
                let b = z_band_for_prefix(p);
                let mut arr = Vec::new();
                arr.push(Value::from(b.0));
                arr.push(Value::from(b.1));
                Value::Array(arr)
            }
            "next_available_id" => {
                let n = self.id_counters.get(tid).copied().unwrap_or(0) + 1;
                let mut id = String::from(tid);
                id.push('-');
                id.push_str(&pad5(n));
                Value::String(id)
            }
            _ => Value::Null,
        };
        let mut m = serde_json::Map::new();
        m.insert(String::from("type"), Value::String(String::from("CUSTOM")));
        m.insert(String::from("dynaep_type"), Value::String(String::from("AEP_QUERY_RESULT")));
        m.insert(String::from("target_id"), Value::String(tid.to_string()));
        m.insert(String::from("result"), result);
        Value::Object(m)
    }
    pub fn add_element(&mut self, kind: &str, parent: &str, z: i64) -> Result<String, LiveEntryError> {
        if TYPE_TO_PREFIX.iter().all(|(t, _)| *t != kind) { return Err(LiveEntryError::UnknownElementType(kind.to_string())); }
        if self.live.contains_key(parent) == false { return Err(LiveEntryError::ParentMissing(parent.to_string())); }
        let prefix = match TYPE_TO_PREFIX.iter().find(|(t, _)| *t == kind).map(|(_, p)| *p) {
            Some(p) => p,
            None => return Err(LiveEntryError::UnknownElementType(kind.to_string())),
        };
        let (lo, hi) = z_band_for_prefix(prefix);
        if z < lo || z > hi { return Err(LiveEntryError::ZOutsideBand(kind.to_string())); }
        let id = match self.mint_element_id(kind) {
            Ok(v) => v,
            Err(e) => return Err(e),
        };
        self.live.insert(id.clone(), Element {
            id: id.clone(), kind: kind.into(), z, parent: Some(parent.into()),
            children: Vec::new(), visible: true, layout: Value::Object(serde_json::Map::new()),
        });
        if let Some(p) = self.live.get_mut(parent) { p.children.push(id.clone()); }
        Ok(id)
    }
    pub fn seed_shell(&mut self) {
        self.live.insert(String::from("SH-00001"), Element {
            id: String::from("SH-00001"), kind: String::from("shell"), z: 0, parent: None,
            children: Vec::new(), visible: true, layout: Value::Object(serde_json::Map::new()),
        });
        self.id_counters.insert(String::from("SH"), 1);
        self.registry.insert(String::from("SH-00001"));
    }
}
fn action_from_event(event: &Value, opened_dest_dock: &str) -> EnvelopeAction {
    let raw_dock = event.get("dest_dock").and_then(|v| v.as_str()).unwrap_or("");
    EnvelopeAction {
        action_path: event.get("action_path").and_then(|v| v.as_str()).unwrap_or("").to_string(),
        agent_id: event.get("agent_id").and_then(|v| v.as_str()).unwrap_or("").to_string(),
        payload: event.get("payload").cloned().unwrap_or(Value::Object(serde_json::Map::new())),
        tool: event.get("tool").and_then(|v| v.as_str()).unwrap_or("").to_string(),
        dest_dock: dest_dock_from_opened_frame(raw_dock, opened_dest_dock),
        scene_id: event.get("target_id").and_then(|v| v.as_str()).unwrap_or("").to_string(),
        agent_ts_ms: event.get("timestamp").and_then(|v| v.as_i64()).unwrap_or(0),
        sequence_number: event.get("_sequenceNumber").and_then(|v| v.as_i64()).unwrap_or(0),
        anomaly_score: event.get("anomaly_score").and_then(|v| v.as_f64()).unwrap_or(0.0),
    }
}
pub fn journal_product_landed(src: &str) -> bool {
    src.contains("admit(&action, &self.snapshot)") && src.contains("load_lattice_yaml")
}
pub fn product_source_has_no_seq_deniers(src: &str) -> bool {
    let compact: String = src.chars().filter(|c| c.is_whitespace() == false).collect();
    if compact.contains("TemporalValidator") { return false; }
    if compact.contains("UnifiedRegoEvaluator") { return false; }
    if compact.contains("UnifiedScanner") { return false; }
    if compact.contains("CausalOrderingEngine") { return false; }
    true
}
pub mod live_entry { pub use super::LiveEntry; }
#[cfg(test)]
mod tests {
    use super::*;
    fn must(cond: bool) { if cond == false { std::process::abort(); } }
    fn yaml() -> &'static str {
        "actions:\n  root:ping:\n    category: system_event\n    parents: []\n    children: []\n    agent_may: [\"*\"]\n  action:write:\n    category: agent_action\n    parents: [\"root:ping\"]\n    children: []\n    agent_may: [\"agent-a\"]\n"
    }
    fn bind_allow(le: &mut LiveEntry, scene: &str) {
        le.bind_opened_frame(scene, "inference_engine");
    }
    fn ev_allow() -> Value {
        serde_json::from_str("{\"type\":\"CUSTOM\",\"action_path\":\"action:write\",\"agent_id\":\"agent-a\",\"payload\":{\"ok\":true},\"timestamp\":1000000,\"target_id\":\"scene-a\",\"dest_dock\":\"inference_engine\",\"_sequenceNumber\":1}").unwrap()
    }
    #[test]
    fn yaml_load_and_admit_in_process() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        bind_allow(&mut le, "scene-a");
        le.snapshot.satisfied_actions.insert(String::from("root:ping"));
        match le.process_event(ev_allow()) {
            ProcessOut::Event(_) => {}
            ProcessOut::Reject(_) => std::process::abort(),
        }
        must(action_is_satisfied(&le.snapshot, "action:write", "agent-a"));
    }
    #[test]
    fn admit_deny_unknown_path() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        let ev = serde_json::from_str("{\"type\":\"CUSTOM\",\"action_path\":\"bogus:path\",\"payload\":{\"ok\":true},\"timestamp\":1000000}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("Admit collect-all walls then Apply")),
            ProcessOut::Event(_) => std::process::abort(),
        }
    }
    #[test]
    fn ping_meets_admit_collect_all() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        let ev = serde_json::from_str("{\"type\":\"PING\"}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("Admit collect-all walls then Apply")),
            ProcessOut::Event(_) => std::process::abort(),
        }
    }
    #[test]
    fn mint_ids() {
        let mut le = LiveEntry::new();
        let a = le.mint_element_id("component").expect("mint");
        must(a.as_str() == "CP-00001");
        let b = le.mint_element_id("component").expect("mint");
        must(b.as_str() == "CP-00002");
    }
    fn ev_state_delta(z: i64) -> Value {
        let mut m = serde_json::Map::new();
        m.insert(String::from("type"), Value::String(String::from("STATE_DELTA")));
        m.insert(String::from("action_path"), Value::String(String::from("root:ping")));
        m.insert(String::from("agent_id"), Value::String(String::from("agent-a")));
        m.insert(String::from("payload"), Value::Object({
            let mut p = serde_json::Map::new();
            p.insert(String::from("ok"), Value::from(true));
            p
        }));
        m.insert(String::from("timestamp"), Value::from(1000000));
        m.insert(String::from("target_id"), Value::String(String::from("scene-a")));
        m.insert(String::from("dest_dock"), Value::String(String::from("inference_engine")));
        m.insert(String::from("_sequenceNumber"), Value::from(1));
        let mut op = serde_json::Map::new();
        op.insert(String::from("op"), Value::String(String::from("replace")));
        op.insert(String::from("path"), Value::String(String::from("/elements/CP-00001/z")));
        op.insert(String::from("value"), Value::from(z));
        m.insert(String::from("delta"), Value::Array(vec![Value::Object(op)]));
        Value::Object(m)
    }
    fn seed_component(le: &mut LiveEntry) {
        le.seed_shell();
        le.live.insert(String::from("CP-00001"), Element {
            id: String::from("CP-00001"), kind: String::from("component"), z: 20,
            parent: Some(String::from("SH-00001")), children: Vec::new(), visible: true,
            layout: Value::Object(serde_json::Map::new()),
        });
    }
    #[test]
    fn structural_apply_z() {
        let mut le = LiveEntry::new();
        seed_component(&mut le);
        let ev = serde_json::from_str("{\"type\":\"STATE_DELTA\",\"delta\":[{\"op\":\"replace\",\"path\":\"/elements/CP-00001/z\",\"value\":21}]}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("Lattice required")),
            ProcessOut::Event(_) => std::process::abort(),
        }
        must(le.live.get("CP-00001").unwrap().z == 20);
    }
    #[test]
    fn empty_action_path_empty_lattice_is_deny() {
        let mut le = LiveEntry::new();
        let ev = serde_json::from_str("{\"type\":\"PING\"}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("Lattice required")),
            ProcessOut::Event(_) => std::process::abort(),
        }
    }

    #[test]
    fn non_empty_action_path_on_empty_lattice_is_deny() {
        let mut le = LiveEntry::new();
        let ev = serde_json::from_str("{\"type\":\"PING\",\"action_path\":\"root:ping\"}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("Lattice required")),
            ProcessOut::Event(_) => std::process::abort(),
        }
    }
    #[test]
    fn unreadable_yaml_is_deny() {
        match LiveEntry::from_yaml("{{ not a lattice") {
            Err(_) => {}
            Ok(_) => std::process::abort(),
        }
    }
    #[test]
    fn z_band_reject() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        bind_allow(&mut le, "scene-a");
        seed_component(&mut le);
        match le.process_event(ev_state_delta(90)) {
            ProcessOut::Reject(r) => must(r.error.contains("z-band")),
            ProcessOut::Event(_) => std::process::abort(),
        }
    }
    #[test]
    fn structural_apply_z_with_lattice() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        bind_allow(&mut le, "scene-a");
        seed_component(&mut le);
        match le.process_event(ev_state_delta(21)) {
            ProcessOut::Event(_) => {}
            ProcessOut::Reject(_) => std::process::abort(),
        }
        must(le.live.get("CP-00001").unwrap().z == 21);
    }
    #[test]
    fn forecast_ingest() {
        let mut le = LiveEntry::new();
        let ev = serde_json::from_str("{\"type\":\"CUSTOM\",\"dynaep_type\":\"AEP_RUNTIME_COORDINATES\",\"target_id\":\"CP-00001\",\"coordinates\":{\"x\":1,\"y\":2}}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("Lattice required")),
            ProcessOut::Event(_) => std::process::abort(),
        }
        must(le.forecast.contains_key("CP-00001") == false);
    }
    #[test]
    fn forecast_ingest_with_lattice() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        bind_allow(&mut le, "CP-00001");
        let ev = serde_json::from_str("{\"type\":\"CUSTOM\",\"dynaep_type\":\"AEP_RUNTIME_COORDINATES\",\"action_path\":\"root:ping\",\"agent_id\":\"agent-a\",\"payload\":{\"ok\":true},\"timestamp\":1000000,\"target_id\":\"CP-00001\",\"dest_dock\":\"inference_engine\",\"_sequenceNumber\":1,\"coordinates\":{\"x\":1,\"y\":2}}").unwrap();
        let _ = le.process_event(ev);
        must(le.forecast.contains_key("CP-00001"));
    }
    #[test]
    fn clock_stamp() {
        let mut le = LiveEntry::new();
        le.set_clock_ms(42);
        let ev = serde_json::from_str("{\"type\":\"TOOL_CALL_START\",\"timestamp\":1}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("Lattice required")),
            ProcessOut::Event(_) => std::process::abort(),
        }
    }
    #[test]
    fn clock_stamp_with_lattice() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(42);
        bind_allow(&mut le, "scene-a");
        let ev = serde_json::from_str("{\"type\":\"TOOL_CALL_START\",\"action_path\":\"root:ping\",\"agent_id\":\"agent-a\",\"payload\":{\"ok\":true},\"timestamp\":42,\"target_id\":\"scene-a\",\"dest_dock\":\"inference_engine\",\"_sequenceNumber\":1}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Event(v) => must(v.get("timestamp").and_then(|x| x.as_i64()) == Some(42)),
            ProcessOut::Reject(_) => std::process::abort(),
        }
    }
    #[test]
    fn env034_ticket() {
        must(TICKET_ENV034 == "AEP28-ENV-034");
    }
    #[test]
    fn env035_ticket() {
        must(TICKET_ENV035 == "AEP28-ENV-035");
    }
    #[test]
    fn env036_ticket() {
        must(TICKET_ENV036 == "AEP28-ENV-036");
    }
    #[test]
    fn env037_ticket() {
        must(TICKET_ENV037 == "AEP28-ENV-037");
    }
    #[test]
    fn env038_ticket() {
        must(TICKET_ENV038 == "AEP28-ENV-038");
    }
    #[test]
    fn env049_ticket() {
        must(TICKET_ENV049 == "AEP28-ENV-049");
        let src = include_str!("lib.rs");
        must(src.contains("pub extra_walls: Vec<AdmitWall>"));
        let conv = ["wall_verdicts_from_admit", "_walls"].concat();
        must(src.contains(&conv) == false);
    }
    #[test]
    fn extra_closed_wall_denies_and_clears() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        bind_allow(&mut le, "scene-a");
        le.extra_walls.push(AdmitWall::close("dock.capsule", "capsule missing"));
        let ev = serde_json::json!({
            "type": "PING",
            "action_path": "root:ping",
            "payload": { "ok": true },
            "timestamp": 1000000,
            "target_id": "scene-a",
            "dest_dock": "inference_engine",
            "_sequenceNumber": 1
        });
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("capsule missing")),
            ProcessOut::Event(_) => std::process::abort(),
        }
        must(le.extra_walls.is_empty());
    }
    fn ev_template_unknown() -> Value {
        serde_json::from_str("{\"type\":\"CUSTOM\",\"action_path\":\"bogus:path\",\"target_id\":\"tpl-a\",\"payload\":{\"ok\":true},\"timestamp\":1000000,\"dest_dock\":\"inference_engine\",\"_sequenceNumber\":1}").unwrap()
    }
    fn ev_template_allow() -> Value {
        serde_json::from_str("{\"type\":\"CUSTOM\",\"action_path\":\"action:write\",\"agent_id\":\"agent-a\",\"target_id\":\"tpl-a\",\"payload\":{\"ok\":true},\"timestamp\":1000000,\"dest_dock\":\"inference_engine\",\"_sequenceNumber\":1}").unwrap()
    }
    #[test]
    fn template_target_unknown_path_is_deny() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        le.templates.insert(String::from("tpl-a"));
        match le.process_event(ev_template_unknown()) {
            ProcessOut::Reject(r) => must(r.error.contains("Admit collect-all walls then Apply")),
            ProcessOut::Event(_) => std::process::abort(),
        }
    }
    #[test]
    fn template_target_known_path_admits_and_applies() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        le.snapshot.satisfied_actions.insert(String::from("root:ping"));
        le.templates.insert(String::from("tpl-a"));
        bind_allow(&mut le, "tpl-a");
        match le.process_event(ev_template_allow()) {
            ProcessOut::Event(v) => {
                must(v.pointer("/_temporal/fast_exit").and_then(|x| x.as_bool()) != Some(true));
            }
            ProcessOut::Reject(_) => std::process::abort(),
        }
        must(action_is_satisfied(&le.snapshot, "action:write", "agent-a"));
    }
    #[test]
    fn template_target_empty_action_path_is_deny_before_apply() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        seed_component(&mut le);
        le.templates.insert(String::from("tpl-a"));
        let before_ts = le.snapshot.bridge_ts_ms;
        let ev = serde_json::from_str("{\"type\":\"CUSTOM\",\"target_id\":\"tpl-a\",\"dynaep_type\":\"AEP_RUNTIME_COORDINATES\",\"coordinates\":{\"x\":1,\"y\":2}}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("missing action_path")),
            ProcessOut::Event(_) => std::process::abort(),
        }
        must(le.forecast.contains_key("tpl-a") == false);
        must(le.snapshot.bridge_ts_ms == before_ts);
    }
    #[test]
    fn template_target_state_delta_still_applies_after_admit() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        seed_component(&mut le);
        le.templates.insert(String::from("CP-00001"));
        bind_allow(&mut le, "CP-00001");
        let mut ev = ev_state_delta(21);
        if let Some(obj) = ev.as_object_mut() {
            obj.insert(String::from("target_id"), Value::String(String::from("CP-00001")));
        }
        match le.process_event(ev) {
            ProcessOut::Event(_) => {}
            ProcessOut::Reject(_) => std::process::abort(),
        }
        must(le.live.get("CP-00001").unwrap().z == 21);
    }
    #[test]
    fn process_event_does_not_event_return_on_template_set() {
        let src = include_str!("lib.rs");
        let start = match src.find("pub fn process_event") {
            Some(v) => v,
            None => std::process::abort(),
        };
        let admit = match src[start..].find("admit(&action, &self.snapshot)") {
            Some(v) => v,
            None => std::process::abort(),
        };
        let slice = &src[start..start + admit];
        must(slice.contains("fast_exit") == false);
        let compact: String = slice.chars().filter(|c| c.is_whitespace() == false).collect();
        must(compact.contains("templates.contains") == false);
        must(compact.contains("returnProcessOut::Event") == false);
    }
    fn ev_state_delta_no_path(z: i64) -> Value {
        let mut m = serde_json::Map::new();
        m.insert(String::from("type"), Value::String(String::from("STATE_DELTA")));
        m.insert(String::from("timestamp"), Value::from(1000000));
        let mut op = serde_json::Map::new();
        op.insert(String::from("op"), Value::String(String::from("replace")));
        op.insert(String::from("path"), Value::String(String::from("/elements/CP-00001/z")));
        op.insert(String::from("value"), Value::from(z));
        m.insert(String::from("delta"), Value::Array(vec![Value::Object(op)]));
        Value::Object(m)
    }
    #[test]
    fn state_delta_without_action_path_does_not_change_z() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        seed_component(&mut le);
        let before_ts = le.snapshot.bridge_ts_ms;
        match le.process_event(ev_state_delta_no_path(21)) {
            ProcessOut::Reject(r) => must(r.error.contains("missing action_path")),
            ProcessOut::Event(_) => std::process::abort(),
        }
        must(le.live.get("CP-00001").unwrap().z == 20);
        must(le.snapshot.bridge_ts_ms == before_ts);
    }
    #[test]
    fn forecast_ingest_without_action_path_does_not_write_coordinates() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        let before_ts = le.snapshot.bridge_ts_ms;
        let ev = serde_json::from_str("{\"type\":\"CUSTOM\",\"dynaep_type\":\"AEP_RUNTIME_COORDINATES\",\"target_id\":\"CP-00001\",\"coordinates\":{\"x\":1,\"y\":2}}").unwrap();
        match le.process_event(ev) {
            ProcessOut::Reject(r) => must(r.error.contains("missing action_path")),
            ProcessOut::Event(_) => std::process::abort(),
        }
        must(le.forecast.contains_key("CP-00001") == false);
        must(le.snapshot.bridge_ts_ms == before_ts);
    }
    #[test]
    fn empty_action_path_deny_is_before_apply() {
        let src = include_str!("lib.rs");
        let start = match src.find("pub fn process_event") {
            Some(v) => v,
            None => std::process::abort(),
        };
        let body = &src[start..];
        let empty = match body.find("if action_path.is_empty() {") {
            Some(v) => v,
            None => std::process::abort(),
        };
        let clock = match body.find("self.snapshot.bridge_ts_ms") {
            Some(v) => v,
            None => std::process::abort(),
        };
        let delta = match body.find("self.apply_state_delta") {
            Some(v) => v,
            None => std::process::abort(),
        };
        let forecast = match body.find("self.forecast.insert") {
            Some(v) => v,
            None => std::process::abort(),
        };
        must(empty < clock);
        must(empty < delta);
        must(empty < forecast);
    }
    #[test]
    fn add_element_mints() {
        let mut le = LiveEntry::new();
        le.seed_shell();
        let id = le.add_element("component", "SH-00001", 21).expect("add");
        must(id.as_str() == "CP-00001");
        must(le.live.contains_key("CP-00001"));
        must(le.live.get("SH-00001").unwrap().children.contains(&id));
    }
    #[test]
    fn source_has_in_process_admit() {
        let src = TICKET;
        must(src == "AEP28-ENV-025");
        must(product_source_has_no_seq_deniers("admit apply_admit load_lattice_yaml mint_element_id"));
        must(journal_product_landed("admit(&action, &self.snapshot) load_lattice_yaml"));
    }
    #[test]
    fn env031_one_live_entry_language() {
        must(TICKET_ENV031 == "AEP28-ENV-031");
        must(journal_product_landed("admit(&action, &self.snapshot) load_lattice_yaml"));
        must(product_source_has_no_seq_deniers("admit apply_admit load_lattice_yaml mint_element_id"));
    }
    #[test]
    fn hvvc_as_process_json() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        bind_allow(&mut le, "scene-a");
        le.snapshot.satisfied_actions.insert(String::from("root:ping"));
        le.event = ev_allow().to_string();
        must(le.process().is_ok());
        must(le.result.contains("DYNAEP_REJECTION") == false);
    }
    #[test]
    fn freeze_keeps_bridge_after_clock_advance() {
        let mut le = LiveEntry::from_yaml(yaml()).expect("yaml");
        le.set_clock_ms(1000000);
        le.freeze_temporal_snapshot(1000000);
        bind_allow(&mut le, "scene-a");
        le.snapshot.satisfied_actions.insert(String::from("root:ping"));
        le.set_clock_ms(1001000);
        match le.process_event(ev_allow()) {
            ProcessOut::Event(_) => {}
            ProcessOut::Reject(_) => std::process::abort(),
        }
        must(le.snapshot.bridge_ts_ms == 1000000);
        must(le.wall_bridge_ts_ms() == 1000000);
        must(le.frozen_bridge_ts_ms() == Some(1000000));
        must(TICKET_ENV065 == "AEP28-ENV-065");
    }
}
