// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:c03753d1128c1fc7386ce1577c4fbabbe1ac294bfcf1188615bbf6f1de69dbce
// crate: aep-envelope-journals
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-011: Journals after product tickets land.

use std::fs;
use std::path::{Path, PathBuf};

pub const PRODUCT_TICKETS: &[&str] = &[
    "AEP28-ENV-001",
    "AEP28-ENV-002",
    "AEP28-ENV-003",
    "AEP28-ENV-004",
    "AEP28-ENV-005",
    "AEP28-ENV-006",
    "AEP28-ENV-007",
    "AEP28-ENV-008",
    "AEP28-ENV-009",
    "AEP28-ENV-010",
];

pub const ADMIT_CRATE_REL: &str = "admit/crate";
pub const FILTER_REL: &str = "dynAEP/bridge/hyperlattice/HyperlatticeFilter.ts";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TicketLanded {
    pub ticket: String,
    pub landed: bool,
    pub evidence: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WaveReport {
    pub landed: Vec<TicketLanded>,
    pub missing: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct JournalVerdict {
    pub allow: bool,
    pub reason: String,
    pub wave: WaveReport,
}

pub fn ticket_in_source(source: &str, ticket: &str) -> bool {
    source.contains(ticket)
}

fn extract_filter_crossing(src: &str) -> String {
    let start = match src.find("async filterCrossing") {
        Some(v) => v,
        None => return String::new(),
    };
    src[start..].to_string()
}

pub fn env007_live_path_landed(filter_source: &str) -> bool {
    let body = extract_filter_crossing(filter_source);
    if body.is_empty() {
        return ticket_in_source(filter_source, "AEP28-ENV-007");
    }
    if body.contains("admitCollectAll") == false {
        return false;
    }
    if body.contains("if (labLatticeFilterEnabled()) { return") {
        return false;
    }
    if body.contains("if (labLatticeFilterEnabled()) return") {
        return false;
    }
    true
}

pub fn default_components_root() -> PathBuf {
    let dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| String::from("."));
    PathBuf::from(dir).join("../..")
}

pub fn default_admit_crate() -> PathBuf {
    default_components_root().join(ADMIT_CRATE_REL)
}

pub fn default_filter_ts() -> PathBuf {
    default_components_root().join(FILTER_REL)
}

fn is_scan_name(name: &str) -> bool {
    name.ends_with(".rs")
        || name.ends_with(".gaplune")
        || name.ends_with(".ts")
        || name.ends_with(".mjs")
        || name.ends_with(".md")
        || name.ends_with(".sh")
}

fn skip_dir_name(name: &str) -> bool {
    name == ".git" || name == "target" || name == "node_modules"
}

fn collect_sources(root: &Path, out: &mut Vec<(String, String)>) {
    let mut stack = Vec::new();
    stack.push(root.to_path_buf());
    while let Some(dir) = stack.pop() {
        let rd = match fs::read_dir(&dir) {
            Ok(v) => v,
            Err(_) => continue,
        };
        for ent in rd.flatten() {
            let path = ent.path();
            let name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("")
                .to_string();
            if skip_dir_name(&name) {
                continue;
            }
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if is_scan_name(&name) == false {
                continue;
            }
            if let Ok(src) = fs::read_to_string(&path) {
                out.push((path.to_string_lossy().into_owned(), src));
            }
        }
    }
}

pub fn evidence_for_ticket(files: &[(String, String)], ticket: &str) -> Option<String> {
    for (path, src) in files {
        if path.contains("envelope-journals") {
            continue;
        }
        if ticket_in_source(src, ticket) {
            return Some(path.clone());
        }
    }
    None
}

pub fn scan_wave(root: &Path) -> WaveReport {
    let mut files = Vec::new();
    collect_sources(root, &mut files);
    let filter_src = files
        .iter()
        .find(|(p, _)| p.ends_with("HyperlatticeFilter.ts"))
        .map(|(_, s)| s.as_str())
        .unwrap_or("");
    let mut landed = Vec::new();
    let mut missing = Vec::new();
    for ticket in PRODUCT_TICKETS {
        if let Some(ev) = evidence_for_ticket(&files, ticket) {
            landed.push(TicketLanded {
                ticket: (*ticket).to_string(),
                landed: true,
                evidence: ev,
            });
            continue;
        }
        if *ticket == "AEP28-ENV-007" && env007_live_path_landed(filter_src) {
            landed.push(TicketLanded {
                ticket: (*ticket).to_string(),
                landed: true,
                evidence: String::from("live filterCrossing always Admit collect-all"),
            });
            continue;
        }
        missing.push((*ticket).to_string());
        landed.push(TicketLanded {
            ticket: (*ticket).to_string(),
            landed: false,
            evidence: String::new(),
        });
    }
    WaveReport { landed, missing }
}

pub fn journal_allow(wave: &WaveReport) -> JournalVerdict {
    if wave.missing.is_empty() {
        JournalVerdict {
            allow: true,
            reason: String::from("product wave landed; journals allowed on Admit crate"),
            wave: wave.clone(),
        }
    } else {
        let mut reason = String::from("journals denied until product tickets land: ");
        reason.push_str(&wave.missing.join(","));
        JournalVerdict {
            allow: false,
            reason,
            wave: wave.clone(),
        }
    }
}

pub fn run_gate(root: &Path) -> JournalVerdict {
    let wave = scan_wave(root);
    journal_allow(&wave)
}

pub fn format_verdict(v: &JournalVerdict) -> String {
    let mut out = String::new();
    if v.allow {
        out.push_str("allow\n");
    } else {
        out.push_str("deny\n");
    }
    out.push_str(&v.reason);
    out.push('\n');
    for t in &v.wave.landed {
        out.push_str(&t.ticket);
        if t.landed {
            out.push_str(" landed ");
            out.push_str(&t.evidence);
        } else {
            out.push_str(" missing");
        }
        out.push('\n');
    }
    out
}

fn err_msg(msg: String) -> anyhow::Error {
    anyhow::Error::msg(msg)
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: product_ticket_landed domain:admit type:service
pub mod product_ticket_landed {
    use super::{err_msg, ticket_in_source};

    pub struct ProductTicketLanded {
        pub source: String,
        pub ticket: String,
        pub landed: String,
    }

    impl ProductTicketLanded {
        pub fn new() -> Self {
            Self {
                source: String::new(),
                ticket: String::from("AEP28-ENV-001"),
                landed: String::new(),
            }
        }

        /// Prove one envelope product ticket landed from registration or crate source
        pub fn process(&mut self) -> anyhow::Result<()> {
            if ticket_in_source(&self.source, &self.ticket) {
                self.landed = String::from("true");
                Ok(())
            } else {
                self.landed = String::from("false");
                let mut msg = String::from("product ticket not landed: ");
                msg.push_str(&self.ticket);
                Err(err_msg(msg))
            }
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: product_wave_landed domain:admit type:service
pub mod product_wave_landed {
    use super::{err_msg, scan_wave, WaveReport};
    use std::path::Path;

    pub struct ProductWaveLanded {
        pub tree: String,
        pub report: String,
    }

    impl ProductWaveLanded {
        pub fn new() -> Self {
            Self {
                tree: String::new(),
                report: String::new(),
            }
        }

        /// Prove AEP28-ENV-001 through AEP28-ENV-010 all landed before journals
        pub fn process(&mut self) -> anyhow::Result<()> {
            let wave: WaveReport = scan_wave(Path::new(&self.tree));
            if wave.missing.is_empty() {
                self.report = String::from("landed");
                Ok(())
            } else {
                self.report = wave.missing.join(",");
                let mut msg = String::from("product wave missing ");
                msg.push_str(&wave.missing.join(","));
                Err(err_msg(msg))
            }
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: journal_gate domain:admit type:service
pub mod journal_gate {
    use super::{err_msg, journal_allow, scan_wave};
    use std::path::Path;

    pub struct JournalGate {
        pub wave: String,
        pub allow: String,
    }

    impl JournalGate {
        pub fn new() -> Self {
            Self {
                wave: String::new(),
                allow: String::new(),
            }
        }

        /// Allow Admit crate journals only after the product wave landed
        pub fn process(&mut self) -> anyhow::Result<()> {
            let report = scan_wave(Path::new(&self.wave));
            let v = journal_allow(&report);
            if v.allow {
                self.allow = String::from("true");
                Ok(())
            } else {
                self.allow = String::from("false");
                Err(err_msg(v.reason.clone()))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn must(cond: bool) {
        if cond == false {
            std::process::abort();
        }
    }

    fn temp_root(tag: &str) -> PathBuf {
        let n = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(1);
        let mut name = String::from("aep-env-011-");
        name.push_str(tag);
        name.push('-');
        name.push_str(&n.to_string());
        let p = PathBuf::from("/tmp").join(name);
        let _ = fs::create_dir_all(&p);
        p
    }

    fn write_file(root: &Path, rel: &str, body: &str) {
        let p = root.join(rel);
        if let Some(parent) = p.parent() {
            let _ = fs::create_dir_all(parent);
        }
        fs::write(&p, body.as_bytes()).expect("write fixture");
    }

    fn good_filter() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    const admit = admitCollectAll(walls);\n    const applied = admit.allow;\n    if (labLatticeFilterEnabled()) {\n      await this.latticeFilter.filterAsync(event);\n    }\n    return { admit, applied };\n  }\n}\n"
    }

    fn skip_filter() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    if (labLatticeFilterEnabled()) { return this.latticeFilter.filterAsync(event); }\n    return runEvaluationChain(event);\n  }\n}\n"
    }

    fn plant_wave(root: &Path, with007_ticket: bool) {
        write_file(root, "envelope-walls/crate/src/lib.rs", "// AEP28-ENV-001\n");
        write_file(
            root,
            "admit-writing-walls/aep-registration.gaplune",
            "ticket: AEP28-ENV-002\n",
        );
        write_file(
            root,
            "admit-trust-floor/aep-registration.gaplune",
            "ticket: AEP28-ENV-003\n",
        );
        write_file(
            root,
            "admit-channel-order-walls/aep-registration.gaplune",
            "ticket: AEP28-ENV-004\n",
        );
        write_file(
            root,
            "admit-temporal-bounds/aep-registration.gaplune",
            "ticket: AEP28-ENV-005\n",
        );
        write_file(
            root,
            "live-crossing-admit-apply/crate/src/lib.rs",
            "// AEP28-ENV-006\n",
        );
        if with007_ticket {
            let mut body = String::from("// AEP28-ENV-007\n");
            body.push_str(good_filter());
            write_file(
                root,
                "dynAEP/bridge/hyperlattice/HyperlatticeFilter.ts",
                &body,
            );
        } else {
            write_file(
                root,
                "dynAEP/bridge/hyperlattice/HyperlatticeFilter.ts",
                good_filter(),
            );
        }
        write_file(
            root,
            "envelope-algebra/aep-registration.gaplune",
            "ticket: AEP28-ENV-008\n",
        );
        write_file(
            root,
            "envelope-product-copy/aep-registration.gaplune",
            "ticket: AEP28-ENV-009\n",
        );
        write_file(
            root,
            "envelope-algebra-ci/aep-registration.gaplune",
            "ticket: AEP28-ENV-010\n",
        );
    }

    #[test]
    fn ticket_in_source_detects_registration() {
        must(ticket_in_source("ticket: AEP28-ENV-010\n", "AEP28-ENV-010") == true);
        must(ticket_in_source("ticket: AEP28-ENV-009\n", "AEP28-ENV-010") == false);
    }

    #[test]
    fn env007_good_filter_lands() {
        must(env007_live_path_landed(good_filter()) == true);
    }

    #[test]
    fn env007_skip_filter_does_not_land() {
        must(env007_live_path_landed(skip_filter()) == false);
    }

    #[test]
    fn missing_tickets_deny_journals() {
        let root = temp_root("missing");
        write_file(&root, "only.md", "nothing\n");
        let v = run_gate(&root);
        must(v.allow == false);
        must(v.wave.missing.is_empty() == false);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn full_wave_allows_journals() {
        let root = temp_root("full");
        plant_wave(&root, true);
        let v = run_gate(&root);
        must(v.allow == true);
        must(v.wave.missing.is_empty() == true);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn env007_via_live_filter_without_ticket_line() {
        let root = temp_root("env007-filter");
        plant_wave(&root, false);
        let v = run_gate(&root);
        must(v.allow == true);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn journal_before_wave_denied() {
        let root = temp_root("before");
        write_file(&root, "envelope-walls/crate/src/lib.rs", "// AEP28-ENV-001\n");
        let v = run_gate(&root);
        must(v.allow == false);
        must(v.reason.contains("journals denied") == true);
        let mut gate = journal_gate::JournalGate::new();
        gate.wave = root.to_string_lossy().into_owned();
        must(gate.process().is_err() == true);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn modules_process_on_planted_wave() {
        let root = temp_root("mods");
        plant_wave(&root, true);
        let mut one = product_ticket_landed::ProductTicketLanded::new();
        one.ticket = String::from("AEP28-ENV-008");
        one.source = String::from("ticket: AEP28-ENV-008\n");
        must(one.process().is_ok() == true);
        must(one.landed.as_str() == "true");
        let mut wave = product_wave_landed::ProductWaveLanded::new();
        wave.tree = root.to_string_lossy().into_owned();
        must(wave.process().is_ok() == true);
        let mut gate = journal_gate::JournalGate::new();
        gate.wave = root.to_string_lossy().into_owned();
        must(gate.process().is_ok() == true);
        must(gate.allow.as_str() == "true");
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn live_components_tree_when_present() {
        let root = default_components_root();
        if root.is_dir() == false {
            return;
        }
        let v = run_gate(&root);
        if v.allow == false {
            let formatted = format_verdict(&v);
            must(formatted.contains("deny") == true);
            return;
        }
        must(v.allow == true);
        must(default_admit_crate().is_dir() == true);
    }
}
