// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aepcaw/wtp/v1/wtp.proto

package wtpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashAlgorithm int32

const (
	HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED HashAlgorithm = 0 // wire-incompatible  -  receivers MUST reject.
	HashAlgorithm_HASH_ALGORITHM_HMAC_SHA256 HashAlgorithm = 1
	HashAlgorithm_HASH_ALGORITHM_HMAC_SHA512 HashAlgorithm = 2
)

// Enum value maps for HashAlgorithm.
var (
	HashAlgorithm_name = map[int32]string{
		0: "HASH_ALGORITHM_UNSPECIFIED",
		1: "HASH_ALGORITHM_HMAC_SHA256",
		2: "HASH_ALGORITHM_HMAC_SHA512",
	}
	HashAlgorithm_value = map[string]int32{
		"HASH_ALGORITHM_UNSPECIFIED": 0,
		"HASH_ALGORITHM_HMAC_SHA256": 1,
		"HASH_ALGORITHM_HMAC_SHA512": 2,
	}
)

func (x HashAlgorithm) Enum() *HashAlgorithm {
	p := new(HashAlgorithm)
	*p = x
	return p
}

func (x HashAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_aepcaw_wtp_v1_wtp_proto_enumTypes[0].Descriptor()
}

func (HashAlgorithm) Type() protoreflect.EnumType {
	return &file_aepcaw_wtp_v1_wtp_proto_enumTypes[0]
}

func (x HashAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgorithm.Descriptor instead.
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{0}
}

type UserSource int32

const (
	UserSource_USER_SOURCE_UNSPECIFIED UserSource = 0
	UserSource_USER_SOURCE_OS          UserSource = 1
	UserSource_USER_SOURCE_TAILSCALE   UserSource = 2
)

// Enum value maps for UserSource.
var (
	UserSource_name = map[int32]string{
		0: "USER_SOURCE_UNSPECIFIED",
		1: "USER_SOURCE_OS",
		2: "USER_SOURCE_TAILSCALE",
	}
	UserSource_value = map[string]int32{
		"USER_SOURCE_UNSPECIFIED": 0,
		"USER_SOURCE_OS":          1,
		"USER_SOURCE_TAILSCALE":   2,
	}
)

func (x UserSource) Enum() *UserSource {
	p := new(UserSource)
	*p = x
	return p
}

func (x UserSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSource) Descriptor() protoreflect.EnumDescriptor {
	return file_aepcaw_wtp_v1_wtp_proto_enumTypes[1].Descriptor()
}

func (UserSource) Type() protoreflect.EnumType {
	return &file_aepcaw_wtp_v1_wtp_proto_enumTypes[1]
}

func (x UserSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSource.Descriptor instead.
func (UserSource) EnumDescriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{1}
}

type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_NONE        Compression = 1
	Compression_COMPRESSION_ZSTD        Compression = 2
	Compression_COMPRESSION_GZIP        Compression = 3
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_NONE",
		2: "COMPRESSION_ZSTD",
		3: "COMPRESSION_GZIP",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_NONE":        1,
		"COMPRESSION_ZSTD":        2,
		"COMPRESSION_GZIP":        3,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_aepcaw_wtp_v1_wtp_proto_enumTypes[2].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_aepcaw_wtp_v1_wtp_proto_enumTypes[2]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{2}
}

type TransportLossReason int32

const (
	TransportLossReason_TRANSPORT_LOSS_REASON_UNSPECIFIED    TransportLossReason = 0 // wire-incompatible  -  receivers MUST reject.
	TransportLossReason_TRANSPORT_LOSS_REASON_OVERFLOW       TransportLossReason = 1 // WAL hit max_total_bytes; oldest segments dropped.
	TransportLossReason_TRANSPORT_LOSS_REASON_CRC_CORRUPTION TransportLossReason = 2 // CRC mismatch encountered during WAL replay.
	// Extended (2026-04-27 spec)  -  gated by client-side
	// output.wtp.emit_extended_loss_reasons. Strict-enum receivers reject
	// unknown values per the UNSPECIFIED contract.
	TransportLossReason_TRANSPORT_LOSS_REASON_MAPPER_FAILURE          TransportLossReason = 3 // compact.Encode wrapped a mapper-side error.
	TransportLossReason_TRANSPORT_LOSS_REASON_INVALID_MAPPER          TransportLossReason = 4 // defense-in-depth: typed-nil mapper escaped validation.
	TransportLossReason_TRANSPORT_LOSS_REASON_INVALID_TIMESTAMP       TransportLossReason = 5 // ev.Timestamp zero or pre-epoch.
	TransportLossReason_TRANSPORT_LOSS_REASON_INVALID_UTF8            TransportLossReason = 6 // chain.EncodeCanonical reported invalid UTF-8.
	TransportLossReason_TRANSPORT_LOSS_REASON_SEQUENCE_OVERFLOW       TransportLossReason = 7 // ev.Chain.Sequence > math.MaxInt64.
	TransportLossReason_TRANSPORT_LOSS_REASON_ACK_REGRESSION_AFTER_GC TransportLossReason = 8 // computeReplayStart synthesized prefix gap.
)

// Enum value maps for TransportLossReason.
var (
	TransportLossReason_name = map[int32]string{
		0: "TRANSPORT_LOSS_REASON_UNSPECIFIED",
		1: "TRANSPORT_LOSS_REASON_OVERFLOW",
		2: "TRANSPORT_LOSS_REASON_CRC_CORRUPTION",
		3: "TRANSPORT_LOSS_REASON_MAPPER_FAILURE",
		4: "TRANSPORT_LOSS_REASON_INVALID_MAPPER",
		5: "TRANSPORT_LOSS_REASON_INVALID_TIMESTAMP",
		6: "TRANSPORT_LOSS_REASON_INVALID_UTF8",
		7: "TRANSPORT_LOSS_REASON_SEQUENCE_OVERFLOW",
		8: "TRANSPORT_LOSS_REASON_ACK_REGRESSION_AFTER_GC",
	}
	TransportLossReason_value = map[string]int32{
		"TRANSPORT_LOSS_REASON_UNSPECIFIED":             0,
		"TRANSPORT_LOSS_REASON_OVERFLOW":                1,
		"TRANSPORT_LOSS_REASON_CRC_CORRUPTION":          2,
		"TRANSPORT_LOSS_REASON_MAPPER_FAILURE":          3,
		"TRANSPORT_LOSS_REASON_INVALID_MAPPER":          4,
		"TRANSPORT_LOSS_REASON_INVALID_TIMESTAMP":       5,
		"TRANSPORT_LOSS_REASON_INVALID_UTF8":            6,
		"TRANSPORT_LOSS_REASON_SEQUENCE_OVERFLOW":       7,
		"TRANSPORT_LOSS_REASON_ACK_REGRESSION_AFTER_GC": 8,
	}
)

func (x TransportLossReason) Enum() *TransportLossReason {
	p := new(TransportLossReason)
	*p = x
	return p
}

func (x TransportLossReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportLossReason) Descriptor() protoreflect.EnumDescriptor {
	return file_aepcaw_wtp_v1_wtp_proto_enumTypes[3].Descriptor()
}

func (TransportLossReason) Type() protoreflect.EnumType {
	return &file_aepcaw_wtp_v1_wtp_proto_enumTypes[3]
}

func (x TransportLossReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportLossReason.Descriptor instead.
func (TransportLossReason) EnumDescriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{3}
}

type GoawayCode int32

const (
	GoawayCode_GOAWAY_CODE_UNSPECIFIED GoawayCode = 0 // v0.4-legacy catch-all; clients MUST treat
	// as transient and reconnect. v0.5+ servers
	// SHOULD emit GOAWAY_CODE_PROTOCOL_ERROR for
	// protocol-invariant violations instead.
	GoawayCode_GOAWAY_CODE_DRAINING GoawayCode = 1 // graceful shutdown; reconnect to a different instance.
	GoawayCode_GOAWAY_CODE_OVERLOAD GoawayCode = 2 // server overloaded; reconnect with backoff.
	GoawayCode_GOAWAY_CODE_UPGRADE  GoawayCode = 3 // server upgrade in progress; reconnect after delay.
	GoawayCode_GOAWAY_CODE_AUTH     GoawayCode = 4 // authentication/authorization failed; do not auto-retry.
	GoawayCode_GOAWAY_CODE_POLICY   GoawayCode = 5 // policy snapshot in SessionInit was rejected
	// (e.g. version regressed, content hash mismatch
	// for an existing (policy_id, version)).
	GoawayCode_GOAWAY_CODE_PROTOCOL_ERROR GoawayCode = 6 // server-detected protocol invariant violation
)

// Enum value maps for GoawayCode.
var (
	GoawayCode_name = map[int32]string{
		0: "GOAWAY_CODE_UNSPECIFIED",
		1: "GOAWAY_CODE_DRAINING",
		2: "GOAWAY_CODE_OVERLOAD",
		3: "GOAWAY_CODE_UPGRADE",
		4: "GOAWAY_CODE_AUTH",
		5: "GOAWAY_CODE_POLICY",
		6: "GOAWAY_CODE_PROTOCOL_ERROR",
	}
	GoawayCode_value = map[string]int32{
		"GOAWAY_CODE_UNSPECIFIED":    0,
		"GOAWAY_CODE_DRAINING":       1,
		"GOAWAY_CODE_OVERLOAD":       2,
		"GOAWAY_CODE_UPGRADE":        3,
		"GOAWAY_CODE_AUTH":           4,
		"GOAWAY_CODE_POLICY":         5,
		"GOAWAY_CODE_PROTOCOL_ERROR": 6,
	}
)

func (x GoawayCode) Enum() *GoawayCode {
	p := new(GoawayCode)
	*p = x
	return p
}

func (x GoawayCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoawayCode) Descriptor() protoreflect.EnumDescriptor {
	return file_aepcaw_wtp_v1_wtp_proto_enumTypes[4].Descriptor()
}

func (GoawayCode) Type() protoreflect.EnumType {
	return &file_aepcaw_wtp_v1_wtp_proto_enumTypes[4]
}

func (x GoawayCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoawayCode.Descriptor instead.
func (GoawayCode) EnumDescriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{4}
}

type ClientShutdownReason int32

const (
	ClientShutdownReason_CLIENT_SHUTDOWN_REASON_UNSPECIFIED ClientShutdownReason = 0
	ClientShutdownReason_CLIENT_SHUTDOWN_REASON_NORMAL      ClientShutdownReason = 1 // clean shutdown of the agent.
	ClientShutdownReason_CLIENT_SHUTDOWN_REASON_RECONFIGURE ClientShutdownReason = 2 // operator-driven reconfig; expect quick reconnect.
	ClientShutdownReason_CLIENT_SHUTDOWN_REASON_FATAL       ClientShutdownReason = 3 // unrecoverable error; do not expect reconnect.
)

// Enum value maps for ClientShutdownReason.
var (
	ClientShutdownReason_name = map[int32]string{
		0: "CLIENT_SHUTDOWN_REASON_UNSPECIFIED",
		1: "CLIENT_SHUTDOWN_REASON_NORMAL",
		2: "CLIENT_SHUTDOWN_REASON_RECONFIGURE",
		3: "CLIENT_SHUTDOWN_REASON_FATAL",
	}
	ClientShutdownReason_value = map[string]int32{
		"CLIENT_SHUTDOWN_REASON_UNSPECIFIED": 0,
		"CLIENT_SHUTDOWN_REASON_NORMAL":      1,
		"CLIENT_SHUTDOWN_REASON_RECONFIGURE": 2,
		"CLIENT_SHUTDOWN_REASON_FATAL":       3,
	}
)

func (x ClientShutdownReason) Enum() *ClientShutdownReason {
	p := new(ClientShutdownReason)
	*p = x
	return p
}

func (x ClientShutdownReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientShutdownReason) Descriptor() protoreflect.EnumDescriptor {
	return file_aepcaw_wtp_v1_wtp_proto_enumTypes[5].Descriptor()
}

func (ClientShutdownReason) Type() protoreflect.EnumType {
	return &file_aepcaw_wtp_v1_wtp_proto_enumTypes[5]
}

func (x ClientShutdownReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientShutdownReason.Descriptor instead.
func (ClientShutdownReason) EnumDescriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{5}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_SessionInit
	//	*ClientMessage_SessionUpdate
	//	*ClientMessage_EventBatch
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_TransportLoss
	//	*ClientMessage_Shutdown
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetSessionInit() *SessionInit {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_SessionInit); ok {
			return x.SessionInit
		}
	}
	return nil
}

func (x *ClientMessage) GetSessionUpdate() *SessionUpdate {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_SessionUpdate); ok {
			return x.SessionUpdate
		}
	}
	return nil
}

func (x *ClientMessage) GetEventBatch() *EventBatch {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_EventBatch); ok {
			return x.EventBatch
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetTransportLoss() *TransportLoss {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_TransportLoss); ok {
			return x.TransportLoss
		}
	}
	return nil
}

func (x *ClientMessage) GetShutdown() *ClientShutdown {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_SessionInit struct {
	SessionInit *SessionInit `protobuf:"bytes,1,opt,name=session_init,json=sessionInit,proto3,oneof"`
}

type ClientMessage_SessionUpdate struct {
	SessionUpdate *SessionUpdate `protobuf:"bytes,2,opt,name=session_update,json=sessionUpdate,proto3,oneof"`
}

type ClientMessage_EventBatch struct {
	EventBatch *EventBatch `protobuf:"bytes,3,opt,name=event_batch,json=eventBatch,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type ClientMessage_TransportLoss struct {
	TransportLoss *TransportLoss `protobuf:"bytes,5,opt,name=transport_loss,json=transportLoss,proto3,oneof"`
}

type ClientMessage_Shutdown struct {
	Shutdown *ClientShutdown `protobuf:"bytes,6,opt,name=shutdown,proto3,oneof"`
}

func (*ClientMessage_SessionInit) isClientMessage_Msg() {}

func (*ClientMessage_SessionUpdate) isClientMessage_Msg() {}

func (*ClientMessage_EventBatch) isClientMessage_Msg() {}

func (*ClientMessage_Heartbeat) isClientMessage_Msg() {}

func (*ClientMessage_TransportLoss) isClientMessage_Msg() {}

func (*ClientMessage_Shutdown) isClientMessage_Msg() {}

// ServerMessage frames sent from server to client. Semantics:
//   - SessionAck        -  sent exactly once after SessionInit; accepted=false
//     terminates the session (client must disconnect).
//   - BatchAck          -  sent per-batch progress ack; advances the client's
//     ack high-watermark and unblocks WAL GC.
//   - ServerHeartbeat   -  periodic; carries the server's current
//     ack_high_watermark_seq so an idle client still
//     learns about catch-up after replay completes.
//   - Goaway            -  server requesting reconnect; carries an enum code.
//   - server_update     -  server-issued SessionUpdate (key/generation
//     rotation initiated by the server).
//   - policy_push       -  mid-session policy update pushed to a live agent.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_SessionAck
	//	*ServerMessage_BatchAck
	//	*ServerMessage_ServerHeartbeat
	//	*ServerMessage_Goaway
	//	*ServerMessage_ServerUpdate
	//	*ServerMessage_PolicyPush
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetSessionAck() *SessionAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_SessionAck); ok {
			return x.SessionAck
		}
	}
	return nil
}

func (x *ServerMessage) GetBatchAck() *BatchAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_BatchAck); ok {
			return x.BatchAck
		}
	}
	return nil
}

func (x *ServerMessage) GetServerHeartbeat() *ServerHeartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ServerHeartbeat); ok {
			return x.ServerHeartbeat
		}
	}
	return nil
}

func (x *ServerMessage) GetGoaway() *Goaway {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Goaway); ok {
			return x.Goaway
		}
	}
	return nil
}

func (x *ServerMessage) GetServerUpdate() *SessionUpdate {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ServerUpdate); ok {
			return x.ServerUpdate
		}
	}
	return nil
}

func (x *ServerMessage) GetPolicyPush() *PolicyPush {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_PolicyPush); ok {
			return x.PolicyPush
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_SessionAck struct {
	SessionAck *SessionAck `protobuf:"bytes,1,opt,name=session_ack,json=sessionAck,proto3,oneof"`
}

type ServerMessage_BatchAck struct {
	BatchAck *BatchAck `protobuf:"bytes,2,opt,name=batch_ack,json=batchAck,proto3,oneof"`
}

type ServerMessage_ServerHeartbeat struct {
	ServerHeartbeat *ServerHeartbeat `protobuf:"bytes,3,opt,name=server_heartbeat,json=serverHeartbeat,proto3,oneof"`
}

type ServerMessage_Goaway struct {
	Goaway *Goaway `protobuf:"bytes,4,opt,name=goaway,proto3,oneof"`
}

type ServerMessage_ServerUpdate struct {
	ServerUpdate *SessionUpdate `protobuf:"bytes,5,opt,name=server_update,json=serverUpdate,proto3,oneof"`
}

type ServerMessage_PolicyPush struct {
	PolicyPush *PolicyPush `protobuf:"bytes,6,opt,name=policy_push,json=policyPush,proto3,oneof"`
}

func (*ServerMessage_SessionAck) isServerMessage_Msg() {}

func (*ServerMessage_BatchAck) isServerMessage_Msg() {}

func (*ServerMessage_ServerHeartbeat) isServerMessage_Msg() {}

func (*ServerMessage_Goaway) isServerMessage_Msg() {}

func (*ServerMessage_ServerUpdate) isServerMessage_Msg() {}

func (*ServerMessage_PolicyPush) isServerMessage_Msg() {}

// SessionInit (§7.1)
type SessionInit struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OcsfVersion         string                 `protobuf:"bytes,2,opt,name=ocsf_version,json=ocsfVersion,proto3" json:"ocsf_version,omitempty"`
	FormatVersion       uint32                 `protobuf:"varint,3,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Algorithm           HashAlgorithm          `protobuf:"varint,4,opt,name=algorithm,proto3,enum=aepcaw.wtp.v1.HashAlgorithm" json:"algorithm,omitempty"`
	KeyFingerprint      string                 `protobuf:"bytes,5,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	ContextDigest       string                 `protobuf:"bytes,6,opt,name=context_digest,json=contextDigest,proto3" json:"context_digest,omitempty"` // hex-encoded SHA-256
	WalHighWatermarkSeq uint64                 `protobuf:"varint,7,opt,name=wal_high_watermark_seq,json=walHighWatermarkSeq,proto3" json:"wal_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,8,opt,name=generation,proto3" json:"generation,omitempty"`
	AgentId             string                 `protobuf:"bytes,9,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion        string                 `protobuf:"bytes,10,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	TotalChained        uint64                 `protobuf:"varint,11,opt,name=total_chained,json=totalChained,proto3" json:"total_chained,omitempty"`         // count of records sink has chained
	DecisionContext     *DecisionContext       `protobuf:"bytes,12,opt,name=decision_context,json=decisionContext,proto3" json:"decision_context,omitempty"` // agent-reported identity/env context
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionInit) Reset() {
	*x = SessionInit{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInit) ProtoMessage() {}

func (x *SessionInit) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInit.ProtoReflect.Descriptor instead.
func (*SessionInit) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{2}
}

func (x *SessionInit) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInit) GetOcsfVersion() string {
	if x != nil {
		return x.OcsfVersion
	}
	return ""
}

func (x *SessionInit) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SessionInit) GetAlgorithm() HashAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED
}

func (x *SessionInit) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

func (x *SessionInit) GetContextDigest() string {
	if x != nil {
		return x.ContextDigest
	}
	return ""
}

func (x *SessionInit) GetWalHighWatermarkSeq() uint64 {
	if x != nil {
		return x.WalHighWatermarkSeq
	}
	return 0
}

func (x *SessionInit) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionInit) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionInit) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SessionInit) GetTotalChained() uint64 {
	if x != nil {
		return x.TotalChained
	}
	return 0
}

func (x *SessionInit) GetDecisionContext() *DecisionContext {
	if x != nil {
		return x.DecisionContext
	}
	return nil
}

// Decision context reported by the agent so the server can resolve the
// bound policy from identity + environment signals. All fields optional;
// the agent sends what it has. `extra` is an open extension so new
// signals do not require a schema bump.
type DecisionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	User          *DecisionContext_User  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionContext) Reset() {
	*x = DecisionContext{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionContext) ProtoMessage() {}

func (x *DecisionContext) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionContext.ProtoReflect.Descriptor instead.
func (*DecisionContext) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{3}
}

func (x *DecisionContext) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DecisionContext) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DecisionContext) GetUser() *DecisionContext_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DecisionContext) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type SessionAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AckHighWatermarkSeq uint64                 `protobuf:"varint,1,opt,name=ack_high_watermark_seq,json=ackHighWatermarkSeq,proto3" json:"ack_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Accepted            bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason        string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // empty when accepted=true
	// Policy push: when an agent has a policy_bindings row for its
	// tenant+agent_id, the server resolves the bound policy and ships
	// it down with the SessionAck. The agent is expected to verify the
	// signature against its locally-configured trust bundle and install
	// the policy for any sessions admitted after this point.
	//
	// policy_id "" means no policy was resolved (no binding, or the
	// binding's target policy is missing). In that case the agent
	// falls back to its local file-based policy. policy_id MUST always
	// appear with version + content + content_hash; signature MAY be
	// empty for unsigned-policy deployments (the agent's verification
	// posture decides whether to install).
	PolicyId          string   `protobuf:"bytes,5,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion     uint32   `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyContentHash string   `protobuf:"bytes,7,opt,name=policy_content_hash,json=policyContentHash,proto3" json:"policy_content_hash,omitempty"`    // "sha256:<hex>"
	PolicyContent     []byte   `protobuf:"bytes,8,opt,name=policy_content,json=policyContent,proto3" json:"policy_content,omitempty"`                  // raw policy bytes (YAML)
	PolicySignature   []byte   `protobuf:"bytes,9,opt,name=policy_signature,json=policySignature,proto3" json:"policy_signature,omitempty"`            // raw signature over policy_content
	PolicySignerKeyId string   `protobuf:"bytes,10,opt,name=policy_signer_key_id,json=policySignerKeyId,proto3" json:"policy_signer_key_id,omitempty"` // identifies the signing key in the agent's trust bundle
	OverlayIds        []string `protobuf:"bytes,11,rep,name=overlay_ids,json=overlayIds,proto3" json:"overlay_ids,omitempty"`                          // overlay IDs the server expects this agent to apply, lex-sorted
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionAck) Reset() {
	*x = SessionAck{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAck) ProtoMessage() {}

func (x *SessionAck) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAck.ProtoReflect.Descriptor instead.
func (*SessionAck) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{4}
}

func (x *SessionAck) GetAckHighWatermarkSeq() uint64 {
	if x != nil {
		return x.AckHighWatermarkSeq
	}
	return 0
}

func (x *SessionAck) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SessionAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *SessionAck) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *SessionAck) GetPolicyVersion() uint32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *SessionAck) GetPolicyContentHash() string {
	if x != nil {
		return x.PolicyContentHash
	}
	return ""
}

func (x *SessionAck) GetPolicyContent() []byte {
	if x != nil {
		return x.PolicyContent
	}
	return nil
}

func (x *SessionAck) GetPolicySignature() []byte {
	if x != nil {
		return x.PolicySignature
	}
	return nil
}

func (x *SessionAck) GetPolicySignerKeyId() string {
	if x != nil {
		return x.PolicySignerKeyId
	}
	return ""
}

func (x *SessionAck) GetOverlayIds() []string {
	if x != nil {
		return x.OverlayIds
	}
	return nil
}

// SessionUpdate (§7.2): generation roll, key rotation, context change.
type SessionUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NewGeneration     uint32                 `protobuf:"varint,1,opt,name=new_generation,json=newGeneration,proto3" json:"new_generation,omitempty"`
	NewKeyFingerprint string                 `protobuf:"bytes,2,opt,name=new_key_fingerprint,json=newKeyFingerprint,proto3" json:"new_key_fingerprint,omitempty"`
	NewContextDigest  string                 `protobuf:"bytes,3,opt,name=new_context_digest,json=newContextDigest,proto3" json:"new_context_digest,omitempty"`
	BoundarySequence  uint64                 `protobuf:"varint,4,opt,name=boundary_sequence,json=boundarySequence,proto3" json:"boundary_sequence,omitempty"` // last seq of prior generation
	DecisionContext   *DecisionContext       `protobuf:"bytes,5,opt,name=decision_context,json=decisionContext,proto3" json:"decision_context,omitempty"`     // updated context for mid-session re-resolution
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionUpdate) Reset() {
	*x = SessionUpdate{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUpdate) ProtoMessage() {}

func (x *SessionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUpdate.ProtoReflect.Descriptor instead.
func (*SessionUpdate) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{5}
}

func (x *SessionUpdate) GetNewGeneration() uint32 {
	if x != nil {
		return x.NewGeneration
	}
	return 0
}

func (x *SessionUpdate) GetNewKeyFingerprint() string {
	if x != nil {
		return x.NewKeyFingerprint
	}
	return ""
}

func (x *SessionUpdate) GetNewContextDigest() string {
	if x != nil {
		return x.NewContextDigest
	}
	return ""
}

func (x *SessionUpdate) GetBoundarySequence() uint64 {
	if x != nil {
		return x.BoundarySequence
	}
	return 0
}

func (x *SessionUpdate) GetDecisionContext() *DecisionContext {
	if x != nil {
		return x.DecisionContext
	}
	return nil
}

// PolicyPush (§7.6): mid-session policy update.
//
// Sent when an already-admitted agent's bound policy is edited (content
// change) or rebound (policy_id change). Field semantics match the
// policy_* fields embedded in SessionAck  -  receiving the same
// (policy_id, policy_content_hash) twice is a no-op on the agent
// because the install hook is idempotent.
//
// Delivery is best-effort. A lost PolicyPush is recovered on the next
// reconnect via SessionAck.
//
// Sent ONLY after SessionAck has admitted the session. policy_id == ""
// means "unbind  -  revert to local file policy"; in that case all
// other fields MAY be empty.
type PolicyPush struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PolicyId          string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion     uint32                 `protobuf:"varint,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyContentHash string                 `protobuf:"bytes,3,opt,name=policy_content_hash,json=policyContentHash,proto3" json:"policy_content_hash,omitempty"` // "sha256:<hex>"
	PolicyContent     []byte                 `protobuf:"bytes,4,opt,name=policy_content,json=policyContent,proto3" json:"policy_content,omitempty"`               // raw policy bytes (YAML)
	PolicySignature   []byte                 `protobuf:"bytes,5,opt,name=policy_signature,json=policySignature,proto3" json:"policy_signature,omitempty"`         // raw signature over policy_content
	PolicySignerKeyId string                 `protobuf:"bytes,6,opt,name=policy_signer_key_id,json=policySignerKeyId,proto3" json:"policy_signer_key_id,omitempty"`
	OverlayIds        []string               `protobuf:"bytes,7,rep,name=overlay_ids,json=overlayIds,proto3" json:"overlay_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PolicyPush) Reset() {
	*x = PolicyPush{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyPush) ProtoMessage() {}

func (x *PolicyPush) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyPush.ProtoReflect.Descriptor instead.
func (*PolicyPush) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{6}
}

func (x *PolicyPush) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyPush) GetPolicyVersion() uint32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *PolicyPush) GetPolicyContentHash() string {
	if x != nil {
		return x.PolicyContentHash
	}
	return ""
}

func (x *PolicyPush) GetPolicyContent() []byte {
	if x != nil {
		return x.PolicyContent
	}
	return nil
}

func (x *PolicyPush) GetPolicySignature() []byte {
	if x != nil {
		return x.PolicySignature
	}
	return nil
}

func (x *PolicyPush) GetPolicySignerKeyId() string {
	if x != nil {
		return x.PolicySignerKeyId
	}
	return ""
}

func (x *PolicyPush) GetOverlayIds() []string {
	if x != nil {
		return x.OverlayIds
	}
	return nil
}

// EventBatch (§7.3)  -  the unit of in-flight work between client and server.
//
// The batch body is mutually exclusive: a sender MUST populate exactly one
// of `uncompressed` (when compression == COMPRESSION_NONE) or
// `compressed_payload` (when compression is COMPRESSION_ZSTD or
// COMPRESSION_GZIP). Receivers MUST reject batches where the oneof case
// disagrees with the compression field, where compression is
// COMPRESSION_UNSPECIFIED, or where the body oneof is unset.
type EventBatch struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FromSequence uint64                 `protobuf:"varint,1,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	ToSequence   uint64                 `protobuf:"varint,2,opt,name=to_sequence,json=toSequence,proto3" json:"to_sequence,omitempty"`
	Generation   uint32                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Compression  Compression            `protobuf:"varint,4,opt,name=compression,proto3,enum=aepcaw.wtp.v1.Compression" json:"compression,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*EventBatch_Uncompressed
	//	*EventBatch_CompressedPayload
	Body          isEventBatch_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{7}
}

func (x *EventBatch) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *EventBatch) GetToSequence() uint64 {
	if x != nil {
		return x.ToSequence
	}
	return 0
}

func (x *EventBatch) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *EventBatch) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *EventBatch) GetBody() isEventBatch_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EventBatch) GetUncompressed() *UncompressedEvents {
	if x != nil {
		if x, ok := x.Body.(*EventBatch_Uncompressed); ok {
			return x.Uncompressed
		}
	}
	return nil
}

func (x *EventBatch) GetCompressedPayload() []byte {
	if x != nil {
		if x, ok := x.Body.(*EventBatch_CompressedPayload); ok {
			return x.CompressedPayload
		}
	}
	return nil
}

type isEventBatch_Body interface {
	isEventBatch_Body()
}

type EventBatch_Uncompressed struct {
	Uncompressed *UncompressedEvents `protobuf:"bytes,5,opt,name=uncompressed,proto3,oneof"`
}

type EventBatch_CompressedPayload struct {
	CompressedPayload []byte `protobuf:"bytes,6,opt,name=compressed_payload,json=compressedPayload,proto3,oneof"`
}

func (*EventBatch_Uncompressed) isEventBatch_Body() {}

func (*EventBatch_CompressedPayload) isEventBatch_Body() {}

// UncompressedEvents wraps the repeated CompactEvent so it can sit inside
// the EventBatch.body oneof (proto3 forbids `repeated` directly in oneofs).
type UncompressedEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*CompactEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncompressedEvents) Reset() {
	*x = UncompressedEvents{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncompressedEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncompressedEvents) ProtoMessage() {}

func (x *UncompressedEvents) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncompressedEvents.ProtoReflect.Descriptor instead.
func (*UncompressedEvents) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{8}
}

func (x *UncompressedEvents) GetEvents() []*CompactEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// CompactEvent (§6.3)
type CompactEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sequence           uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Generation         uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	TimestampUnixNanos uint64                 `protobuf:"varint,3,opt,name=timestamp_unix_nanos,json=timestampUnixNanos,proto3" json:"timestamp_unix_nanos,omitempty"`
	OcsfClassUid       uint32                 `protobuf:"varint,4,opt,name=ocsf_class_uid,json=ocsfClassUid,proto3" json:"ocsf_class_uid,omitempty"`
	OcsfActivityId     uint32                 `protobuf:"varint,5,opt,name=ocsf_activity_id,json=ocsfActivityId,proto3" json:"ocsf_activity_id,omitempty"`
	Payload            []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // protobuf-encoded class-specific payload
	Integrity          *IntegrityRecord       `protobuf:"bytes,7,opt,name=integrity,proto3" json:"integrity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompactEvent) Reset() {
	*x = CompactEvent{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactEvent) ProtoMessage() {}

func (x *CompactEvent) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactEvent.ProtoReflect.Descriptor instead.
func (*CompactEvent) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{9}
}

func (x *CompactEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CompactEvent) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *CompactEvent) GetTimestampUnixNanos() uint64 {
	if x != nil {
		return x.TimestampUnixNanos
	}
	return 0
}

func (x *CompactEvent) GetOcsfClassUid() uint32 {
	if x != nil {
		return x.OcsfClassUid
	}
	return 0
}

func (x *CompactEvent) GetOcsfActivityId() uint32 {
	if x != nil {
		return x.OcsfActivityId
	}
	return 0
}

func (x *CompactEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CompactEvent) GetIntegrity() *IntegrityRecord {
	if x != nil {
		return x.Integrity
	}
	return nil
}

type IntegrityRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion  uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Sequence       uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Generation     uint32                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	PrevHash       string                 `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	EventHash      string                 `protobuf:"bytes,5,opt,name=event_hash,json=eventHash,proto3" json:"event_hash,omitempty"`
	ContextDigest  string                 `protobuf:"bytes,6,opt,name=context_digest,json=contextDigest,proto3" json:"context_digest,omitempty"`
	KeyFingerprint string                 `protobuf:"bytes,7,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IntegrityRecord) Reset() {
	*x = IntegrityRecord{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityRecord) ProtoMessage() {}

func (x *IntegrityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityRecord.ProtoReflect.Descriptor instead.
func (*IntegrityRecord) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{10}
}

func (x *IntegrityRecord) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *IntegrityRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *IntegrityRecord) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *IntegrityRecord) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *IntegrityRecord) GetEventHash() string {
	if x != nil {
		return x.EventHash
	}
	return ""
}

func (x *IntegrityRecord) GetContextDigest() string {
	if x != nil {
		return x.ContextDigest
	}
	return ""
}

func (x *IntegrityRecord) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

type Heartbeat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WalHighWatermarkSeq uint64                 `protobuf:"varint,1,opt,name=wal_high_watermark_seq,json=walHighWatermarkSeq,proto3" json:"wal_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{11}
}

func (x *Heartbeat) GetWalHighWatermarkSeq() uint64 {
	if x != nil {
		return x.WalHighWatermarkSeq
	}
	return 0
}

func (x *Heartbeat) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type ServerHeartbeat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AckHighWatermarkSeq uint64                 `protobuf:"varint,1,opt,name=ack_high_watermark_seq,json=ackHighWatermarkSeq,proto3" json:"ack_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerHeartbeat) Reset() {
	*x = ServerHeartbeat{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartbeat) ProtoMessage() {}

func (x *ServerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartbeat.ProtoReflect.Descriptor instead.
func (*ServerHeartbeat) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{12}
}

func (x *ServerHeartbeat) GetAckHighWatermarkSeq() uint64 {
	if x != nil {
		return x.AckHighWatermarkSeq
	}
	return 0
}

func (x *ServerHeartbeat) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type BatchAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AckHighWatermarkSeq uint64                 `protobuf:"varint,1,opt,name=ack_high_watermark_seq,json=ackHighWatermarkSeq,proto3" json:"ack_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{13}
}

func (x *BatchAck) GetAckHighWatermarkSeq() uint64 {
	if x != nil {
		return x.AckHighWatermarkSeq
	}
	return 0
}

func (x *BatchAck) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// TransportLoss (§7.5)  -  emitted on WAL overflow or CRC corruption.
type TransportLoss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSequence  uint64                 `protobuf:"varint,1,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	ToSequence    uint64                 `protobuf:"varint,2,opt,name=to_sequence,json=toSequence,proto3" json:"to_sequence,omitempty"`
	Generation    uint32                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Reason        TransportLossReason    `protobuf:"varint,4,opt,name=reason,proto3,enum=aepcaw.wtp.v1.TransportLossReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportLoss) Reset() {
	*x = TransportLoss{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportLoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportLoss) ProtoMessage() {}

func (x *TransportLoss) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportLoss.ProtoReflect.Descriptor instead.
func (*TransportLoss) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{14}
}

func (x *TransportLoss) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *TransportLoss) GetToSequence() uint64 {
	if x != nil {
		return x.ToSequence
	}
	return 0
}

func (x *TransportLoss) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *TransportLoss) GetReason() TransportLossReason {
	if x != nil {
		return x.Reason
	}
	return TransportLossReason_TRANSPORT_LOSS_REASON_UNSPECIFIED
}

type Goaway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  GoawayCode             `protobuf:"varint,1,opt,name=code,proto3,enum=aepcaw.wtp.v1.GoawayCode" json:"code,omitempty"`
	// Human-readable diagnostic message describing the reason for the
	// GOAWAY. The Watchtower server-side contract REQUIRES that this
	// string MUST NOT contain credentials, secrets, or PII  -  clients
	// may log it (per the client's LogGoawayMessage config flag) after
	// applying client-side sanitization (control-char stripping +
	// truncation to 512 bytes at a UTF-8 rune boundary + invalid-UTF-8
	// replacement with U+FFFD). Server operators MUST produce only
	// operator-facing diagnostic text here; the server is the
	// authoritative owner of the no-secrets contract. Client-side
	// redaction beyond the sanitization described above is out of scope.
	Message          string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RetryImmediately bool   `protobuf:"varint,3,opt,name=retry_immediately,json=retryImmediately,proto3" json:"retry_immediately,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Goaway) Reset() {
	*x = Goaway{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goaway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goaway) ProtoMessage() {}

func (x *Goaway) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goaway.ProtoReflect.Descriptor instead.
func (*Goaway) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{15}
}

func (x *Goaway) GetCode() GoawayCode {
	if x != nil {
		return x.Code
	}
	return GoawayCode_GOAWAY_CODE_UNSPECIFIED
}

func (x *Goaway) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Goaway) GetRetryImmediately() bool {
	if x != nil {
		return x.RetryImmediately
	}
	return false
}

type ClientShutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        ClientShutdownReason   `protobuf:"varint,1,opt,name=reason,proto3,enum=aepcaw.wtp.v1.ClientShutdownReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientShutdown) Reset() {
	*x = ClientShutdown{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientShutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientShutdown) ProtoMessage() {}

func (x *ClientShutdown) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientShutdown.ProtoReflect.Descriptor instead.
func (*ClientShutdown) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{16}
}

func (x *ClientShutdown) GetReason() ClientShutdownReason {
	if x != nil {
		return x.Reason
	}
	return ClientShutdownReason_CLIENT_SHUTDOWN_REASON_UNSPECIFIED
}

type DecisionContext_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Source        UserSource             `protobuf:"varint,2,opt,name=source,proto3,enum=aepcaw.wtp.v1.UserSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionContext_User) Reset() {
	*x = DecisionContext_User{}
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionContext_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionContext_User) ProtoMessage() {}

func (x *DecisionContext_User) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_wtp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionContext_User.ProtoReflect.Descriptor instead.
func (*DecisionContext_User) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DecisionContext_User) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DecisionContext_User) GetSource() UserSource {
	if x != nil {
		return x.Source
	}
	return UserSource_USER_SOURCE_UNSPECIFIED
}

var File_aepcaw_wtp_v1_wtp_proto protoreflect.FileDescriptor

const file_aepcaw_wtp_v1_wtp_proto_rawDesc = "" +
	"\n" +
	"\x17aepcaw/wtp/v1/wtp.proto\x12\raepcaw.wtp.v1\"\x9a\x03\n" +
	"\rClientMessage\x12?\n" +
	"\fsession_init\x18\x01 \x01(\v2\x1a.aepcaw.wtp.v1.SessionInitH\x00R\vsessionInit\x12E\n" +
	"\x0esession_update\x18\x02 \x01(\v2\x1c.aepcaw.wtp.v1.SessionUpdateH\x00R\rsessionUpdate\x12<\n" +
	"\vevent_batch\x18\x03 \x01(\v2\x19.aepcaw.wtp.v1.EventBatchH\x00R\n" +
	"eventBatch\x128\n" +
	"\theartbeat\x18\x04 \x01(\v2\x18.aepcaw.wtp.v1.HeartbeatH\x00R\theartbeat\x12E\n" +
	"\x0etransport_loss\x18\x05 \x01(\v2\x1c.aepcaw.wtp.v1.TransportLossH\x00R\rtransportLoss\x12;\n" +
	"\bshutdown\x18\x06 \x01(\v2\x1d.aepcaw.wtp.v1.ClientShutdownH\x00R\bshutdownB\x05\n" +
	"\x03msg\"\x8d\x03\n" +
	"\rServerMessage\x12<\n" +
	"\vsession_ack\x18\x01 \x01(\v2\x19.aepcaw.wtp.v1.SessionAckH\x00R\n" +
	"sessionAck\x126\n" +
	"\tbatch_ack\x18\x02 \x01(\v2\x17.aepcaw.wtp.v1.BatchAckH\x00R\bbatchAck\x12K\n" +
	"\x10server_heartbeat\x18\x03 \x01(\v2\x1e.aepcaw.wtp.v1.ServerHeartbeatH\x00R\x0fserverHeartbeat\x12/\n" +
	"\x06goaway\x18\x04 \x01(\v2\x15.aepcaw.wtp.v1.GoawayH\x00R\x06goaway\x12C\n" +
	"\rserver_update\x18\x05 \x01(\v2\x1c.aepcaw.wtp.v1.SessionUpdateH\x00R\fserverUpdate\x12<\n" +
	"\vpolicy_push\x18\x06 \x01(\v2\x19.aepcaw.wtp.v1.PolicyPushH\x00R\n" +
	"policyPushB\x05\n" +
	"\x03msg\"\x87\x04\n" +
	"\vSessionInit\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\focsf_version\x18\x02 \x01(\tR\vocsfVersion\x12%\n" +
	"\x0eformat_version\x18\x03 \x01(\rR\rformatVersion\x12:\n" +
	"\talgorithm\x18\x04 \x01(\x0e2\x1c.aepcaw.wtp.v1.HashAlgorithmR\talgorithm\x12'\n" +
	"\x0fkey_fingerprint\x18\x05 \x01(\tR\x0ekeyFingerprint\x12%\n" +
	"\x0econtext_digest\x18\x06 \x01(\tR\rcontextDigest\x123\n" +
	"\x16wal_high_watermark_seq\x18\a \x01(\x04R\x13walHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\b \x01(\rR\n" +
	"generation\x12\x19\n" +
	"\bagent_id\x18\t \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\n" +
	" \x01(\tR\fagentVersion\x12#\n" +
	"\rtotal_chained\x18\v \x01(\x04R\ftotalChained\x12I\n" +
	"\x10decision_context\x18\f \x01(\v2\x1e.aepcaw.wtp.v1.DecisionContextR\x0fdecisionContext\"\xc6\x02\n" +
	"\x0fDecisionContext\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x127\n" +
	"\x04user\x18\x03 \x01(\v2#.aepcaw.wtp.v1.DecisionContext.UserR\x04user\x12?\n" +
	"\x05extra\x18\x04 \x03(\v2).aepcaw.wtp.v1.DecisionContext.ExtraEntryR\x05extra\x1aO\n" +
	"\x04User\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x121\n" +
	"\x06source\x18\x02 \x01(\x0e2\x19.aepcaw.wtp.v1.UserSourceR\x06source\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x03\n" +
	"\n" +
	"SessionAck\x123\n" +
	"\x16ack_high_watermark_seq\x18\x01 \x01(\x04R\x13ackHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\x12\x1b\n" +
	"\tpolicy_id\x18\x05 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\rR\rpolicyVersion\x12.\n" +
	"\x13policy_content_hash\x18\a \x01(\tR\x11policyContentHash\x12%\n" +
	"\x0epolicy_content\x18\b \x01(\fR\rpolicyContent\x12)\n" +
	"\x10policy_signature\x18\t \x01(\fR\x0fpolicySignature\x12/\n" +
	"\x14policy_signer_key_id\x18\n" +
	" \x01(\tR\x11policySignerKeyId\x12\x1f\n" +
	"\voverlay_ids\x18\v \x03(\tR\n" +
	"overlayIds\"\x8c\x02\n" +
	"\rSessionUpdate\x12%\n" +
	"\x0enew_generation\x18\x01 \x01(\rR\rnewGeneration\x12.\n" +
	"\x13new_key_fingerprint\x18\x02 \x01(\tR\x11newKeyFingerprint\x12,\n" +
	"\x12new_context_digest\x18\x03 \x01(\tR\x10newContextDigest\x12+\n" +
	"\x11boundary_sequence\x18\x04 \x01(\x04R\x10boundarySequence\x12I\n" +
	"\x10decision_context\x18\x05 \x01(\v2\x1e.aepcaw.wtp.v1.DecisionContextR\x0fdecisionContext\"\xa4\x02\n" +
	"\n" +
	"PolicyPush\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\rR\rpolicyVersion\x12.\n" +
	"\x13policy_content_hash\x18\x03 \x01(\tR\x11policyContentHash\x12%\n" +
	"\x0epolicy_content\x18\x04 \x01(\fR\rpolicyContent\x12)\n" +
	"\x10policy_signature\x18\x05 \x01(\fR\x0fpolicySignature\x12/\n" +
	"\x14policy_signer_key_id\x18\x06 \x01(\tR\x11policySignerKeyId\x12\x1f\n" +
	"\voverlay_ids\x18\a \x03(\tR\n" +
	"overlayIds\"\xb2\x02\n" +
	"\n" +
	"EventBatch\x12#\n" +
	"\rfrom_sequence\x18\x01 \x01(\x04R\ffromSequence\x12\x1f\n" +
	"\vto_sequence\x18\x02 \x01(\x04R\n" +
	"toSequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\rR\n" +
	"generation\x12<\n" +
	"\vcompression\x18\x04 \x01(\x0e2\x1a.aepcaw.wtp.v1.CompressionR\vcompression\x12G\n" +
	"\funcompressed\x18\x05 \x01(\v2!.aepcaw.wtp.v1.UncompressedEventsH\x00R\funcompressed\x12/\n" +
	"\x12compressed_payload\x18\x06 \x01(\fH\x00R\x11compressedPayloadB\x06\n" +
	"\x04body\"I\n" +
	"\x12UncompressedEvents\x123\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.aepcaw.wtp.v1.CompactEventR\x06events\"\xa4\x02\n" +
	"\fCompactEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\x120\n" +
	"\x14timestamp_unix_nanos\x18\x03 \x01(\x04R\x12timestampUnixNanos\x12$\n" +
	"\x0eocsf_class_uid\x18\x04 \x01(\rR\focsfClassUid\x12(\n" +
	"\x10ocsf_activity_id\x18\x05 \x01(\rR\x0eocsfActivityId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12<\n" +
	"\tintegrity\x18\a \x01(\v2\x1e.aepcaw.wtp.v1.IntegrityRecordR\tintegrity\"\x80\x02\n" +
	"\x0fIntegrityRecord\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\rR\n" +
	"generation\x12\x1b\n" +
	"\tprev_hash\x18\x04 \x01(\tR\bprevHash\x12\x1d\n" +
	"\n" +
	"event_hash\x18\x05 \x01(\tR\teventHash\x12%\n" +
	"\x0econtext_digest\x18\x06 \x01(\tR\rcontextDigest\x12'\n" +
	"\x0fkey_fingerprint\x18\a \x01(\tR\x0ekeyFingerprint\"`\n" +
	"\tHeartbeat\x123\n" +
	"\x16wal_high_watermark_seq\x18\x01 \x01(\x04R\x13walHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\"f\n" +
	"\x0fServerHeartbeat\x123\n" +
	"\x16ack_high_watermark_seq\x18\x01 \x01(\x04R\x13ackHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\"_\n" +
	"\bBatchAck\x123\n" +
	"\x16ack_high_watermark_seq\x18\x01 \x01(\x04R\x13ackHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\"\xb1\x01\n" +
	"\rTransportLoss\x12#\n" +
	"\rfrom_sequence\x18\x01 \x01(\x04R\ffromSequence\x12\x1f\n" +
	"\vto_sequence\x18\x02 \x01(\x04R\n" +
	"toSequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\rR\n" +
	"generation\x12:\n" +
	"\x06reason\x18\x04 \x01(\x0e2\".aepcaw.wtp.v1.TransportLossReasonR\x06reason\"~\n" +
	"\x06Goaway\x12-\n" +
	"\x04code\x18\x01 \x01(\x0e2\x19.aepcaw.wtp.v1.GoawayCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11retry_immediately\x18\x03 \x01(\bR\x10retryImmediately\"M\n" +
	"\x0eClientShutdown\x12;\n" +
	"\x06reason\x18\x01 \x01(\x0e2#.aepcaw.wtp.v1.ClientShutdownReasonR\x06reason*o\n" +
	"\rHashAlgorithm\x12\x1e\n" +
	"\x1aHASH_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aHASH_ALGORITHM_HMAC_SHA256\x10\x01\x12\x1e\n" +
	"\x1aHASH_ALGORITHM_HMAC_SHA512\x10\x02*X\n" +
	"\n" +
	"UserSource\x12\x1b\n" +
	"\x17USER_SOURCE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_SOURCE_OS\x10\x01\x12\x19\n" +
	"\x15USER_SOURCE_TAILSCALE\x10\x02*l\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x01\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x02\x12\x14\n" +
	"\x10COMPRESSION_GZIP\x10\x03*\x93\x03\n" +
	"\x13TransportLossReason\x12%\n" +
	"!TRANSPORT_LOSS_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTRANSPORT_LOSS_REASON_OVERFLOW\x10\x01\x12(\n" +
	"$TRANSPORT_LOSS_REASON_CRC_CORRUPTION\x10\x02\x12(\n" +
	"$TRANSPORT_LOSS_REASON_MAPPER_FAILURE\x10\x03\x12(\n" +
	"$TRANSPORT_LOSS_REASON_INVALID_MAPPER\x10\x04\x12+\n" +
	"'TRANSPORT_LOSS_REASON_INVALID_TIMESTAMP\x10\x05\x12&\n" +
	"\"TRANSPORT_LOSS_REASON_INVALID_UTF8\x10\x06\x12+\n" +
	"'TRANSPORT_LOSS_REASON_SEQUENCE_OVERFLOW\x10\a\x121\n" +
	"-TRANSPORT_LOSS_REASON_ACK_REGRESSION_AFTER_GC\x10\b*\xc4\x01\n" +
	"\n" +
	"GoawayCode\x12\x1b\n" +
	"\x17GOAWAY_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14GOAWAY_CODE_DRAINING\x10\x01\x12\x18\n" +
	"\x14GOAWAY_CODE_OVERLOAD\x10\x02\x12\x17\n" +
	"\x13GOAWAY_CODE_UPGRADE\x10\x03\x12\x14\n" +
	"\x10GOAWAY_CODE_AUTH\x10\x04\x12\x16\n" +
	"\x12GOAWAY_CODE_POLICY\x10\x05\x12\x1e\n" +
	"\x1aGOAWAY_CODE_PROTOCOL_ERROR\x10\x06*\xab\x01\n" +
	"\x14ClientShutdownReason\x12&\n" +
	"\"CLIENT_SHUTDOWN_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCLIENT_SHUTDOWN_REASON_NORMAL\x10\x01\x12&\n" +
	"\"CLIENT_SHUTDOWN_REASON_RECONFIGURE\x10\x02\x12 \n" +
	"\x1cCLIENT_SHUTDOWN_REASON_FATAL\x10\x032V\n" +
	"\n" +
	"Watchtower\x12H\n" +
	"\x06Stream\x12\x1c.aepcaw.wtp.v1.ClientMessage\x1a\x1c.aepcaw.wtp.v1.ServerMessage(\x010\x01B@Z>github.com/thePM001/AEP-agent-element-protocol/AEP-CAW/proto/aepcaw/wtp/v1;wtpv1b\x06proto3"

var (
	file_aepcaw_wtp_v1_wtp_proto_rawDescOnce sync.Once
	file_aepcaw_wtp_v1_wtp_proto_rawDescData []byte
)

func file_aepcaw_wtp_v1_wtp_proto_rawDescGZIP() []byte {
	file_aepcaw_wtp_v1_wtp_proto_rawDescOnce.Do(func() {
		file_aepcaw_wtp_v1_wtp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_wtp_proto_rawDesc), len(file_aepcaw_wtp_v1_wtp_proto_rawDesc)))
	})
	return file_aepcaw_wtp_v1_wtp_proto_rawDescData
}

var file_aepcaw_wtp_v1_wtp_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_aepcaw_wtp_v1_wtp_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_aepcaw_wtp_v1_wtp_proto_goTypes = []any{
	(HashAlgorithm)(0),           // 0: aepcaw.wtp.v1.HashAlgorithm
	(UserSource)(0),              // 1: aepcaw.wtp.v1.UserSource
	(Compression)(0),             // 2: aepcaw.wtp.v1.Compression
	(TransportLossReason)(0),     // 3: aepcaw.wtp.v1.TransportLossReason
	(GoawayCode)(0),              // 4: aepcaw.wtp.v1.GoawayCode
	(ClientShutdownReason)(0),    // 5: aepcaw.wtp.v1.ClientShutdownReason
	(*ClientMessage)(nil),        // 6: aepcaw.wtp.v1.ClientMessage
	(*ServerMessage)(nil),        // 7: aepcaw.wtp.v1.ServerMessage
	(*SessionInit)(nil),          // 8: aepcaw.wtp.v1.SessionInit
	(*DecisionContext)(nil),      // 9: aepcaw.wtp.v1.DecisionContext
	(*SessionAck)(nil),           // 10: aepcaw.wtp.v1.SessionAck
	(*SessionUpdate)(nil),        // 11: aepcaw.wtp.v1.SessionUpdate
	(*PolicyPush)(nil),           // 12: aepcaw.wtp.v1.PolicyPush
	(*EventBatch)(nil),           // 13: aepcaw.wtp.v1.EventBatch
	(*UncompressedEvents)(nil),   // 14: aepcaw.wtp.v1.UncompressedEvents
	(*CompactEvent)(nil),         // 15: aepcaw.wtp.v1.CompactEvent
	(*IntegrityRecord)(nil),      // 16: aepcaw.wtp.v1.IntegrityRecord
	(*Heartbeat)(nil),            // 17: aepcaw.wtp.v1.Heartbeat
	(*ServerHeartbeat)(nil),      // 18: aepcaw.wtp.v1.ServerHeartbeat
	(*BatchAck)(nil),             // 19: aepcaw.wtp.v1.BatchAck
	(*TransportLoss)(nil),        // 20: aepcaw.wtp.v1.TransportLoss
	(*Goaway)(nil),               // 21: aepcaw.wtp.v1.Goaway
	(*ClientShutdown)(nil),       // 22: aepcaw.wtp.v1.ClientShutdown
	(*DecisionContext_User)(nil), // 23: aepcaw.wtp.v1.DecisionContext.User
	nil,                          // 24: aepcaw.wtp.v1.DecisionContext.ExtraEntry
}
var file_aepcaw_wtp_v1_wtp_proto_depIdxs = []int32{
	8,  // 0: aepcaw.wtp.v1.ClientMessage.session_init:type_name -> aepcaw.wtp.v1.SessionInit
	11, // 1: aepcaw.wtp.v1.ClientMessage.session_update:type_name -> aepcaw.wtp.v1.SessionUpdate
	13, // 2: aepcaw.wtp.v1.ClientMessage.event_batch:type_name -> aepcaw.wtp.v1.EventBatch
	17, // 3: aepcaw.wtp.v1.ClientMessage.heartbeat:type_name -> aepcaw.wtp.v1.Heartbeat
	20, // 4: aepcaw.wtp.v1.ClientMessage.transport_loss:type_name -> aepcaw.wtp.v1.TransportLoss
	22, // 5: aepcaw.wtp.v1.ClientMessage.shutdown:type_name -> aepcaw.wtp.v1.ClientShutdown
	10, // 6: aepcaw.wtp.v1.ServerMessage.session_ack:type_name -> aepcaw.wtp.v1.SessionAck
	19, // 7: aepcaw.wtp.v1.ServerMessage.batch_ack:type_name -> aepcaw.wtp.v1.BatchAck
	18, // 8: aepcaw.wtp.v1.ServerMessage.server_heartbeat:type_name -> aepcaw.wtp.v1.ServerHeartbeat
	21, // 9: aepcaw.wtp.v1.ServerMessage.goaway:type_name -> aepcaw.wtp.v1.Goaway
	11, // 10: aepcaw.wtp.v1.ServerMessage.server_update:type_name -> aepcaw.wtp.v1.SessionUpdate
	12, // 11: aepcaw.wtp.v1.ServerMessage.policy_push:type_name -> aepcaw.wtp.v1.PolicyPush
	0,  // 12: aepcaw.wtp.v1.SessionInit.algorithm:type_name -> aepcaw.wtp.v1.HashAlgorithm
	9,  // 13: aepcaw.wtp.v1.SessionInit.decision_context:type_name -> aepcaw.wtp.v1.DecisionContext
	23, // 14: aepcaw.wtp.v1.DecisionContext.user:type_name -> aepcaw.wtp.v1.DecisionContext.User
	24, // 15: aepcaw.wtp.v1.DecisionContext.extra:type_name -> aepcaw.wtp.v1.DecisionContext.ExtraEntry
	9,  // 16: aepcaw.wtp.v1.SessionUpdate.decision_context:type_name -> aepcaw.wtp.v1.DecisionContext
	2,  // 17: aepcaw.wtp.v1.EventBatch.compression:type_name -> aepcaw.wtp.v1.Compression
	14, // 18: aepcaw.wtp.v1.EventBatch.uncompressed:type_name -> aepcaw.wtp.v1.UncompressedEvents
	15, // 19: aepcaw.wtp.v1.UncompressedEvents.events:type_name -> aepcaw.wtp.v1.CompactEvent
	16, // 20: aepcaw.wtp.v1.CompactEvent.integrity:type_name -> aepcaw.wtp.v1.IntegrityRecord
	3,  // 21: aepcaw.wtp.v1.TransportLoss.reason:type_name -> aepcaw.wtp.v1.TransportLossReason
	4,  // 22: aepcaw.wtp.v1.Goaway.code:type_name -> aepcaw.wtp.v1.GoawayCode
	5,  // 23: aepcaw.wtp.v1.ClientShutdown.reason:type_name -> aepcaw.wtp.v1.ClientShutdownReason
	1,  // 24: aepcaw.wtp.v1.DecisionContext.User.source:type_name -> aepcaw.wtp.v1.UserSource
	6,  // 25: aepcaw.wtp.v1.Watchtower.Stream:input_type -> aepcaw.wtp.v1.ClientMessage
	7,  // 26: aepcaw.wtp.v1.Watchtower.Stream:output_type -> aepcaw.wtp.v1.ServerMessage
	26, // [26:27] is the sub-list for method output_type
	25, // [25:26] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_aepcaw_wtp_v1_wtp_proto_init() }
func file_aepcaw_wtp_v1_wtp_proto_init() {
	if File_aepcaw_wtp_v1_wtp_proto != nil {
		return
	}
	file_aepcaw_wtp_v1_wtp_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_SessionInit)(nil),
		(*ClientMessage_SessionUpdate)(nil),
		(*ClientMessage_EventBatch)(nil),
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_TransportLoss)(nil),
		(*ClientMessage_Shutdown)(nil),
	}
	file_aepcaw_wtp_v1_wtp_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_SessionAck)(nil),
		(*ServerMessage_BatchAck)(nil),
		(*ServerMessage_ServerHeartbeat)(nil),
		(*ServerMessage_Goaway)(nil),
		(*ServerMessage_ServerUpdate)(nil),
		(*ServerMessage_PolicyPush)(nil),
	}
	file_aepcaw_wtp_v1_wtp_proto_msgTypes[7].OneofWrappers = []any{
		(*EventBatch_Uncompressed)(nil),
		(*EventBatch_CompressedPayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_wtp_proto_rawDesc), len(file_aepcaw_wtp_v1_wtp_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aepcaw_wtp_v1_wtp_proto_goTypes,
		DependencyIndexes: file_aepcaw_wtp_v1_wtp_proto_depIdxs,
		EnumInfos:         file_aepcaw_wtp_v1_wtp_proto_enumTypes,
		MessageInfos:      file_aepcaw_wtp_v1_wtp_proto_msgTypes,
	}.Build()
	File_aepcaw_wtp_v1_wtp_proto = out.File
	file_aepcaw_wtp_v1_wtp_proto_goTypes = nil
	file_aepcaw_wtp_v1_wtp_proto_depIdxs = nil
}
