// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:e783bcf380141ed235701f2a324370511e07ab5fe37e2551a0d352f6e9fe9413
// crate: aep-envelope-wrap-disabled
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-012: wrap when lattice governance is disabled.

use anyhow::anyhow;
use std::fs;
use std::path::{Path, PathBuf};

pub const TICKET: &str = "AEP28-ENV-012";
pub const SKIP_NEEDLE: &str = "governance !== \"disabled\"";

fn extract_process_event(src: &str) -> String {
    let start = match src.find("async processEvent") {
        Some(v) => v,
        None => return String::new(),
    };
    src[start..].to_string()
}

fn extract_should_filter_block(src: &str) -> String {
    let body = extract_process_event(src);
    let start = match body.find("const shouldFilter") {
        Some(v) => v,
        None => return String::new(),
    };
    let rest = &body[start..];
    let end = rest.find("if (shouldFilter)").unwrap_or_else(|| rest.len().min(1200));
    rest[..end].to_string()
}

pub fn wrap_skip_needle_in_should_filter(bridge_source: &str) -> bool {
    let block = extract_should_filter_block(bridge_source);
    if block.is_empty() {
        return false;
    }
    block.contains(SKIP_NEEDLE)
}

pub fn wrap_on_disabled_governance(bridge_source: &str) -> Result<String, String> {
    let body = extract_process_event(bridge_source);
    if body.is_empty() {
        return Err(String::from("processEvent not found"));
    }
    if body.contains("filterCrossing") == false {
        return Err(String::from("processEvent never calls filterCrossing wrap"));
    }
    let block = extract_should_filter_block(bridge_source);
    if block.is_empty() {
        if body.contains("if (shouldFilter)") {
            return Err(String::from("shouldFilter used but assignment missing"));
        }
        return Ok(String::from("ok wrap on disabled governance"));
    }
    if wrap_skip_needle_in_should_filter(bridge_source) {
        return Err(String::from(
            "shouldFilter still skips the wrap when governance is disabled",
        ));
    }
    if body.contains("if (shouldFilter)") == false {
        return Err(String::from("shouldFilter wrap call missing"));
    }
    Ok(String::from("ok wrap on disabled governance"))
}

pub fn default_bridge_ts() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../AEP-SDKs/typescript/dynaep/src/bridge.ts")
}

pub fn run_gate(bridge: &Path) -> Result<i32, String> {
    if bridge.is_file() == false {
        return Err(format!("bridge source missing: {}", bridge.display()));
    }
    let src = fs::read_to_string(bridge).map_err(|e| e.to_string())?;
    let proof = wrap_on_disabled_governance(&src)?;
    println!("aep-envelope-wrap-disabled ok proof={}", proof);
    Ok(0)
}

fn err_msg(msg: String) -> anyhow::Error {
    anyhow!(msg)
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: wrap_on_disabled_governance domain:dynaep type:service
pub mod wrap_on_disabled_governance {
    use super::{err_msg, wrap_on_disabled_governance as scan_fn};
    use std::path::Path;

    pub struct WrapOnDisabledGovernance {
        pub bridge_source: String,
        pub scan: String,
    }

    impl WrapOnDisabledGovernance {
        pub fn new() -> Self {
            Self {
                bridge_source: String::new(),
                scan: String::new(),
            }
        }

        /// Fail if bridge.ts skips the wrap when lattice governance is disabled.
        pub fn process(&mut self) -> anyhow::Result<()> {
            let src = if self.bridge_source.is_empty() {
                String::new()
            } else if Path::new(&self.bridge_source).is_file() {
                std::fs::read_to_string(&self.bridge_source).map_err(anyhow::Error::msg)?
            } else {
                self.bridge_source.clone()
            };
            self.scan = scan_fn(&src).map_err(err_msg)?;
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn skip_src() -> String {
        String::from("class DynAEPBridge {
  async processEvent(event) {
    if (event.action_path && this.lattice) {
      const shouldFilter =
        governance !== \"disabled\" &&
        (agentSecurity || (governance !== \"ui_only\"));
      if (shouldFilter) {
        crossing = await this.hyperlatticeFilter.filterCrossing(latticeEvent, governance, node);
      }
    }
  }
}
")
    }

    fn good_or_src() -> String {
        String::from("class DynAEPBridge {
  async processEvent(event) {
    if (event.action_path && this.lattice) {
      const shouldFilter =
        governance === \"disabled\" ||
        agentSecurity ||
        (governance !== \"ui_only\");
      if (shouldFilter) {
        crossing = await this.hyperlatticeFilter.filterCrossing(latticeEvent, governance, node);
      }
    }
  }
}
")
    }

    #[test]
    fn skip_needle_fails_gate() {
        let src = skip_src();
        let err = wrap_on_disabled_governance(&src).unwrap_err();
        assert_eq!(err.contains("skips the wrap"), true);
        assert_eq!(wrap_skip_needle_in_should_filter(&src), true);
    }

    #[test]
    fn disabled_or_wrap_passes_gate() {
        let src = good_or_src();
        assert_eq!(wrap_on_disabled_governance(&src).is_ok(), true);
        assert_eq!(wrap_skip_needle_in_should_filter(&src), false);
    }

    #[test]
    fn tm15_init_needle_outside_should_filter_is_not_this_ticket() {
        let src = String::from("class DynAEPBridge {
  constructor() {
    if (governance !== \"disabled\") {
      throw new Error(\"init\");
    }
  }
  async processEvent(event) {
    const shouldFilter =
      governance === \"disabled\" || agentSecurity;
    if (shouldFilter) {
      await this.hyperlatticeFilter.filterCrossing(latticeEvent, governance, node);
    }
  }
}
");
        assert_eq!(wrap_on_disabled_governance(&src).is_ok(), true);
    }

    #[test]
    fn live_bridge_wraps_when_present() {
        let path = default_bridge_ts();
        if path.is_file() == false {
            return;
        }
        let src = fs::read_to_string(&path).unwrap_or_default();
        if src.is_empty() {
            return;
        }
        assert_eq!(wrap_on_disabled_governance(&src).is_ok(), true);
    }
}
