// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:7f6eb29fac57fc4450572d98316368025a841db3100e3f9cdd24db8400d79292
// crate: aep-admit-trust-floor
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-003: Fold per-node lattice trust floor into Admit walls on the same collect-all pass.

use aep_admit::{AdmitResult, AdmitWall};

pub use aep_admit::{
    clamp_unbound_trust_tier, compile_trust_floor_wall, fold_trust_floor_into_admit,
    trust_sufficient_from_admit, WALL_TRUST_FLOOR,
};

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: compile_trust_floor_wall domain:admit type:service
pub mod compile_trust_floor_wall_svc {
    use aep_admit::AdmitWall;

    pub struct CompileTrustFloorWall {
        pub trust_tier: u32,
        pub trust_floor: u32,
        pub wall: AdmitWall,
    }

    impl CompileTrustFloorWall {
        pub fn new() -> Self {
            Self {
                trust_tier: 1,
                trust_floor: 1,
                wall: AdmitWall::open(aep_admit::WALL_TRUST_FLOOR),
            }
        }

        /// Compile node trust floor versus agent trust tier into one Admit wall named trust_floor
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.wall = aep_admit::compile_trust_floor_wall(self.trust_tier, self.trust_floor);
            Ok(())
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: fold_trust_floor_into_admit domain:admit type:service
pub mod fold_trust_floor_into_admit_svc {
    use aep_admit::{AdmitResult, AdmitWall};

    pub struct FoldTrustFloorIntoAdmit {
        pub trust_tier: u32,
        pub trust_floor: u32,
        pub extra: Vec<AdmitWall>,
        pub result: AdmitResult,
    }

    impl FoldTrustFloorIntoAdmit {
        pub fn new() -> Self {
            Self {
                trust_tier: 1,
                trust_floor: 1,
                extra: Vec::new(),
                result: aep_admit::admit_collect_all(&[]),
            }
        }

        /// Fold the trust floor wall plus extra walls into one Admit collect-all pass
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.result = aep_admit::fold_trust_floor_into_admit(
                self.trust_tier,
                self.trust_floor,
                &self.extra,
            );
            Ok(())
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: trust_sufficient_from_admit domain:admit type:service
pub mod trust_sufficient_from_admit_svc {
    use aep_admit::AdmitResult;

    pub struct TrustSufficientFromAdmit {
        pub result: AdmitResult,
        pub sufficient: bool,
    }

    impl TrustSufficientFromAdmit {
        pub fn new() -> Self {
            Self {
                result: aep_admit::admit_collect_all(&[]),
                sufficient: true,
            }
        }

        /// Derive trust_sufficient from whether the trust_floor wall is closed
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.sufficient = aep_admit::trust_sufficient_from_admit(&self.result);
            Ok(())
        }
    }
}

/// Fold trust floor plus extra walls. Same closed set as aep-admit fold.
pub fn fold_trust_floor(trust_tier: u32, trust_floor: u32, extra: &[AdmitWall]) -> AdmitResult {
    aep_admit::fold_trust_floor_into_admit(trust_tier, trust_floor, extra)
}

#[cfg(test)]
mod tests {
    use super::*;
    use aep_admit::AdmitWall;

    #[test]
    fn service_compile_closes_below_floor() {
        let mut svc = compile_trust_floor_wall_svc::CompileTrustFloorWall::new();
        svc.trust_tier = 2;
        svc.trust_floor = 5;
        svc.process().expect("compile");
        assert_eq!(svc.wall.closed, true);
        assert_eq!(svc.wall.id, WALL_TRUST_FLOOR);
    }

    #[test]
    fn fold_keeps_trust_and_constraint_on_one_pass() {
        let extra = vec![AdmitWall::close(
            "constraint:required_field:alpha",
            "alpha required",
        )];
        let result = fold_trust_floor(1, 5, &extra);
        assert_eq!(result.allow, false);
        let ids: Vec<&str> = result.closed.iter().map(|w| w.id.as_str()).collect();
        assert_eq!(ids.contains(&WALL_TRUST_FLOOR), true);
        assert_eq!(ids.contains(&"constraint:required_field:alpha"), true);
        assert_eq!(trust_sufficient_from_admit(&result), false);
    }

    #[test]
    fn unbound_claim_cannot_raise_floor() {
        let claimed = clamp_unbound_trust_tier("", 9);
        let result = fold_trust_floor(claimed, 5, &[]);
        assert_eq!(result.allow, false);
        assert_eq!(trust_sufficient_from_admit(&result), false);
    }

    #[test]
    fn sufficient_service_reads_closed_set() {
        let mut fold = fold_trust_floor_into_admit_svc::FoldTrustFloorIntoAdmit::new();
        fold.trust_tier = 4;
        fold.trust_floor = 3;
        fold.process().expect("fold");
        let mut suf = trust_sufficient_from_admit_svc::TrustSufficientFromAdmit::new();
        suf.result = fold.result;
        suf.process().expect("sufficient");
        assert_eq!(suf.sufficient, true);
    }
}
