// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:919070fba02421bc02fbbc73fff8c01e5860c12d746bc8a04e47d69614cdddf8
// crate: aep-envelope-algebra-ci
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-010: CI gate against live OPA and live 15-step on action_path.

use anyhow::anyhow;
use std::fs;
use std::path::{Path, PathBuf};

pub const RESTRICTED_NEEDLES: &[&str] = &["package dynaep.lattice", "rego.restricted"];

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ScanHit {
    pub needle: String,
    pub line: usize,
}

fn extract_filter_crossing(src: &str) -> String {
    let start = match src.find("async filterCrossing") {
        Some(v) => v,
        None => return String::new(),
    };
    src[start..].to_string()
}

fn is_comment_line(line: &str) -> bool {
    let t = line.trim_start();
    t.starts_with("//") || t.starts_with('#') || t.starts_with('*') || t.starts_with("/*")
}

pub fn scan_restricted_source(source: &str) -> Vec<ScanHit> {
    let mut hits = Vec::new();
    for (idx, line) in source.lines().enumerate() {
        if is_comment_line(line) {
            continue;
        }
        for needle in RESTRICTED_NEEDLES {
            if line.contains(needle) {
                hits.push(ScanHit {
                    needle: (*needle).to_string(),
                    line: idx + 1,
                });
            }
        }
    }
    hits
}

pub fn format_hits(hits: &[ScanHit]) -> String {
    hits.iter()
        .map(|h| format!("{}:{}", h.line, h.needle))
        .collect::<Vec<_>>()
        .join(",")
}

pub fn live_opa_absent(filter_source: &str) -> Result<String, String> {
    let body = extract_filter_crossing(filter_source);
    if body.is_empty() {
        return Err(String::from("filterCrossing not found"));
    }
    if body.contains("latticePolicy.evaluate") || body.contains("evaluateLatticePolicyWithOpa") {
        return Err(String::from(
            "filterCrossing still calls live OPA evaluate on action_path",
        ));
    }
    Ok(String::from("ok live OPA absent on filterCrossing"))
}

pub fn live_15step_absent(filter_source: &str) -> Result<String, String> {
    let body = extract_filter_crossing(filter_source);
    if body.is_empty() {
        return Err(String::from("filterCrossing not found"));
    }
    if body.contains("runEvaluationChain")
        || body.contains("evaluationChain")
        || body.contains("step_00")
    {
        return Err(String::from(
            "filterCrossing still runs 15-step evaluator on action_path",
        ));
    }
    Ok(String::from("ok live 15-step absent on filterCrossing"))
}

pub fn restricted_rego_absent(source: &str) -> Result<String, String> {
    let hits = scan_restricted_source(source);
    if hits.is_empty() == false {
        return Err(format!(
            "restricted Rego subset still present: {}",
            format_hits(&hits)
        ));
    }
    Ok(String::from("ok restricted Rego subset absent"))
}

pub fn default_filter_ts() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../dynAEP/bridge/hyperlattice/HyperlatticeFilter.ts")
}

pub fn default_admit_js() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../admit/lib/admit.mjs")
}

pub fn default_admit_rs() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../admit/crate/src/lib.rs")
}

pub fn run_gate(filter: &Path, admit_js: &Path, admit_rs: &Path) -> Result<i32, String> {
    if filter.is_file() == false {
        return Ok(0);
    }
    if admit_js.is_file() == false {
        return Err(format!("admit.mjs missing: {}", admit_js.display()));
    }
    if admit_rs.is_file() == false {
        return Err(format!("aep-admit crate missing: {}", admit_rs.display()));
    }
    let filter_src = fs::read_to_string(filter).map_err(|e| e.to_string())?;
    let opa = live_opa_absent(&filter_src)?;
    let chain = live_15step_absent(&filter_src)?;
    let js_src = fs::read_to_string(admit_js).map_err(|e| e.to_string())?;
    let js = restricted_rego_absent(&js_src)?;
    let rs_src = fs::read_to_string(admit_rs).map_err(|e| e.to_string())?;
    let rs = restricted_rego_absent(&rs_src)?;
    println!(
        "aep-envelope-algebra-ci ok opa={} chain={} js={} rs={}",
        opa, chain, js, rs
    );
    Ok(0)
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: live_opa_absent domain:dynaep type:service
pub mod live_opa_absent {
    use super::*;

    pub struct LiveOpaAbsent {
        pub filter_source: String,
        pub scan: String,
    }

    impl LiveOpaAbsent {
        pub fn new() -> Self {
            Self {
                filter_source: String::new(),
                scan: String::new(),
            }
        }

        /// Fail CI if HyperlatticeFilter.filterCrossing still calls latticePolicy.evaluate on the live path
        pub fn process(&mut self) -> anyhow::Result<()> {
            if Path::new(&self.filter_source).is_file() == false && self.filter_source.contains('/') {
                self.scan = String::from("parked");
                return Ok(());
            }
            if Path::new(&self.filter_source).is_file() == false && self.filter_source.contains('/') {
                self.scan = String::from("parked");
                return Ok(());
            }
            let src = if self.filter_source.is_empty() {
                fs::read_to_string(default_filter_ts()).map_err(anyhow::Error::msg)?
            } else if Path::new(&self.filter_source).is_file() {
                fs::read_to_string(&self.filter_source).map_err(anyhow::Error::msg)?
            } else {
                self.filter_source.clone()
            };
            self.scan = live_opa_absent(&src).map_err(anyhow::Error::msg)?;
            Ok(())
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: live_15step_absent domain:dynaep type:service
pub mod live_15step_absent {
    use super::*;

    pub struct Live15stepAbsent {
        pub filter_source: String,
        pub scan: String,
    }

    impl Live15stepAbsent {
        pub fn new() -> Self {
            Self {
                filter_source: String::new(),
                scan: String::new(),
            }
        }

        /// Fail CI if HyperlatticeFilter.filterCrossing still calls runEvaluationChain on the live path
        pub fn process(&mut self) -> anyhow::Result<()> {
            if Path::new(&self.filter_source).is_file() == false && self.filter_source.contains('/') {
                self.scan = String::from("parked");
                return Ok(());
            }
            if Path::new(&self.filter_source).is_file() == false && self.filter_source.contains('/') {
                self.scan = String::from("parked");
                return Ok(());
            }
            let src = if self.filter_source.is_empty() {
                fs::read_to_string(default_filter_ts()).map_err(anyhow::Error::msg)?
            } else if Path::new(&self.filter_source).is_file() {
                fs::read_to_string(&self.filter_source).map_err(anyhow::Error::msg)?
            } else {
                self.filter_source.clone()
            };
            self.scan = live_15step_absent(&src).map_err(anyhow::Error::msg)?;
            Ok(())
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: restricted_rego_absent domain:admit type:service
pub mod restricted_rego_absent {
    use super::*;

    pub struct RestrictedRegoAbsent {
        pub source: String,
        pub scan: String,
    }

    impl RestrictedRegoAbsent {
        pub fn new() -> Self {
            Self {
                source: String::new(),
                scan: String::new(),
            }
        }

        /// Fail CI if admit.mjs or aep-admit re-grows a restricted Rego subset instead of compiled walls
        pub fn process(&mut self) -> anyhow::Result<()> {
            let src = if self.source.is_empty() {
                fs::read_to_string(default_admit_js()).map_err(anyhow::Error::msg)?
            } else if Path::new(&self.source).is_file() {
                fs::read_to_string(&self.source).map_err(anyhow::Error::msg)?
            } else {
                self.source.clone()
            };
            self.scan = restricted_rego_absent(&src).map_err(|e| anyhow!(e))?;
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn good_filter() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    const compiled = compileLatticePolicy(input);\n    const admit = admitCollectAll(walls);\n    const applied = admit.allow;\n    return { admit, applied };\n  }\n}\n"
    }

    fn opa_filter() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    const lattice_policy = this.latticePolicy.evaluate(policyInput);\n    return lattice_policy;\n  }\n}\n"
    }

    fn chain_filter() -> &'static str {
        "export class HyperlatticeFilter {\n  async filterCrossing(event) {\n    return runEvaluationChain(event);\n  }\n}\n"
    }

    #[test]
    fn live_opa_evaluate_fails_gate() {
        let err = live_opa_absent(opa_filter()).unwrap_err();
        assert_eq!(err.contains("live OPA"), true);
    }

    #[test]
    fn live_15step_runner_fails_gate() {
        let err = live_15step_absent(chain_filter()).unwrap_err();
        assert_eq!(err.contains("15-step"), true);
    }

    #[test]
    fn good_filter_passes_opa_and_chain() {
        assert_eq!(live_opa_absent(good_filter()).is_ok(), true);
        assert_eq!(live_15step_absent(good_filter()).is_ok(), true);
    }

    #[test]
    fn restricted_rego_source_fails() {
        let src = "package dynaep.lattice\nexport function admitCollectAll() {}\n";
        let err = restricted_rego_absent(src).unwrap_err();
        assert_eq!(err.contains("restricted Rego"), true);
    }

    #[test]
    fn comments_are_not_restricted_hits() {
        let src = "// package dynaep.lattice\nexport function admitCollectAll(walls) { return walls; }\n";
        assert_eq!(restricted_rego_absent(src).is_ok(), true);
    }

    #[test]
    fn live_filter_is_clean_when_present() {
        let path = default_filter_ts();
        if path.is_file() == false {
            return;
        }
        let src = fs::read_to_string(&path).unwrap_or_default();
        if src.is_empty() {
            return;
        }
        assert_eq!(live_opa_absent(&src).is_ok(), true);
        assert_eq!(live_15step_absent(&src).is_ok(), true);
    }

    #[test]
    fn live_admit_js_has_no_restricted_subset() {
        let path = default_admit_js();
        if path.is_file() == false {
            return;
        }
        let src = fs::read_to_string(&path).expect("read admit.mjs");
        assert_eq!(restricted_rego_absent(&src).is_ok(), true);
    }

    #[test]
    fn live_admit_rs_has_no_restricted_subset() {
        let path = default_admit_rs();
        if path.is_file() == false {
            return;
        }
        let src = fs::read_to_string(&path).expect("read aep-admit");
        assert_eq!(restricted_rego_absent(&src).is_ok(), true);
    }

    #[test]
    fn modules_process_synthetic_good_filter() {
        let mut opa = live_opa_absent::LiveOpaAbsent::new();
        opa.filter_source = good_filter().to_string();
        opa.process().unwrap();
        assert_eq!(opa.scan.contains("ok live OPA"), true);
        let mut chain = live_15step_absent::Live15stepAbsent::new();
        chain.filter_source = good_filter().to_string();
        chain.process().unwrap();
        assert_eq!(chain.scan.contains("ok live 15-step"), true);
        let mut rego = restricted_rego_absent::RestrictedRegoAbsent::new();
        rego.source = String::from("export function admitCollectAll(walls) { return walls; }\n");
        rego.process().unwrap();
        assert_eq!(rego.scan.contains("ok restricted"), true);
    }
}
