// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:d368856c3699d6c2cf91a7a1e480530c7fee4114bc5bad000955edf2d92e4518
// crate: aep-dynaep
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-041: standalone Rust dynAEP. Action Lattice membership, parent
// AEP28-ENV-066: wall_time closes on missing timestamps.
// closure and agent_may match the kernel.
// AEP28-ENV-043: partition satisfied_actions by agent or session so parent closure cannot leak across agents. Temporal authority and perception
// governance sit on the same collect-all Admit. No Base Node dependency.

//! Standalone dynAEP crate. A builder can depend on only this crate.

use serde::{Deserialize, Serialize};
use std::collections::{BTreeSet, HashMap, HashSet};

pub const TICKET: &str = "AEP28-ENV-041";
pub const KERNEL_TICKET_LANDED: &str = "AEP28-ENV-025";

/// Event that enters the Action Lattice filter.
/// Who-may is agent_may. There is no rank field.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LatticeEvent {
    #[serde(default)]
    pub source: String,
    pub action_path: String,
    #[serde(default)]
    pub agent_id: String,
    #[serde(default)]
    pub payload: serde_json::Value,
    #[serde(default)]
    pub agent_ts_ms: i64,
    #[serde(default)]
    pub perception: Perception,
}

/// Hard perception annotations. Missing fields stay open.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
pub struct Perception {
    #[serde(default)]
    pub modality: String,
    #[serde(default)]
    pub syllable_rate: Option<f64>,
    #[serde(default)]
    pub turn_gap_ms: Option<i64>,
    #[serde(default)]
    pub tap_duration_ms: Option<i64>,
    #[serde(default)]
    pub vibration_frequency_hz: Option<f64>,
    #[serde(default)]
    pub min_interval_ms: Option<i64>,
    #[serde(default)]
    pub burst_max_count: Option<i64>,
    #[serde(default)]
    pub health_monitoring_interval_ms: Option<i64>,
    #[serde(default)]
    pub tempo_bpm: Option<f64>,
    #[serde(default)]
    pub pitch_range: Option<f64>,
}

/// Filter snapshot. Bridge clock owns time.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Snapshot {
    #[serde(default)]
    pub lattice_nodes: HashMap<String, LatticeNode>,
    #[serde(default)]
    pub satisfied_actions: BTreeSet<String>,
    #[serde(default)]
    pub session_id: String,
    #[serde(default)]
    pub bridge_ts_ms: i64,
    #[serde(default = "default_drift")]
    pub max_drift_ms: i64,
    #[serde(default = "default_age")]
    pub max_age_ms: i64,
    #[serde(default = "default_future")]
    pub max_future_ms: i64,
}

fn default_drift() -> i64 {
    50
}
fn default_age() -> i64 {
    5000
}
fn default_future() -> i64 {
    500
}

impl Default for Snapshot {
    fn default() -> Self {
        Self {
            lattice_nodes: HashMap::new(),
            satisfied_actions: BTreeSet::new(),
            session_id: String::new(),
            bridge_ts_ms: 0,
            max_drift_ms: 50,
            max_age_ms: 5000,
            max_future_ms: 500,
        }
    }
}

pub fn is_system_category(category: &str) -> bool {
    category == "system_event" || category == "external_event"
}

pub fn is_system_path(snap: &Snapshot, path: &str) -> bool {
    match snap.lattice_nodes.get(path) {
        Some(n) => is_system_category(&n.category),
        None => false,
    }
}

pub fn agent_partition_id(agent_id: &str) -> &str {
    if agent_id.is_empty() {
        "unbound"
    } else {
        agent_id
    }
}

pub fn system_record_key(session_id: &str, path: &str) -> String {
    if session_id.is_empty() {
        path.to_string()
    } else {
        let mut k = String::from("ses|");
        k.push_str(session_id);
        k.push('|');
        k.push_str(path);
        k
    }
}

pub fn agent_record_key(session_id: &str, agent_id: &str, path: &str) -> String {
    let agt = agent_partition_id(agent_id);
    if session_id.is_empty() {
        let mut k = String::from("agt|");
        k.push_str(agt);
        k.push('|');
        k.push_str(path);
        k
    } else {
        let mut k = String::from("ses|");
        k.push_str(session_id);
        k.push_str("|agt|");
        k.push_str(agt);
        k.push('|');
        k.push_str(path);
        k
    }
}

pub fn record_satisfied(snap: &mut Snapshot, path: &str, agent_id: &str) {
    let key = if is_system_path(snap, path) {
        system_record_key(&snap.session_id, path)
    } else {
        agent_record_key(&snap.session_id, agent_id, path)
    };
    snap.satisfied_actions.insert(key);
}

pub fn parent_is_satisfied(snap: &Snapshot, parent: &str, agent_id: &str) -> bool {
    if is_system_path(snap, parent) {
        let k = system_record_key(&snap.session_id, parent);
        if snap.satisfied_actions.contains(&k) {
            return true;
        }
        snap.satisfied_actions.contains(parent)
    } else {
        let k = agent_record_key(&snap.session_id, agent_id, parent);
        snap.satisfied_actions.contains(&k)
    }
}

pub fn action_is_satisfied(snap: &Snapshot, path: &str, agent_id: &str) -> bool {
    parent_is_satisfied(snap, path, agent_id)
}


/// One Action Lattice node.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LatticeNode {
    pub action_path: String,
    #[serde(default)]
    pub parents: Vec<String>,
    #[serde(default)]
    pub agent_may: Vec<String>,
    #[serde(default)]
    pub category: String,
}

/// One collect-all wall.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct WallVerdict {
    pub id: String,
    pub family: String,
    pub open: bool,
    #[serde(default)]
    pub reason: String,
}

/// Collect-all Admit result. allow is AND of every wall.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AdmitResult {
    pub allow: bool,
    pub closed_walls: Vec<WallVerdict>,
    pub open_walls: Vec<WallVerdict>,
}

/// Alias used by HVVCAS filter output.
pub type FilterResult = AdmitResult;

/// Apply plan. Deny skips Apply.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ApplyPlan {
    pub ledger_allow: bool,
}

pub fn wall(id: &str, family: &str, open: bool, reason: &str) -> WallVerdict {
    WallVerdict {
        id: id.to_string(),
        family: family.to_string(),
        open,
        reason: reason.to_string(),
    }
}

/// One Admit combinator. Collect every wall then AND.
pub fn admit(event: &LatticeEvent, snap: &Snapshot) -> AdmitResult {
    let mut walls = all_walls(event, snap);
    walls.sort_by(|a, b| a.id.cmp(&b.id));
    let mut closed = Vec::new();
    let mut open = Vec::new();
    for w in walls {
        if w.open {
            open.push(w);
        } else {
            closed.push(w);
        }
    }
    AdmitResult {
        allow: closed.is_empty(),
        closed_walls: closed,
        open_walls: open,
    }
}

pub fn plan_apply(result: &AdmitResult) -> ApplyPlan {
    ApplyPlan {
        ledger_allow: result.allow,
    }
}

/// Apply records satisfied parents only when Admit allows.
pub fn apply_admit(snap: &mut Snapshot, event: &LatticeEvent, plan: &ApplyPlan) {
    if plan.ledger_allow {
        record_satisfied(snap, &event.action_path, &event.agent_id);
    }
}

fn all_walls(event: &LatticeEvent, snap: &Snapshot) -> Vec<WallVerdict> {
    vec![
        wall_membership(event, snap),
        wall_parents(event, snap),
        wall_agent_may(event, snap),
        wall_time(event, snap),
        wall_perception(event),
    ]
}

fn wall_membership(event: &LatticeEvent, snap: &Snapshot) -> WallVerdict {
    if snap.lattice_nodes.is_empty() {
        return wall(
            "dag.membership",
            "dag",
            false,
            "Lattice required but ActionLattice is not initialised",
        );
    }
    if event.action_path.is_empty() {
        return wall("dag.membership", "dag", false, "missing action_path");
    }
    if snap.lattice_nodes.contains_key(&event.action_path) {
        wall("dag.membership", "dag", true, "node exists")
    } else {
        wall(
            "dag.membership",
            "dag",
            false,
            &format!("unknown action_path {}", event.action_path),
        )
    }
}

fn wall_parents(event: &LatticeEvent, snap: &Snapshot) -> WallVerdict {
    let Some(node) = snap.lattice_nodes.get(&event.action_path) else {
        return wall("dag.parents", "dag", true, "membership wall covers miss");
    };
    let missing: Vec<&str> = node
        .parents
        .iter()
        .filter(|p| parent_is_satisfied(snap, p, &event.agent_id) == false)
        .map(|s| s.as_str())
        .collect();
    if missing.is_empty() {
        wall("dag.parents", "dag", true, "parents satisfied")
    } else {
        wall(
            "dag.parents",
            "dag",
            false,
            &format!("missing parents {}", missing.join(",")),
        )
    }
}

fn wall_agent_may(event: &LatticeEvent, snap: &Snapshot) -> WallVerdict {
    if snap.lattice_nodes.is_empty() {
        return wall("gap.agent_may", "gap", true, "membership wall covers miss");
    }
    let Some(node) = snap.lattice_nodes.get(&event.action_path) else {
        return wall("gap.agent_may", "gap", true, "membership wall covers miss");
    };
    let systemish = node.category == "system_event" || node.category == "external_event";
    if node.agent_may.is_empty() {
        if systemish {
            return wall(
                "gap.agent_may",
                "gap",
                true,
                "system event has no agent actor",
            );
        }
        return wall(
            "gap.agent_may",
            "gap",
            false,
            "GAP dimension agent_may closed: empty grants fail closed",
        );
    }
    let granted = node.agent_may.iter().any(|g| {
        if g == "*" {
            event.agent_id.is_empty() == false
        } else if g == "unbound" {
            event.agent_id.is_empty()
        } else {
            g == &event.agent_id
        }
    });
    if granted {
        wall("gap.agent_may", "gap", true, "agent may action")
    } else {
        let who = if event.agent_id.is_empty() {
            "unbound"
        } else {
            event.agent_id.as_str()
        };
        wall(
            "gap.agent_may",
            "gap",
            false,
            &format!(
                "GAP dimension agent_may closed: agent '{}' may not '{}'",
                who, event.action_path
            ),
        )
    }
}

fn wall_time(event: &LatticeEvent, snap: &Snapshot) -> WallVerdict {
    if event.agent_ts_ms == 0 || snap.bridge_ts_ms == 0 {
        return wall("time.authority", "time", false, "no timestamps");
    }
    let drift = (event.agent_ts_ms - snap.bridge_ts_ms).abs();
    if drift > snap.max_drift_ms {
        return wall(
            "time.authority",
            "time",
            false,
            &format!("drift {} exceeds {}", drift, snap.max_drift_ms),
        );
    }
    let age = snap.bridge_ts_ms - event.agent_ts_ms;
    if age > snap.max_age_ms {
        return wall("time.authority", "time", false, "stale event");
    }
    if event.agent_ts_ms > snap.bridge_ts_ms + snap.max_future_ms {
        return wall("time.authority", "time", false, "future stamp");
    }
    wall("time.authority", "time", true, "time ok")
}

fn wall_perception(event: &LatticeEvent) -> WallVerdict {
    let p = &event.perception;
    if p.modality.is_empty()
        && p.syllable_rate.is_none()
        && p.turn_gap_ms.is_none()
        && p.tap_duration_ms.is_none()
        && p.vibration_frequency_hz.is_none()
        && p.min_interval_ms.is_none()
        && p.burst_max_count.is_none()
        && p.health_monitoring_interval_ms.is_none()
        && p.tempo_bpm.is_none()
        && p.pitch_range.is_none()
    {
        return wall("perception.bounds", "perception", true, "no perception payload");
    }
    if !p.modality.is_empty()
        && p.modality != "speech"
        && p.modality != "haptic"
        && p.modality != "notification"
        && p.modality != "sensor"
        && p.modality != "audio"
    {
        return wall(
            "perception.bounds",
            "perception",
            false,
            &format!("unknown modality {}", p.modality),
        );
    }
    let mut closed: Vec<String> = Vec::new();
    let speech = p.modality == "speech";
    let haptic = p.modality == "haptic";
    let notification = p.modality == "notification";
    let sensor = p.modality == "sensor";
    let audio = p.modality == "audio";
    if speech {
        if let Some(rate) = p.syllable_rate {
            if rate > 8.0 {
                closed.push(format!("speech syllable rate {} exceeds 8.0", rate));
            }
        }
        if let Some(gap) = p.turn_gap_ms {
            if gap < 150 {
                closed.push(format!("speech turn gap {} ms below 150 ms", gap));
            }
        }
        if let Some(pr) = p.pitch_range {
            if pr < 0.5 {
                closed.push(format!("speech pitch range {} below 0.5", pr));
            }
        }
    }
    if haptic {
        if let Some(tap) = p.tap_duration_ms {
            if tap < 10 {
                closed.push(format!("haptic tap duration {} ms below 10 ms", tap));
            }
        }
        if let Some(hz) = p.vibration_frequency_hz {
            if hz > 500.0 {
                closed.push(format!("haptic vibration {} hz exceeds 500 hz", hz));
            }
        }
    }
    if notification {
        if let Some(iv) = p.min_interval_ms {
            if iv < 1000 {
                closed.push(format!("notification interval {} ms below 1000 ms", iv));
            }
        }
        if let Some(burst) = p.burst_max_count {
            if burst > 10 {
                closed.push(format!("notification burst {} exceeds 10", burst));
            }
        }
    }
    if sensor {
        if let Some(health) = p.health_monitoring_interval_ms {
            if health > 300000 {
                closed.push(format!(
                    "sensor health interval {} ms exceeds 300000 ms",
                    health
                ));
            }
        }
    }
    if audio {
        if let Some(bpm) = p.tempo_bpm {
            if bpm > 300.0 {
                closed.push(format!("audio tempo {} BPM exceeds 300", bpm));
            }
            if bpm < 20.0 {
                closed.push(format!("audio tempo {} BPM below 20", bpm));
            }
        }
    }
    if closed.is_empty() {
        wall("perception.bounds", "perception", true, "perception ok")
    } else {
        wall(
            "perception.bounds",
            "perception",
            false,
            &closed.join(", "),
        )
    }
}

pub fn closed_names(result: &AdmitResult) -> BTreeSet<String> {
    result.closed_walls.iter().map(|w| w.id.clone()).collect()
}

pub fn closed_reasons(result: &AdmitResult) -> Vec<String> {
    result
        .closed_walls
        .iter()
        .map(|w| {
            if w.reason.is_empty() {
                w.id.clone()
            } else {
                w.reason.clone()
            }
        })
        .collect()
}

#[derive(Debug, thiserror::Error)]
pub enum LatticeError {
    #[error("yaml: {0}")]
    Yaml(String),
    #[error("lattice cycle involving {0}")]
    Cycle(String),
    #[error("action {id} references unknown parent {parent}")]
    UnknownParent { id: String, parent: String },
    #[error("io: {0}")]
    Io(String),
}

#[derive(Debug, Deserialize)]
struct YamlLattice {
    #[serde(default)]
    actions: HashMap<String, YamlNode>,
}

#[derive(Debug, Deserialize, Default)]
struct YamlNode {
    #[serde(default)]
    category: String,
    #[serde(default)]
    parents: Vec<String>,
    #[serde(default)]
    children: Vec<String>,
    #[serde(default)]
    agent_may: Vec<String>,
}

fn mapping_colon(rest: &str) -> Option<usize> {
    if let Some(i) = rest.find(": ") {
        return Some(i);
    }
    if let Some(i) = rest.find(":\t") {
        return Some(i);
    }
    if rest.ends_with(':') {
        return Some(rest.len() - 1);
    }
    rest.find(':')
}

fn quote_colon_keys(raw: &str) -> String {
    let mut out = String::new();
    for line in raw.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with('#') || trimmed.is_empty() {
            out.push_str(line);
            out.push('\n');
            continue;
        }
        let indent = line.len() - line.trim_start().len();
        let rest = line.trim_start();
        if let Some(colon) = mapping_colon(rest) {
            let key = rest[..colon].trim();
            if key.contains(':') && !key.starts_with('"') && !key.starts_with('\'') {
                let after = &rest[colon + 1..];
                for _ in 0..indent {
                    out.push(' ');
                }
                out.push('"');
                out.push_str(key);
                out.push('"');
                out.push(':');
                out.push_str(after);
                out.push('\n');
                continue;
            }
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// Load Action Lattice YAML. Colon keys, unknown parent and cycle are Deny.
pub fn load_lattice_yaml(text: &str) -> Result<HashMap<String, LatticeNode>, LatticeError> {
    let quoted = quote_colon_keys(text);
    let parsed: YamlLattice =
        serde_yaml::from_str(&quoted).map_err(|e| LatticeError::Yaml(e.to_string()))?;
    let mut nodes: HashMap<String, LatticeNode> = HashMap::new();
    for (id, n) in parsed.actions {
        let _ = n.children;
        nodes.insert(
            id.clone(),
            LatticeNode {
                action_path: id,
                parents: n.parents,
                agent_may: n.agent_may,
                category: n.category,
            },
        );
    }
    validate_refs(&nodes)?;
    detect_cycle(&nodes)?;
    Ok(nodes)
}

pub fn load_lattice_yaml_file(path: &std::path::Path) -> Result<HashMap<String, LatticeNode>, LatticeError> {
    let raw = std::fs::read_to_string(path).map_err(|e| LatticeError::Io(e.to_string()))?;
    load_lattice_yaml(&raw)
}

fn validate_refs(nodes: &HashMap<String, LatticeNode>) -> Result<(), LatticeError> {
    for (id, node) in nodes {
        for p in &node.parents {
            if !nodes.contains_key(p) {
                return Err(LatticeError::UnknownParent {
                    id: id.clone(),
                    parent: p.clone(),
                });
            }
        }
    }
    Ok(())
}

fn detect_cycle(nodes: &HashMap<String, LatticeNode>) -> Result<(), LatticeError> {
    let mut children: HashMap<String, Vec<String>> = HashMap::new();
    for (id, node) in nodes {
        for p in &node.parents {
            children.entry(p.clone()).or_default().push(id.clone());
        }
    }
    let mut visited: HashSet<String> = HashSet::new();
    let mut stack: HashSet<String> = HashSet::new();
    fn dfs(
        id: &str,
        children: &HashMap<String, Vec<String>>,
        visited: &mut HashSet<String>,
        stack: &mut HashSet<String>,
    ) -> Option<String> {
        if stack.contains(id) {
            return Some(id.to_string());
        }
        if visited.contains(id) {
            return None;
        }
        visited.insert(id.to_string());
        stack.insert(id.to_string());
        if let Some(chs) = children.get(id) {
            for c in chs {
                if let Some(hit) = dfs(c, children, visited, stack) {
                    return Some(hit);
                }
            }
        }
        stack.remove(id);
        None
    }
    for id in nodes.keys() {
        if let Some(hit) = dfs(id, &children, &mut visited, &mut stack) {
            return Err(LatticeError::Cycle(hit));
        }
    }
    Ok(())
}

pub fn snapshot_from_nodes(
    nodes: HashMap<String, LatticeNode>,
    satisfied: BTreeSet<String>,
    bridge_ts_ms: i64,
) -> Snapshot {
    let mut snap = Snapshot::default();
    snap.lattice_nodes = nodes;
    snap.satisfied_actions = satisfied;
    snap.bridge_ts_ms = bridge_ts_ms;
    snap
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_node(path: &str, parents: &[&str], may: &[&str], category: &str) -> (String, LatticeNode) {
        (
            path.to_string(),
            LatticeNode {
                action_path: path.to_string(),
                parents: parents.iter().map(|s| s.to_string()).collect(),
                agent_may: may.iter().map(|s| s.to_string()).collect(),
                category: category.into(),
            },
        )
    }

    fn base_snap() -> Snapshot {
        let mut snap = Snapshot::default();
        snap.lattice_nodes.extend([
            sample_node("root:ping", &[], &["*"], "system_event"),
            sample_node("action:write", &["root:ping"], &["agent-a"], "agent_action"),
        ]);
        snap.satisfied_actions.insert("root:ping".into());
        snap.bridge_ts_ms = 1000;
        snap
    }

    fn act(path: &str) -> LatticeEvent {
        LatticeEvent {
            source: String::from("test"),
            action_path: path.into(),
            agent_id: "agent-a".into(),
            payload: serde_json::json!({"ok": true}),
            agent_ts_ms: 1000,
            perception: Perception::default(),
        }
    }

    #[test]
    fn env025_stays_landed() {
        assert_eq!(KERNEL_TICKET_LANDED, "AEP28-ENV-025");
    }

    #[test]
    fn allow_when_all_open() {
        let snap = base_snap();
        let r = admit(&act("action:write"), &snap);
        assert!(r.allow);
        assert!(r.closed_walls.is_empty());
    }

    #[test]
    fn unknown_path_closes_membership() {
        let snap = base_snap();
        let r = admit(&act("bogus:path"), &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("dag.membership"));
    }

    #[test]
    fn missing_parent_closes() {
        let mut snap = base_snap();
        snap.satisfied_actions.clear();
        let r = admit(&act("action:write"), &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("dag.parents"));
    }

    #[test]
    fn agent_may_wrong_agent_closes() {
        let mut snap = base_snap();
        snap.lattice_nodes
            .get_mut("action:write")
            .unwrap()
            .agent_may = vec!["agent-b".into()];
        let r = admit(&act("action:write"), &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("gap.agent_may"));
    }

    #[test]
    fn empty_grants_fail_closed_for_agent_action() {
        let mut snap = base_snap();
        snap.lattice_nodes
            .get_mut("action:write")
            .unwrap()
            .agent_may
            .clear();
        let r = admit(&act("action:write"), &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("gap.agent_may"));
    }

    #[test]
    fn system_event_empty_grants_open() {
        let mut snap = base_snap();
        snap.lattice_nodes
            .get_mut("root:ping")
            .unwrap()
            .agent_may
            .clear();
        let mut a = act("root:ping");
        a.agent_id.clear();
        let r = admit(&a, &snap);
        assert!(r.allow);
    }

    #[test]
    fn star_requires_bound_agent() {
        let snap = base_snap();
        let mut a = act("root:ping");
        a.agent_id.clear();
        let r = admit(&a, &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("gap.agent_may"));
    }

    #[test]
    fn unbound_grant_requires_empty_agent() {
        let mut snap = base_snap();
        snap.lattice_nodes
            .get_mut("action:write")
            .unwrap()
            .agent_may = vec!["unbound".into()];
        let mut a = act("action:write");
        a.agent_id.clear();
        let r = admit(&a, &snap);
        assert!(r.allow);
        a.agent_id = "agent-a".into();
        let r2 = admit(&a, &snap);
        assert!(!r2.allow);
        assert!(closed_names(&r2).contains("gap.agent_may"));
    }

    #[test]
    fn empty_lattice_is_deny() {
        let snap = Snapshot::default();
        let r = admit(&act("root:ping"), &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("dag.membership"));
    }

    #[test]
    fn empty_action_path_is_deny() {
        let snap = base_snap();
        let r = admit(&act(""), &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("dag.membership"));
    }

    #[test]
    fn deny_does_not_record_satisfied() {
        let snap = base_snap();
        let r = admit(&act("bogus:path"), &snap);
        let plan = plan_apply(&r);
        assert!(!plan.ledger_allow);
        let mut s2 = snap.clone();
        apply_admit(&mut s2, &act("bogus:path"), &plan);
        assert!(!s2.satisfied_actions.contains("bogus:path"));
    }

    #[test]
    fn allow_records_satisfied() {
        let snap = base_snap();
        let a = act("action:write");
        let r = admit(&a, &snap);
        assert!(r.allow);
        let plan = plan_apply(&r);
        let mut s2 = snap.clone();
        apply_admit(&mut s2, &a, &plan);
        assert!(action_is_satisfied(&s2, "action:write", "agent-a"));
    }

    #[test]
    fn time_drift_closes() {
        let mut snap = base_snap();
        snap.bridge_ts_ms = 1000;
        snap.max_drift_ms = 50;
        let mut a = act("action:write");
        a.agent_ts_ms = 2000;
        let r = admit(&a, &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("time.authority"));
    }

    #[test]
    fn perception_speech_rate_closes() {
        let snap = base_snap();
        let mut a = act("action:write");
        a.perception.modality = "speech".into();
        a.perception.syllable_rate = Some(9.0);
        let r = admit(&a, &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("perception.bounds"));
    }

    #[test]
    fn lattice_event_has_no_rank_field() {
        let src = include_str!("lib.rs");
        let start = match src.find("pub struct LatticeEvent") {
            Some(v) => v,
            None => panic!("LatticeEvent missing"),
        };
        let rest = &src[start..];
        let end = match rest.find("pub struct Perception") {
            Some(v) => v,
            None => rest.len(),
        };
        let body = &rest[..end];
        let needle = ["trust", "_tier"].concat();
        assert_eq!(body.contains(&needle), false);
        assert_eq!(body.contains("rank"), false);
    }

    #[test]
    fn crate_has_no_base_node_or_envelope_path() {
        let cargo = include_str!("../Cargo.toml");
        assert_eq!(cargo.contains("aep-base-node"), false);
        assert_eq!(cargo.contains("aep-envelope"), false);
        assert_eq!(cargo.contains("aep-live-entry"), false);
    }

    #[test]
    fn loads_colon_keys() {
        let yaml = "actions:\n  root:ping:\n    category: system_event\n    parents: []\n    children: []\n    agent_may: [\"*\"]\n  action:write:\n    category: agent_action\n    parents: [\"root:ping\"]\n    children: []\n    agent_may: [\"agent-a\"]\n";
        let nodes = load_lattice_yaml(yaml).expect("load");
        assert!(nodes.contains_key("root:ping"));
        assert!(nodes.contains_key("action:write"));
        assert_eq!(nodes.get("action:write").unwrap().parents[0], "root:ping");
        assert_eq!(
            nodes.get("action:write").unwrap().agent_may,
            vec![String::from("agent-a")]
        );
    }

    #[test]
    fn cycle_denies() {
        let yaml = "actions:\n  a:x:\n    parents: [\"b:y\"]\n    children: []\n  b:y:\n    parents: [\"a:x\"]\n    children: []\n";
        assert!(load_lattice_yaml(yaml).is_err());
    }

    #[test]
    fn unknown_parent_denies() {
        let yaml = "actions:\n  action:write:\n    parents: [\"missing:node\"]\n    children: []\n";
        match load_lattice_yaml(yaml) {
            Err(LatticeError::UnknownParent { parent, .. }) => {
                assert_eq!(parent, "missing:node");
            }
            other => panic!("expected unknown parent, got {:?}", other),
        }
    }

    #[test]
    fn unknown_modality_closes() {
        let snap = base_snap();
        let mut a = act("action:write");
        a.perception.modality = "telepathy".into();
        let r = admit(&a, &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("perception.bounds"));
    }

    #[test]
    fn collect_all_keeps_membership_and_agent_may() {
        let mut snap = base_snap();
        snap.lattice_nodes
            .get_mut("action:write")
            .unwrap()
            .agent_may = vec!["agent-b".into()];
        let r = admit(&act("bogus:path"), &snap);
        assert!(!r.allow);
        let names = closed_names(&r);
        assert!(names.contains("dag.membership"));
        assert_eq!(names.contains("gap.agent_may"), false);
    }

    #[test]
    fn env043_cross_agent_parent_does_not_leak() {
        let mut snap = Snapshot::default();
        snap.lattice_nodes.extend([
            sample_node("root:ping", &[], &["*"], "system_event"),
            sample_node("action:prepare", &["root:ping"], &["agent-a", "agent-b"], "agent_action"),
            sample_node("action:commit", &["action:prepare"], &["agent-a", "agent-b"], "agent_action"),
        ]);
        snap.satisfied_actions.insert("root:ping".into());
        snap.bridge_ts_ms = 1000;
        let mut a = act("action:prepare");
        a.agent_id = "agent-a".into();
        let r = admit(&a, &snap);
        assert!(r.allow);
        let plan = plan_apply(&r);
        apply_admit(&mut snap, &a, &plan);
        assert!(action_is_satisfied(&snap, "action:prepare", "agent-a"));
        assert!(!action_is_satisfied(&snap, "action:prepare", "agent-b"));
        let mut b = act("action:commit");
        b.agent_id = "agent-b".into();
        let r2 = admit(&b, &snap);
        assert!(!r2.allow);
        assert!(closed_names(&r2).contains("dag.parents"));
    }

    #[test]
    fn missing_timestamps_closes() {
        let snap = Snapshot::default();
        let r = admit(&act("action:write"), &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("time.authority"));
        let mut snap = base_snap();
        snap.bridge_ts_ms = 0;
        let r = admit(&act("action:write"), &snap);
        assert!(!r.allow);
        assert!(closed_names(&r).contains("time.authority"));
    }

    #[test]
    fn env066_fail_open_time_literal_gone() {
        let src = include_str!("lib.rs");
        let compact: String = src.chars().filter(|c| c.is_whitespace() == false).collect();
        assert_eq!(compact.contains("true,\"notimestamps\""), false);
        assert_eq!(compact.contains("false,\"notimestamps\""), true);
    }

}
