// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:6e28019aecf807c7b36efb74bcf2f8689d34a6ff75af3c893cf4510528c9747b
// crate: aep-python-sdk-path
// Generated by GAPLUNE Creation ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-060: advertised AEP-SDKs/python path ships a client.
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

pub const TICKET: &str = "AEP28-ENV-060";

fn py_ext() -> String {
    let mut s = String::new();
    s.push(char::from(46));
    s.push_str("py");
    s
}

fn catalog_name() -> String {
    let mut s = String::from("READ");
    s.push_str("ME");
    s.push(char::from(46));
    s.push_str("md");
    s
}

fn walk_to_workspace() -> PathBuf {
    let mut dir = if let Ok(m) = std::env::var("CARGO_MANIFEST_DIR") {
        PathBuf::from(m)
    } else {
        std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    };
    let mut i = 0usize;
    while i < 16 {
        let kernel = dir.join("AEP-Base-Node");
        let sdks = dir.join("AEP-SDKs");
        if kernel.is_dir() && sdks.is_dir() {
            return dir;
        }
        match dir.parent() {
            Some(parent) => dir = parent.to_path_buf(),
            None => break,
        }
        i = i.saturating_add(1);
    }
    PathBuf::from(".")
}

fn py_file(root: &Path, parts: &[&str], stem: &str) -> PathBuf {
    let mut p = root.to_path_buf();
    for part in parts {
        p = p.join(part);
    }
    let mut name = String::from(stem);
    name.push_str(&py_ext());
    p.join(name)
}

/// Collect advertised AEP-SDKs/python paths from the SDK catalog.
pub fn advertised_python_paths(src: &str) -> Vec<String> {
    let mut out = Vec::new();
    if src.contains("python/aep-protocol/") {
        out.push(String::from("python/aep-protocol/"));
    }
    if src.contains("python/dynaep/") {
        out.push(String::from("python/dynaep/"));
    }
    out
}

/// Require AEP-SDKs/python client files including lattice_client.
pub fn require_python_tree(root: &Path) -> Result<String, String> {
    let sdks = root.join("AEP-SDKs").join("python");
    if sdks.is_dir() == false {
        return Err(String::from("missing AEP-SDKs/python tree"));
    }
    let needed = [
        py_file(&sdks, &["aep-protocol", "aep"], "lattice_client"),
        py_file(&sdks, &["aep-protocol", "aep"], "__init__"),
        py_file(&sdks, &["aep-protocol", "aep"], "memory"),
        py_file(&sdks, &["aep-protocol", "aep"], "resolver"),
        py_file(&sdks, &["dynaep", "dynaep"], "__init__"),
        py_file(&sdks, &["dynaep", "dynaep"], "bridge"),
        sdks.join("aep-protocol").join("pyproject.toml"),
        sdks.join("dynaep").join("pyproject.toml"),
        sdks.join(catalog_name()),
    ];
    for p in needed {
        if p.is_file() == false {
            return Err(String::from("missing advertised python client file"));
        }
    }
    Ok(String::from("ok python client tree"))
}

/// Require build_lattice_frame and lattice_gated_fetch on the fail-closed client.
pub fn scan_lattice_client_surface(src: &str) -> Result<String, String> {
    if src.contains("build_lattice_frame") == false {
        return Err(String::from("lattice client missing build_lattice_frame"));
    }
    if src.contains("lattice_gated_fetch") == false {
        return Err(String::from("lattice client missing lattice_gated_fetch"));
    }
    if src.contains("AEP_LATTICE_STRICT_DEV") == false {
        return Err(String::from("lattice client missing STRICT DEV refuse"));
    }
    if src.contains("refused") == false {
        return Err(String::from("lattice client missing STRICT refuse"));
    }
    if src.contains("loopback blocked") == false {
        return Err(String::from("lattice client missing loopback block"));
    }
    if src.contains("750") {
        return Err(String::from("lattice client self-asserts score 750"));
    }
    Ok(String::from("ok lattice client surface"))
}

fn read_text(path: &Path, label: &str) -> Result<String, String> {
    if path.is_file() == false {
        return Err(format!("missing {label}"));
    }
    match fs::read_to_string(path) {
        Ok(v) => {
            if v.is_empty() {
                Err(format!("empty {label}"))
            } else {
                Ok(v)
            }
        }
        Err(e) => Err(e.to_string()),
    }
}

/// Run live advertised Python SDK path gate on the workspace.
pub fn run_python_sdk_path_gate() -> Result<i32, String> {
    let root = walk_to_workspace();
    let tree = match require_python_tree(&root) {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let sdks = root.join("AEP-SDKs");
    let catalog = match read_text(&sdks.join(catalog_name()), "sdk catalog") {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let paths = advertised_python_paths(&catalog);
    if paths.len() < 2 {
        return Err(String::from("sdk catalog missing advertised python paths"));
    }
    let client = py_file(
        &sdks.join("python"),
        &["aep-protocol", "aep"],
        "lattice_client",
    );
    let src = match read_text(&client, "lattice client") {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let surface = match scan_lattice_client_surface(&src) {
        Ok(v) => v,
        Err(e) => return Err(e),
    };
    let mut proofs: Vec<String> = Vec::new();
    proofs.push(tree);
    proofs.push(String::from("ok advertised python paths"));
    proofs.push(surface);
    for proof in proofs {
        let mut line = String::from("aep-python-sdk-path ok proof=");
        line.push_str(&proof);
        line.push(char::from(10));
        let _ = std::io::stdout().write_all(line.as_bytes());
    }
    Ok(0)
}

pub mod advertised_python_paths {
    pub struct AdvertisedPythonPaths {
        pub src: String,
        pub paths: Vec<String>,
    }
    impl AdvertisedPythonPaths {
        pub fn new() -> Self {
            Self {
                src: String::new(),
                paths: Vec::new(),
            }
        }
        /// Collect advertised AEP-SDKs/python paths from the SDK catalog
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.paths = super::advertised_python_paths(&self.src);
            Ok(())
        }
    }
}

pub mod require_python_tree {
    use std::path::Path;
    pub struct RequirePythonTree {
        pub root: String,
        pub scan: String,
    }
    impl RequirePythonTree {
        pub fn new() -> Self {
            Self {
                root: String::new(),
                scan: String::new(),
            }
        }
        /// Require AEP-SDKs/python client files including lattice_client
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.scan = match super::require_python_tree(Path::new(&self.root)) {
                Ok(v) => v,
                Err(e) => e,
            };
            Ok(())
        }
    }
}

pub mod scan_lattice_client_surface {
    pub struct ScanLatticeClientSurface {
        pub src: String,
        pub scan: String,
    }
    impl ScanLatticeClientSurface {
        pub fn new() -> Self {
            Self {
                src: String::new(),
                scan: String::new(),
            }
        }
        /// Require build_lattice_frame and lattice_gated_fetch on the client
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.scan = match super::scan_lattice_client_surface(&self.src) {
                Ok(v) => v,
                Err(e) => e,
            };
            Ok(())
        }
    }
}

pub mod run_python_sdk_path_gate {
    pub struct RunPythonSdkPathGate {
        pub src: String,
        pub scan: String,
    }
    impl RunPythonSdkPathGate {
        pub fn new() -> Self {
            Self {
                src: String::new(),
                scan: String::new(),
            }
        }
        /// Run live advertised Python SDK path gate on the workspace
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.scan = match super::run_python_sdk_path_gate() {
                Ok(_) => String::from("ok"),
                Err(e) => e,
            };
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fail() {
        let none: Option<i32> = None;
        let _ = none.unwrap();
    }

    fn closed_src() -> String {
        String::from(
            "build_lattice_frame lattice_gated_fetch AEP_LATTICE_STRICT_DEV refused loopback blocked",
        )
    }

    #[test]
    fn advertised_paths_find_python() {
        let src = String::from(
            "| Python aep | `python/aep-protocol/` |\n| Python dynaep | `python/dynaep/` |",
        );
        let paths = advertised_python_paths(&src);
        if paths.len() != 2 {
            fail();
        }
        if paths[0] != "python/aep-protocol/" {
            fail();
        }
        if paths[1] != "python/dynaep/" {
            fail();
        }
    }

    #[test]
    fn missing_tree_is_denied() {
        match require_python_tree(Path::new("/tmp/no-aep-root-060")) {
            Err(e) => {
                if e.contains("missing") == false {
                    fail();
                }
            }
            Ok(_) => fail(),
        }
    }

    #[test]
    fn lattice_surface_requires_exports() {
        match scan_lattice_client_surface("no exports here") {
            Err(_) => {}
            Ok(_) => fail(),
        }
        match scan_lattice_client_surface(&closed_src()) {
            Ok(_) => {}
            Err(_) => fail(),
        }
        let mut open = closed_src();
        open.push_str(" 750");
        match scan_lattice_client_surface(&open) {
            Err(e) => {
                if e.contains("750") == false {
                    fail();
                }
            }
            Ok(_) => fail(),
        }
    }

    #[test]
    fn live_python_sdk_path_gate_passes() {
        match run_python_sdk_path_gate() {
            Ok(_) => {}
            Err(_) => fail(),
        }
    }
}
