// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:fb547fc736705233e96ac6644016af64b89f49f2ca2b4b91fa7ddbc040fcd98b
// crate: aep-live-crossing-reject-copy
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// AEP28-ENV-015: live processEvent rejection is Admit collect-all walls then Apply.

use anyhow::anyhow;
use std::fs;
use std::path::{Path, PathBuf};

pub const TICKET: &str = "AEP28-ENV-015";
pub const BANNED: &str = "Admit then OPA";
pub const LIVE_COPY: &str = "Admit collect-all walls then Apply";

fn extract_process_event(src: &str) -> String {
    let start = match src.find("async processEvent") {
        Some(v) => v,
        None => return String::new(),
    };
    src[start..].to_string()
}

fn is_comment_line(line: &str) -> bool {
    let t = line.trim_start();
    if t.starts_with("//") || t.starts_with("/*") || t.starts_with("*/") {
        return true;
    }
    if let Some(rest) = t.strip_prefix('*') {
        return rest.is_empty() || rest.starts_with(' ') || rest.starts_with('/');
    }
    false
}

pub fn live_lines_contain(src: &str, needle: &str) -> bool {
    for line in src.lines() {
        if is_comment_line(line) {
            continue;
        }
        if line.contains(needle) {
            return true;
        }
    }
    false
}

pub fn live_reject_copy(bridge_source: &str) -> Result<String, String> {
    let body = extract_process_event(bridge_source);
    if body.is_empty() {
        return Err(String::from("processEvent not found"));
    }
    if live_lines_contain(&body, BANNED) {
        return Err(String::from(
            "live processEvent rejection still says Admit then OPA",
        ));
    }
    if live_lines_contain(&body, LIVE_COPY) == false {
        return Err(String::from(
            "live processEvent rejection missing Admit collect-all walls then Apply",
        ));
    }
    Ok(String::from("ok live reject copy"))
}

pub fn default_bridge_ts() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../AEP-SDKs/typescript/dynaep/src/bridge.ts")
}

pub fn run_gate(bridge: &Path) -> Result<i32, String> {
    if bridge.is_file() == false {
        return Err(format!("bridge source missing: {}", bridge.display()));
    }
    let src = fs::read_to_string(bridge).map_err(|e| e.to_string())?;
    let proof = live_reject_copy(&src)?;
    println!("aep-live-crossing-reject-copy ok proof={}", proof);
    Ok(0)
}

fn err_msg(msg: String) -> anyhow::Error {
    anyhow!(msg)
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: live_reject_copy domain:dynaep type:service
pub mod live_reject_copy {
    use super::{err_msg, live_reject_copy as scan_fn};
    use std::path::Path;

    pub struct LiveRejectCopy {
        pub bridge_source: String,
        pub scan: String,
    }

    impl LiveRejectCopy {
        pub fn new() -> Self {
            Self {
                bridge_source: String::new(),
                scan: String::new(),
            }
        }

        /// Fail if live processEvent rejection still says Admit then OPA. Live copy is Admit collect-all walls then Apply.
        pub fn process(&mut self) -> anyhow::Result<()> {
            let src = if self.bridge_source.is_empty() {
                String::new()
            } else if Path::new(&self.bridge_source).is_file() {
                std::fs::read_to_string(&self.bridge_source).map_err(anyhow::Error::msg)?
            } else {
                self.bridge_source.clone()
            };
            self.scan = scan_fn(&src).map_err(err_msg)?;
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn banned_src() -> String {
        String::from(
            "class DynAEPBridge {
  async processEvent(event) {
    if (!this.hyperlatticeFilter) {
      return this.createRejection(
        event.action_path,
        \"Live crossing requires HyperlatticeFilter (Admit then OPA). LatticeFilter is lab-only.\",
        event.timestamp,
      );
    }
  }
}
",
        )
    }

    fn good_src() -> String {
        String::from(
            "class DynAEPBridge {
  async processEvent(event) {
    if (!this.hyperlatticeFilter) {
      return this.createRejection(
        event.action_path,
        \"Live crossing requires HyperlatticeFilter (Admit collect-all walls then Apply). LatticeFilter is lab-only.\",
        event.timestamp,
      );
    }
  }
}
",
        )
    }

    fn comment_banned_src() -> String {
        String::from(
            "class DynAEPBridge {
  async processEvent(event) {
    // historical: Admit then OPA
    if (!this.hyperlatticeFilter) {
      return this.createRejection(
        event.action_path,
        \"Live crossing requires HyperlatticeFilter (Admit collect-all walls then Apply). LatticeFilter is lab-only.\",
        event.timestamp,
      );
    }
  }
}
",
        )
    }

    #[test]
    fn banned_live_reject_fails_gate() {
        let src = banned_src();
        let err = live_reject_copy(&src).unwrap_err();
        assert_eq!(err.contains("Admit then OPA"), true);
        assert_eq!(live_lines_contain(&src, BANNED), true);
    }

    #[test]
    fn aep28_live_copy_passes_gate() {
        let src = good_src();
        assert_eq!(live_reject_copy(&src).is_ok(), true);
        assert_eq!(live_lines_contain(&src, BANNED), false);
        assert_eq!(live_lines_contain(&src, LIVE_COPY), true);
    }

    #[test]
    fn commented_banned_phrase_does_not_fail_when_live_copy_present() {
        let src = comment_banned_src();
        assert_eq!(live_reject_copy(&src).is_ok(), true);
    }

    #[test]
    fn missing_live_copy_fails_gate() {
        let src = String::from(
            "class DynAEPBridge {
  async processEvent(event) {
    return this.createRejection(event.action_path, \"no filter\", event.timestamp);
  }
}
",
        );
        let err = live_reject_copy(&src).unwrap_err();
        assert_eq!(err.contains("missing Admit collect-all walls then Apply"), true);
    }

    #[test]
    fn live_bridge_reject_copy_when_present() {
        let path = default_bridge_ts();
        if path.is_file() == false {
            return;
        }
        let src = fs::read_to_string(&path).unwrap_or_default();
        if src.is_empty() {
            return;
        }
        assert_eq!(live_reject_copy(&src).is_ok(), true);
    }
}

