// The one writing rule reader for the JavaScript surfaces.
//
// The rule table itself is generated by the compiled wall set in the Rust admit
// crate and written to AEP-Components/admit/rules/writing-rules.json, so a
// JavaScript surface never carries a private copy of a writing rule. Every
// JavaScript surface that used to hold its own dash list, Oxford comma list or
// punctuation scan reads this module instead.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const TABLE_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "rules",
  "writing-rules.json",
);

let cachedRules = null;

export function writingRulesPath() {
  return TABLE_PATH;
}

/** The one rule table. Shape: id, wall_id, reason, detector, code_points, patterns. */
export function writingRuleTable() {
  if (cachedRules === null) {
    const parsed = JSON.parse(readFileSync(TABLE_PATH, "utf8"));
    cachedRules = parsed.rules ?? [];
  }
  return cachedRules;
}

export function writingRuleIds() {
  return writingRuleTable().map((rule) => rule.id);
}

export function writingRule(id) {
  const rule = writingRuleTable().find((entry) => entry.id === id);
  if (!rule) throw new Error(`unknown writing rule: ${id}`);
  return rule;
}

export function writingWallId(rule) {
  return `writing:${rule}`;
}

function hasCodePoint(text, points) {
  return (points ?? []).some((point) => text.includes(String.fromCodePoint(point)));
}

function hasPattern(text, patterns) {
  return (patterns ?? []).some((pattern) => pattern !== "" && text.includes(pattern));
}

/** Missing space after ? or ! before the next word, the kernel punctuation rule. */
export function punctuationWordSpaceClosed(text) {
  const chars = Array.from(String(text ?? ""));
  for (let i = 0; i < chars.length - 1; i += 1) {
    const ch = chars[i];
    const next = chars[i + 1];
    if ((ch === "?" || ch === "!") && /[A-Za-z0-9]/.test(next)) return true;
  }
  return false;
}

/** One verdict per rule, read from the table. */
export function writingRuleClosed(text, id) {
  const rule = writingRule(id);
  if (rule.detector === "punct_word_space") return punctuationWordSpaceClosed(text);
  return hasCodePoint(text, rule.code_points) || hasPattern(text, rule.patterns);
}

/** Closed walls for one text, in rule table order. */
export function compileWritingWalls(text) {
  const body = String(text ?? "");
  return writingRuleTable().map((rule) => ({
    id: rule.wall_id,
    closed: writingRuleClosed(body, rule.id),
    reason: rule.reason,
  }));
}

/** Violations for one text or for one line of a larger document. */
export function lintWritingRules(text) {
  const body = String(text ?? "");
  const violations = [];
  for (const rule of writingRuleTable()) {
    if (writingRuleClosed(body, rule.id) === false) continue;
    violations.push({ rule: rule.id, message: rule.reason, wall_id: rule.wall_id });
  }
  return violations;
}
