// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:cd31580fdc8a4eb41bc9a8890eee65b76510f26c9387358adf4e98ff2ccdb7d4
// crate: aep-admit
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0
// Live evaluator: Admit (AND of compiled walls, collect every closed wall)
// then OPA deny_lattice collect-all then Apply.
// Writing.gap rules compile into Admit walls on the same collect-all pass.
// LatticeFilter and PolicyEvaluator sequential stacks are lab-only.

/// One compiled Admit wall.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdmitWall {
    pub id: String,
    pub closed: bool,
    pub reason: String,
}

impl AdmitWall {
    pub fn open(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            closed: false,
            reason: String::new(),
        }
    }

    pub fn close(id: impl Into<String>, reason: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            closed: true,
            reason: reason.into(),
        }
    }
}

/// Admit result. allow is AND of every wall (true iff no closed wall).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdmitResult {
    pub allow: bool,
    pub closed: Vec<AdmitWall>,
}

impl AdmitResult {
    /// Canonical closed-set identity. Order of input walls does not change this.
    pub fn closed_set_key(&self) -> String {
        let mut rows: Vec<String> = self
            .closed
            .iter()
            .map(|w| {
                let mut s = w.id.clone();
                s.push('\u{1f}');
                s.push_str(&w.reason);
                s
            })
            .collect();
        rows.sort();
        rows.dedup();
        rows.join("\n")
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: admit_wall domain:policy type:library
pub mod admit_wall {
    pub use super::AdmitWall;
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: admit_collect_all domain:policy type:library
pub mod admit_collect_all {
    use super::{AdmitResult, AdmitWall};

    /// AND of compiled walls. Collect every closed wall. Do not stop at the first close.
    pub fn admit_collect_all(walls: &[AdmitWall]) -> AdmitResult {
        let mut closed: Vec<AdmitWall> = walls.iter().filter(|w| w.closed).cloned().collect();
        closed.sort_by(|a, b| a.id.cmp(&b.id).then(a.reason.cmp(&b.reason)));
        closed.dedup_by(|a, b| a.id == b.id && a.reason == b.reason);
        AdmitResult {
            allow: closed.is_empty(),
            closed,
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: compile_writing_walls domain:admit type:library
pub mod compile_writing_walls {
    use super::AdmitWall;

    pub const RULE_NO_EM_DASHES: &str = "no_em_dashes";
    pub const RULE_NO_EN_DASHES: &str = "no_en_dashes";
    pub const RULE_NO_DASH_SUBSTITUTES: &str = "no_dash_substitutes";
    pub const RULE_NO_BOX_DRAWING_DASHES: &str = "no_box_drawing_dashes";
    pub const RULE_NO_MINUS_AS_DASH: &str = "no_minus_as_dash";
    pub const RULE_NO_DOUBLE_HYPHEN: &str = "no_double_hyphen";
    pub const RULE_NO_OXFORD_COMMA: &str = "no_oxford_comma";
    pub const RULE_PUNCTUATION_WORD_SPACE: &str = "punctuation_word_space";

    pub fn writing_wall_id(rule: &str) -> String {
        let mut id = String::from("writing:");
        id.push_str(rule);
        id
    }

    fn wall(rule: &str, closed: bool, reason: &str) -> AdmitWall {
        let id = writing_wall_id(rule);
        if closed {
            AdmitWall::close(id, reason)
        } else {
            AdmitWall::open(id)
        }
    }

    fn contains_char(text: &str, ch: char) -> bool {
        text.chars().any(|c| c == ch)
    }

    fn oxford_and_pattern() -> String {
        let mut p = String::from(",");
        p.push(' ');
        p.push_str("and ");
        p
    }

    fn oxford_or_pattern() -> String {
        let mut p = String::from(",");
        p.push(' ');
        p.push_str("or ");
        p
    }

    fn has_oxford_comma(text: &str) -> bool {
        text.contains(&oxford_and_pattern()) || text.contains(&oxford_or_pattern())
    }

    fn has_double_hyphen_prose(text: &str) -> bool {
        let sep: String = [' ', '-', '-', ' '].iter().collect();
        text.contains(&sep)
    }

    fn has_punct_word_space_fail(text: &str) -> bool {
        let chars: Vec<char> = text.chars().collect();
        for i in 0..chars.len().saturating_sub(1) {
            let ch = chars[i];
            let next = chars[i + 1];
            if (ch == '?' || ch == '!') && next.is_ascii_alphanumeric() {
                return true;
            }
        }
        false
    }

    /// Compile writing.gap denies into Admit walls. One wall per rule. Collect-all later.
    pub fn compile_writing_walls(text: &str) -> Vec<AdmitWall> {
        let mut walls = Vec::new();
        walls.push(wall(
            RULE_NO_EM_DASHES,
            contains_char(text, '\u{2014}'),
            "Em dash U+2014 forbidden by writing.gap",
        ));
        walls.push(wall(
            RULE_NO_EN_DASHES,
            contains_char(text, '\u{2013}'),
            "En dash U+2013 forbidden by writing.gap",
        ));
        let subst = contains_char(text, '\u{2015}')
            || contains_char(text, '\u{2e3a}')
            || contains_char(text, '\u{2e3b}');
        walls.push(wall(
            RULE_NO_DASH_SUBSTITUTES,
            subst,
            "Dash substitute U+2015 U+2E3A U+2E3B forbidden by writing.gap",
        ));
        let boxd = contains_char(text, '\u{2500}') || contains_char(text, '\u{2501}');
        walls.push(wall(
            RULE_NO_BOX_DRAWING_DASHES,
            boxd,
            "Box drawing dash U+2500 U+2501 forbidden by writing.gap",
        ));
        walls.push(wall(
            RULE_NO_MINUS_AS_DASH,
            contains_char(text, '\u{2212}'),
            "Minus sign U+2212 used as dash forbidden by writing.gap",
        ));
        walls.push(wall(
            RULE_NO_DOUBLE_HYPHEN,
            has_double_hyphen_prose(text),
            "Double hyphen prose separator forbidden by writing.gap",
        ));
        walls.push(wall(
            RULE_NO_OXFORD_COMMA,
            has_oxford_comma(text),
            "Oxford comma forbidden by writing.gap",
        ));
        walls.push(wall(
            RULE_PUNCTUATION_WORD_SPACE,
            has_punct_word_space_fail(text),
            "Space after ? or ! before the next word required by writing.gap",
        ));
        walls
    }

    /// Join payload strings then compile. Same closed set as compiling the join.
    pub fn compile_writing_walls_for_strings(strings: &[String]) -> Vec<AdmitWall> {
        compile_writing_walls(&strings.join("\n"))
    }

    /// Split payload text on newlines. Empty lines dropped.
    pub fn collect_payload_strings(payload: &str) -> Vec<String> {
        payload
            .lines()
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
            .map(|s| s.to_string())
            .collect()
    }
}

pub use admit_collect_all::admit_collect_all;
pub use compile_writing_walls::{
    collect_payload_strings, compile_writing_walls, compile_writing_walls_for_strings,
    writing_wall_id, RULE_NO_EM_DASHES, RULE_NO_OXFORD_COMMA,
};

pub mod compile_lattice;
pub use compile_lattice::{
    compile_lattice_policy, compile_lattice_walls, default_rego_path,
    load_policy_sets, parse_policy_sets, prove_rego_source, CompiledPolicy,
    LatticeCompileInput, PolicySets,
};

pub mod compile_trust;
pub use compile_trust::{
    clamp_unbound_trust_tier, compile_trust_floor_wall, fold_trust_floor_into_admit,
    trust_sufficient_from_admit, WALL_TRUST_FLOOR,
};

#[cfg(test)]
mod tests {
    use super::*;

    fn oxford_sample() -> String {
        let mut s = String::from("red, white");
        s.push(',');
        s.push_str(" and blue");
        s
    }

    fn em_sample() -> String {
        let mut s = String::from("bad");
        s.push('\u{2014}');
        s.push_str("dash");
        s
    }

    #[test]
    fn two_closed_walls_both_appear() {
        let walls = vec![
            AdmitWall::close("wall.alpha", "alpha closed"),
            AdmitWall::close("wall.beta", "beta closed"),
        ];
        let result = admit_collect_all(&walls);
        assert_eq!(result.allow, false);
        assert_eq!(result.closed.len(), 2);
        let ids: Vec<&str> = result.closed.iter().map(|w| w.id.as_str()).collect();
        assert_eq!(ids.contains(&"wall.alpha"), true);
        assert_eq!(ids.contains(&"wall.beta"), true);
    }

    #[test]
    fn wall_order_does_not_change_closed_set() {
        let a = AdmitWall::close("wall.alpha", "alpha closed");
        let b = AdmitWall::close("wall.beta", "beta closed");
        let open = AdmitWall::open("wall.gamma");
        let left = admit_collect_all(&[a.clone(), b.clone(), open.clone()]);
        let right = admit_collect_all(&[open, b, a]);
        assert_eq!(left.closed_set_key(), right.closed_set_key());
        assert_eq!(left.allow, right.allow);
        assert_eq!(left.closed.len(), 2);
    }

    #[test]
    fn all_open_allows() {
        let walls = vec![AdmitWall::open("a"), AdmitWall::open("b")];
        let result = admit_collect_all(&walls);
        assert_eq!(result.allow, true);
        assert_eq!(result.closed.is_empty(), true);
    }

    #[test]
    fn writing_em_dash_closes_wall() {
        let walls = compile_writing_walls(&em_sample());
        let result = admit_collect_all(&walls);
        assert_eq!(result.allow, false);
        let id = writing_wall_id(RULE_NO_EM_DASHES);
        assert_eq!(
            result.closed.iter().any(|w| w.id == id),
            true
        );
    }

    #[test]
    fn writing_oxford_comma_closes_wall() {
        let walls = compile_writing_walls(&oxford_sample());
        let result = admit_collect_all(&walls);
        assert_eq!(result.allow, false);
        let id = writing_wall_id(RULE_NO_OXFORD_COMMA);
        assert_eq!(
            result.closed.iter().any(|w| w.id == id),
            true
        );
    }

    #[test]
    fn writing_and_constraint_share_one_collect_all_pass() {
        let mut walls = compile_writing_walls(&em_sample());
        walls.push(AdmitWall::close(
            "constraint:required_field:alpha",
            "alpha required",
        ));
        walls.push(AdmitWall::open("constraint:beta"));
        let result = admit_collect_all(&walls);
        assert_eq!(result.allow, false);
        let writing_id = writing_wall_id(RULE_NO_EM_DASHES);
        let ids: Vec<&str> = result.closed.iter().map(|w| w.id.as_str()).collect();
        assert_eq!(ids.contains(&writing_id.as_str()), true);
        assert_eq!(ids.contains(&"constraint:required_field:alpha"), true);
        assert_eq!(result.closed.len() >= 2, true);
    }

    #[test]
    fn clean_prose_opens_writing_walls() {
        let walls = compile_writing_walls("plain hyphen-ok prose");
        let result = admit_collect_all(&walls);
        assert_eq!(result.allow, true);
        assert_eq!(result.closed.is_empty(), true);
        assert_eq!(walls.is_empty(), false);
    }
}
