version: 1
id: dirtyfrag-conservative
title: Dirty Frag conservative mitigation
references:
  - https://www.openwall.com/lists/oss-security/2026/05/07/8

seccomp:
  socket_rules:
    - name: dirtyfrag-conservative-rxrpc
      family: AF_RXRPC
      action: log_and_kill
    - name: dirtyfrag-conservative-xfrm
      family: AF_NETLINK
      protocol: NETLINK_XFRM
      action: log_and_kill
