// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:ddc268f216c624cd04055c3a8fed5c8ed0f08b2e2bbb97374bd4963f4fe8e060
// crate: aep-base-node-pulse
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
use std::collections::HashSet;
use std::fs;
use std::io::Write;
use std::path::PathBuf;
pub const TICKET: &str = "AEP28-ENV-065";
pub const PARENT_TICKET_ENV066: &str = "AEP28-ENV-066";
pub const TICKET_ENV074: &str = "AEP28-ENV-074";
pub const PULSE_MS: i64 = 1000;
pub const MAX_DRIFT_MS: i64 = 50;
pub const MAX_AGE_MS: i64 = 5000;
pub const MAX_FRAME_AGE_SECS: u64 = 300;
pub const MAX_FRAME_FUTURE_SKEW_SECS: u64 = 60;
pub const QUEUE_CAP_CAPSULES: usize = 256;
pub const QUEUE_CAP_BYTES: usize = 262144;
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FrozenSnapshot { pub bridge_ts_ms: i64, pub max_drift_ms: i64, pub max_age_ms: i64, pub epoch_id: u64 }
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct QueuedCapsule { pub digest: String, pub agent_id: String, pub sequence_number: i64, pub byte_len: usize, pub freeze: FrozenSnapshot }
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EnqueueDeny { OverflowCapsules, OverflowBytes, DuplicateDigest }
impl EnqueueDeny {
    pub fn as_str(&self) -> &'static str {
        match self {
            EnqueueDeny::OverflowCapsules => "pulse queue overflow capsules",
            EnqueueDeny::OverflowBytes => "pulse queue overflow bytes",
            EnqueueDeny::DuplicateDigest => "frame replay rejected",
        }
    }
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CapsuleFate { Ready, Wait, Aged }
#[derive(Clone, Debug, Default)]
pub struct BeatRelease { pub ready: Vec<QueuedCapsule>, pub aged: Vec<QueuedCapsule>, pub epoch_id: u64 }
#[derive(Debug, Default)]
pub struct PulseQueue { items: Vec<QueuedCapsule>, bytes: usize, epoch: u64, queued_digests: HashSet<String> }
pub fn freeze_temporal_snapshot(bridge_ts_ms: i64, epoch_id: u64) -> FrozenSnapshot {
    FrozenSnapshot { bridge_ts_ms, max_drift_ms: MAX_DRIFT_MS, max_age_ms: MAX_AGE_MS, epoch_id }
}
pub fn drift_against_freeze(agent_ts_ms: i64, freeze: &FrozenSnapshot) -> i64 { (agent_ts_ms - freeze.bridge_ts_ms).abs() }
pub fn age_against_freeze(agent_ts_ms: i64, freeze: &FrozenSnapshot) -> i64 { freeze.bridge_ts_ms.saturating_sub(agent_ts_ms) }
pub fn hold_age_ms(now_ms: i64, freeze: &FrozenSnapshot) -> i64 { now_ms.saturating_sub(freeze.bridge_ts_ms) }
pub fn fate_at(now_ms: i64, freeze: &FrozenSnapshot) -> CapsuleFate {
    let held = hold_age_ms(now_ms, freeze);
    if held > MAX_AGE_MS { return CapsuleFate::Aged; }
    if held >= PULSE_MS { return CapsuleFate::Ready; }
    CapsuleFate::Wait
}
impl PulseQueue {
    pub fn new() -> Self { Self::default() }
    pub fn len(&self) -> usize { self.items.len() }
    pub fn bytes(&self) -> usize { self.bytes }
    pub fn epoch_id(&self) -> u64 { self.epoch }
    pub fn is_empty(&self) -> bool { self.items.is_empty() }
    pub fn enqueue(&mut self, cap: QueuedCapsule) -> Result<(), EnqueueDeny> {
        if self.queued_digests.contains(&cap.digest) { return Err(EnqueueDeny::DuplicateDigest); }
        if self.items.len() >= QUEUE_CAP_CAPSULES { return Err(EnqueueDeny::OverflowCapsules); }
        let next = self.bytes.saturating_add(cap.byte_len);
        if next > QUEUE_CAP_BYTES { return Err(EnqueueDeny::OverflowBytes); }
        self.queued_digests.insert(cap.digest.clone());
        self.bytes = next;
        self.items.push(cap);
        Ok(())
    }
    pub fn beat(&mut self, now_ms: i64) -> BeatRelease {
        self.epoch = self.epoch.saturating_add(1);
        let epoch_id = self.epoch;
        let mut stay: Vec<QueuedCapsule> = Vec::new();
        let mut aged: Vec<QueuedCapsule> = Vec::new();
        let mut candidates: Vec<QueuedCapsule> = Vec::new();
        for cap in self.items.drain(..) {
            match fate_at(now_ms, &cap.freeze) {
                CapsuleFate::Aged => aged.push(cap),
                CapsuleFate::Ready => candidates.push(cap),
                CapsuleFate::Wait => stay.push(cap),
            }
        }
        let mut ready: Vec<QueuedCapsule> = Vec::new();
        for cap in candidates {
            let lower_still_queued = stay.iter().any(|o| o.agent_id == cap.agent_id && o.sequence_number < cap.sequence_number);
            if lower_still_queued { stay.push(cap); } else { ready.push(cap); }
        }
        ready.sort_by(|a, b| match a.agent_id.cmp(&b.agent_id) {
            std::cmp::Ordering::Equal => a.sequence_number.cmp(&b.sequence_number),
            other => other,
        });
        self.bytes = stay.iter().map(|c| c.byte_len).sum();
        self.queued_digests = stay.iter().map(|c| c.digest.clone()).collect();
        self.items = stay;
        BeatRelease { ready, aged, epoch_id }
    }
}
fn compact(src: &str) -> String { src.chars().filter(|c| c.is_whitespace() == false).collect() }
fn strip_line_comments(src: &str) -> String {
    let mut out = String::new();
    for line in src.lines() {
        if let Some(i) = line.find("//") { out.push_str(&line[..i]); } else { out.push_str(line); }
        out.push('\n');
    }
    out
}
fn extract_fn(src: &str, needle: &str) -> String {
    let start = match src.find(needle) { Some(v) => v, None => return String::new() };
    let rest = &src[start..];
    let brace = match rest.find('{') { Some(v) => v, None => return String::new() };
    let bytes = rest.as_bytes();
    let mut i = brace; let mut depth: i32 = 0;
    while i < bytes.len() {
        if bytes[i] == b'{' { depth += 1; } else if bytes[i] == b'}' {
            depth -= 1; if depth == 0 { return rest[..=i].to_string(); }
        }
        i += 1;
    }
    String::new()
}
pub fn scan_docking_pulse_owner(src: &str) -> Result<String, String> {
    let code = compact(&strip_line_comments(src));
    if code.contains("aep_base_node_pulse") == false { return Err(String::from("docking.rs is not the Base Node pulse owner")); }
    if code.contains("pulse_beat") == false { return Err(String::from("docking.rs has no pulse beat")); }
    let handle = extract_fn(src, "fn handle_frame");
    if handle.is_empty() { return Err(String::from("handle_frame not found")); }
    let h = compact(&strip_line_comments(&handle));
    let admit_at = h.find("admit_sealed_payload_on_live_dock");
    let enq_at = h.find("pulse_enqueue");
    match (admit_at, enq_at) {
        (Some(a), Some(e)) if a < e => Err(String::from("handle_frame still Admits before enqueue")),
        (Some(_), None) => Err(String::from("handle_frame still Admits immediately")),
        (None, None) => Err(String::from("handle_frame has no pulse enqueue")),
        _ => Ok(String::from("ok docking.rs owns the pulse")),
    }
}
pub fn scan_dynaep_not_pulse_owner(src: &str) -> Result<String, String> {
    let code = compact(&strip_line_comments(src));
    if code.contains("QUEUE_CAP_CAPSULES") || code.contains("QUEUE_CAP_BYTES") || code.contains("PulseQueue") {
        return Err(String::from("aep-dynaep is a second pulse owner"));
    }
    Ok(String::from("ok aep-dynaep is not a second pulse owner"))
}
pub fn scan_drift_not_pulse_length(src: &str) -> Result<String, String> {
    let code = compact(&strip_line_comments(src));
    if code.contains("max_drift_ms=1000") || code.contains("max_drift_ms:1000") || code.contains("max_drift_ms=PULSE_MS") || code.contains("fndefault_drift()->i64{1000}") {
        return Err(String::from("max_drift_ms is set to pulse length"));
    }
    Ok(String::from("ok max_drift_ms stays against freeze"))
}
pub fn scan_docking_no_local_wire_clocks(src: &str) -> Result<String, String> {
    let code = compact(&strip_line_comments(src));
    if code.contains("constMAX_FRAME_AGE_SECS") {
        return Err(String::from("docking.rs keeps local const MAX_FRAME_AGE_SECS"));
    }
    if code.contains("constMAX_FRAME_FUTURE_SKEW_SECS") {
        return Err(String::from("docking.rs keeps local const MAX_FRAME_FUTURE_SKEW_SECS"));
    }
    if code.contains("MAX_FRAME_AGE_SECS") == false || code.contains("MAX_FRAME_FUTURE_SKEW_SECS") == false {
        return Err(String::from("docking.rs does not use pulse-crate wire clocks"));
    }
    Ok(String::from("ok docking.rs imports wire clocks from pulse crate"))
}
pub fn scan_compile_live_walls_freeze(src: &str) -> Result<String, String> {
    let fn_src = extract_fn(src, "pub fn compile_live_walls");
    if fn_src.is_empty() { return Err(String::from("compile_live_walls not found")); }
    let code = compact(&strip_line_comments(&fn_src));
    if code.contains("letbridge=live.now_ms()") { return Err(String::from("compile_live_walls still uses live now as pulse bridge")); }
    if code.contains("wall_bridge_ts_ms") == false { return Err(String::from("compile_live_walls has no freeze bind")); }
    Ok(String::from("ok extra walls measure drift against freeze"))
}
fn walk_to_workspace() -> PathBuf {
    let mut dir = if let Ok(m) = std::env::var("CARGO_MANIFEST_DIR") { PathBuf::from(m) } else { std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")) };
    let mut i = 0usize;
    while i < 12 {
        if dir.join("AEP-Base-Node/crate/src/docking.rs").is_file() { return dir; }
        match dir.parent() { Some(parent) => dir = parent.to_path_buf(), None => break }
        i = i.saturating_add(1);
    }
    PathBuf::from(".")
}
fn read_src(path: &PathBuf, label: &str) -> Result<String, String> {
    if path.is_file() == false { return Err(format!("missing {label} source")); }
    match fs::read_to_string(path) { Ok(v) => if v.is_empty() { Err(format!("empty {label} source")) } else { Ok(v) }, Err(e) => Err(e.to_string()) }
}
pub fn run_gate() -> Result<i32, String> {
    let root = walk_to_workspace();
    let dock_src = read_src(&root.join("AEP-Base-Node/crate/src/docking.rs"), "docking")?;
    let dyn_src = read_src(&root.join("AEP-Components/dynAEP/crate/src/lib.rs"), "dynaep")?;
    let env_src = read_src(&root.join("AEP-Components/envelope/crate/src/lib.rs"), "envelope")?;
    let live_src = read_src(&root.join("AEP-Components/live-entry/crate/src/lib.rs"), "live-entry")?;
    let tmp_src = read_src(&root.join("AEP-Components/admit-temporal-bounds/crate/src/compile.rs"), "compile_temporal")?;
    let live_dock_src = read_src(&root.join("AEP-Components/admit-live-dock/crate/src/lib.rs"), "admit-live-dock")?;
    let proofs = [scan_docking_pulse_owner(&dock_src)?, scan_dynaep_not_pulse_owner(&dyn_src)?, scan_drift_not_pulse_length(&env_src)?, scan_drift_not_pulse_length(&tmp_src)?, scan_drift_not_pulse_length(&live_src)?, scan_drift_not_pulse_length(&dock_src)?, scan_drift_not_pulse_length(&live_dock_src)?, scan_compile_live_walls_freeze(&live_dock_src)?, scan_docking_no_local_wire_clocks(&dock_src)?];
    if live_src.contains("freeze_temporal_snapshot") == false { return Err(String::from("live-entry has no freeze_temporal_snapshot")); }
    if live_src.contains("wall_bridge_ts_ms") == false { return Err(String::from("live-entry has no wall_bridge_ts_ms")); }
    for p in proofs { let _ = std::io::stdout().write_all(p.as_bytes()); let _ = std::io::stdout().write_all(b"\n"); }
    Ok(0)
}
#[cfg(test)]
mod tests {
    use super::*;
    fn must(cond: bool) { if cond == false { std::process::abort(); } }
    fn cap(digest: &str, agent: &str, seq: i64, freeze_ms: i64, bytes: usize) -> QueuedCapsule {
        QueuedCapsule { digest: String::from(digest), agent_id: String::from(agent), sequence_number: seq, byte_len: bytes, freeze: freeze_temporal_snapshot(freeze_ms, 0) }
    }
    #[test]
    fn ticket_and_bounds() {
        must(TICKET == "AEP28-ENV-065");
        must(PARENT_TICKET_ENV066 == "AEP28-ENV-066");
        must(TICKET_ENV074 == "AEP28-ENV-074");
        must(PULSE_MS == 1000 && MAX_DRIFT_MS == 50 && MAX_AGE_MS == 5000);
        must(MAX_FRAME_AGE_SECS == 300 && MAX_FRAME_FUTURE_SKEW_SECS == 60);
        must(QUEUE_CAP_CAPSULES == 256 && QUEUE_CAP_BYTES == 262144);
        must(MAX_DRIFT_MS != PULSE_MS);
        must(MAX_DRIFT_MS != 1000);
        let freeze = freeze_temporal_snapshot(1_000_000, 1);
        must(freeze.max_drift_ms == 50);
        must(drift_against_freeze(1_000_040, &freeze) <= 50);
        must(drift_against_freeze(1_000_051, &freeze) > 50);
        must(fate_at(1_001_000, &freeze) == CapsuleFate::Ready);
        must(fate_at(1_005_000, &freeze) == CapsuleFate::Ready);
        must(fate_at(1_005_001, &freeze) == CapsuleFate::Aged);
        must(hold_age_ms(1_001_000, &freeze) == 1000);
    }
    #[test]
    fn overflow_and_duplicate() {
        let mut q = PulseQueue::new();
        for i in 0..QUEUE_CAP_CAPSULES {
            q.enqueue(cap(&format!("d{i}"), "ag", i as i64 + 1, 1000, 1)).expect("enq");
        }
        match q.enqueue(cap("overflow", "ag", 999, 1000, 1)) { Err(EnqueueDeny::OverflowCapsules) => {}, _ => std::process::abort() }
        let mut q = PulseQueue::new();
        q.enqueue(cap("big", "ag", 1, 1000, QUEUE_CAP_BYTES)).expect("enq");
        match q.enqueue(cap("one-more", "ag", 2, 1000, 1)) { Err(EnqueueDeny::OverflowBytes) => {}, _ => std::process::abort() }
        let mut q = PulseQueue::new();
        q.enqueue(cap("same", "ag", 1, 1000, 8)).expect("enq");
        match q.enqueue(cap("same", "ag", 2, 1000, 8)) { Err(EnqueueDeny::DuplicateDigest) => {}, _ => std::process::abort() }
    }
    #[test]
    fn sequence_order_and_hold() {
        let mut q = PulseQueue::new();
        q.enqueue(cap("b", "ag-a", 2, 1000, 4)).expect("enq");
        q.enqueue(cap("a", "ag-a", 1, 1000, 4)).expect("enq");
        let rel = q.beat(2000);
        let a: Vec<_> = rel.ready.iter().filter(|c| c.agent_id == "ag-a").map(|c| c.sequence_number).collect();
        must(a == vec![1, 2]);
        let mut q = PulseQueue::new();
        q.enqueue(cap("late", "ag", 1, 1500, 4)).expect("enq");
        q.enqueue(cap("early", "ag", 2, 1000, 4)).expect("enq");
        must(q.beat(2000).ready.len() == 0);
        let rel2 = q.beat(2500);
        must(rel2.ready.len() == 2 && rel2.ready[0].sequence_number == 1 && rel2.ready[1].sequence_number == 2);
        let mut q = PulseQueue::new();
        q.enqueue(cap("w", "ag", 1, 1000, 4)).expect("enq");
        must(q.beat(1999).ready.is_empty());
        must(q.beat(2000).ready.len() == 1);
    }
    #[test]
    fn scans_and_drift_not_pulse() {
        let bad = "fn handle_frame() { admit_sealed_payload_on_live_dock(&mut live, &plaintext, &dock); }";
        must(scan_docking_pulse_owner(bad).is_err());
        must(scan_dynaep_not_pulse_owner("pub const QUEUE_CAP_CAPSULES: usize = 256; struct PulseQueue {}").is_err());
        must(scan_drift_not_pulse_length("fn default_drift() -> i64 { 1000 }").is_err());
        must(scan_compile_live_walls_freeze("pub fn compile_live_walls() { let bridge = live.now_ms(); }").is_err());
        must(scan_compile_live_walls_freeze("pub fn compile_live_walls() { let bridge = live.wall_bridge_ts_ms(); }").is_ok());
        must(MAX_DRIFT_MS != 1000);
        must(scan_docking_no_local_wire_clocks("const MAX_FRAME_AGE_SECS: u64 = 300;\nconst MAX_FRAME_FUTURE_SKEW_SECS: u64 = 60;").is_err());
        must(scan_docking_no_local_wire_clocks("use aep_base_node_pulse::{MAX_FRAME_AGE_SECS, MAX_FRAME_FUTURE_SKEW_SECS};").is_ok());
        let root = walk_to_workspace();
        let dock_src = read_src(&root.join("AEP-Base-Node/crate/src/docking.rs"), "docking").expect("docking.rs");
        must(scan_docking_no_local_wire_clocks(&dock_src).is_ok());
    }
}
