// @PAD: gaplune-creation-pad via gaplune-pad-transform encode
// @GCDE: gaplune-decode hmac-sha256:a784685983c436d804591b4173b1c952789806a83947d35fd7f3cffb42801292
// crate: aep-admit-writing-walls
// Generated by GAPLUNE Creation PAD ( zero-LLM, Rust-only )
// tokens: 0

use aep_admit::{admit_collect_all, AdmitResult, AdmitWall};

pub use aep_admit::{
    collect_payload_strings, compile_writing_walls, compile_writing_walls_for_strings,
    writing_wall_id, RULE_NO_EM_DASHES, RULE_NO_OXFORD_COMMA,
};

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: compile_writing_walls domain:admit type:service
pub mod compile_writing_walls_svc {
    use aep_admit::AdmitWall;

    pub struct CompileWritingWalls {
        pub text: String,
        pub walls: Vec<AdmitWall>,
    }

    impl CompileWritingWalls {
        pub fn new() -> Self {
            Self {
                text: Default::default(),
                walls: Default::default(),
            }
        }

        /// Compile writing.gap denies into Admit walls for one collect-all pass
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.walls = aep_admit::compile_writing_walls(&self.text);
            Ok(())
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: collect_payload_strings domain:admit type:service
pub mod collect_payload_strings_svc {
    pub struct CollectPayloadStrings {
        pub payload: String,
        pub strings: Vec<String>,
    }

    impl CollectPayloadStrings {
        pub fn new() -> Self {
            Self {
                payload: Default::default(),
                strings: Default::default(),
            }
        }

        /// Walk payload values and collect every string for writing walls
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.strings = aep_admit::collect_payload_strings(&self.payload);
            Ok(())
        }
    }
}

// @PAD: gaplune-creation-pad emit ( zero-LLM )
// HVVCAS: writing_wall_ids domain:admit type:service
pub mod writing_wall_ids {
    pub struct WritingWallIds {
        pub rule: String,
        pub wall_id: String,
    }

    impl WritingWallIds {
        pub fn new() -> Self {
            Self {
                rule: Default::default(),
                wall_id: Default::default(),
            }
        }

        /// Name writing walls writing.no_em_dashes and writing.no_oxford_comma
        pub fn process(&mut self) -> anyhow::Result<()> {
            self.wall_id = aep_admit::writing_wall_id(&self.rule);
            Ok(())
        }
    }
}

/// Fold writing walls plus extra walls into one collect-all pass.
pub fn fold_writing_into_admit(text: &str, extra: &[AdmitWall]) -> AdmitResult {
    let mut walls = aep_admit::compile_writing_walls(text);
    walls.extend(extra.iter().cloned());
    admit_collect_all(&walls)
}

#[cfg(test)]
mod tests {
    use super::*;
    use aep_admit::{AdmitWall, RULE_NO_EM_DASHES, RULE_NO_OXFORD_COMMA};

    fn em_sample() -> String {
        let mut s = String::from("bad");
        s.push('\u{2014}');
        s.push_str("dash");
        s
    }

    fn oxford_sample() -> String {
        let mut s = String::from("red, white");
        s.push(',');
        s.push_str(" and blue");
        s
    }

    #[test]
    fn fold_keeps_writing_and_constraint_on_one_pass() {
        let extra = vec![AdmitWall::close("constraint:required_field:alpha", "alpha required")];
        let result = fold_writing_into_admit(&em_sample(), &extra);
        assert_eq!(result.allow, false);
        let wid = writing_wall_id(RULE_NO_EM_DASHES);
        let ids: Vec<&str> = result.closed.iter().map(|w| w.id.as_str()).collect();
        assert_eq!(ids.contains(&wid.as_str()), true);
        assert_eq!(ids.contains(&"constraint:required_field:alpha"), true);
    }

    #[test]
    fn oxford_and_em_both_close() {
        let mut text = em_sample();
        text.push('\n');
        text.push_str(&oxford_sample());
        let result = fold_writing_into_admit(&text, &[]);
        assert_eq!(result.allow, false);
        let em = writing_wall_id(RULE_NO_EM_DASHES);
        let ox = writing_wall_id(RULE_NO_OXFORD_COMMA);
        let ids: Vec<&str> = result.closed.iter().map(|w| w.id.as_str()).collect();
        assert_eq!(ids.contains(&em.as_str()), true);
        assert_eq!(ids.contains(&ox.as_str()), true);
    }

    #[test]
    fn wall_id_prefix() {
        let mut ids = writing_wall_ids::WritingWallIds::new();
        ids.rule = RULE_NO_EM_DASHES.into();
        ids.process().expect("ids");
        assert_eq!(ids.wall_id, "writing:no_em_dashes");
    }
}
