package server_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nla-aep/aep-caw-framework/internal/config"
	"github.com/nla-aep/aep-caw-framework/internal/server"
	"github.com/nla-aep/aep-caw-framework/internal/store/watchtower/compact"
)

// TestBuildWatchtowerStore_DisabledReturnsNil verifies that the disabled
// case short-circuits without errors and returns a nil store.
func TestBuildWatchtowerStore_DisabledReturnsNil(t *testing.T) {
	s, err := server.BuildWatchtowerStoreForTest(context.Background(),
		config.AuditWatchtowerConfig{Enabled: false},
		compact.StubMapper{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if s != nil {
		t.Fatal("expected nil store when disabled")
	}
}

// TestBuildWatchtowerStore_RejectsInvalidConfig verifies that validation runs
// and returns an error when the chain key source is not configured.
// (The config.AuditWatchtowerConfig schema uses Chain.KeyFile/KeyEnv for the
// HMAC key - the plan's HMACSecret field does not exist in the current schema.
// An empty Chain config causes the KMS provider to fail, which surfaces as an
// error before the store is opened.)
func TestBuildWatchtowerStore_RejectsInvalidConfig(t *testing.T) {
	cfg := config.AuditWatchtowerConfig{
		Enabled:   true,
		StateDir:  t.TempDir(),
		Endpoint:  "localhost:0",
		SessionID: "s",
		// Chain.KeyFile, KeyEnv, and all cloud-KMS sub-configs are empty
		// (no key source). The KMS provider will return an error.
		Auth: config.WatchtowerAuthConfig{
			TokenEnv: "AEP_CAW_TEST_WTP_TOKEN_NOT_SET",
		},
	}
	_, err := server.BuildWatchtowerStoreForTest(context.Background(),
		cfg, compact.StubMapper{})
	if err == nil {
		t.Fatal("expected error for missing chain key source")
	}
	t.Logf("got expected error: %v", err)
}

// TestBuildWatchtowerStore_EmptySessionIDAutoGenerated verifies that an empty
// session_id does NOT cause buildWatchtowerStore to fail. The function must
// auto-generate a session_id rather than passing the empty string through to
// watchtower.New (which rejects it). The test expects the construction to fail
// at the KMS-provider step (missing chain key), NOT at the session-id
// validation step.
func TestBuildWatchtowerStore_EmptySessionIDAutoGenerated(t *testing.T) {
	cfg := config.AuditWatchtowerConfig{
		Enabled:  true,
		StateDir: t.TempDir(),
		Endpoint: "localhost:0",
		// SessionID intentionally empty - should be auto-generated.
		SessionID: "",
		Auth:      config.WatchtowerAuthConfig{TokenEnv: "AEP_CAW_TEST_WTP_TOKEN_NOT_SET"},
	}
	_, err := server.BuildWatchtowerStoreForTest(context.Background(),
		cfg, compact.StubMapper{})
	// We expect an error - but it must NOT be about session_id.
	// The failure must come from the missing chain key, not from
	// "SessionID is required".
	if err == nil {
		t.Fatal("expected an error (missing chain key), got nil")
	}
	if strings.Contains(err.Error(), "SessionID") || strings.Contains(err.Error(), "session_id") {
		t.Fatalf("session_id auto-generation failed - error mentions session_id: %v", err)
	}
	t.Logf("correctly failed at KMS step, not at session_id: %v", err)
}

// TestResolveAuthBearer_TrimWhitespace_File verifies that tokens loaded from a
// file are trimmed of leading/trailing whitespace (including trailing newline).
func TestResolveAuthBearer_TrimWhitespace_File(t *testing.T) {
	dir := t.TempDir()
	tokenFile := filepath.Join(dir, "token")
	// Write token with trailing newline (common with `echo` or heredoc output).
	if err := os.WriteFile(tokenFile, []byte("mytoken\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	auth := config.WatchtowerAuthConfig{TokenFile: tokenFile}
	token, err := server.ResolveAuthBearerForTest(auth)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if token != "mytoken" {
		t.Fatalf("expected trimmed token %q, got %q", "mytoken", token)
	}
}

// TestResolveAuthBearer_TrimWhitespace_Env verifies that tokens loaded from
// an environment variable are trimmed of leading/trailing whitespace.
func TestResolveAuthBearer_TrimWhitespace_Env(t *testing.T) {
	const envKey = "AEP_CAW_TEST_WTP_TRIM_TOKEN"
	t.Setenv(envKey, "  envtoken  ")
	auth := config.WatchtowerAuthConfig{TokenEnv: envKey}
	token, err := server.ResolveAuthBearerForTest(auth)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if token != "envtoken" {
		t.Fatalf("expected trimmed token %q, got %q", "envtoken", token)
	}
}

// TestResolveAuthBearer_EmptyFileAfterTrim_ReturnsError verifies that an
// all-whitespace token file returns an error rather than an empty string.
func TestResolveAuthBearer_EmptyFileAfterTrim_ReturnsError(t *testing.T) {
	dir := t.TempDir()
	tokenFile := filepath.Join(dir, "token")
	if err := os.WriteFile(tokenFile, []byte("   \n\t  \n"), 0o600); err != nil {
		t.Fatal(err)
	}
	auth := config.WatchtowerAuthConfig{TokenFile: tokenFile}
	_, err := server.ResolveAuthBearerForTest(auth)
	if err == nil {
		t.Fatal("expected error for all-whitespace token file, got nil")
	}
	t.Logf("got expected error: %v", err)
}

// TestWatchtowerTLSConfig_InsecureField_Default verifies that the
// WatchtowerTLSConfig.Insecure field defaults to false (TLS on) when not set
// in a zero-value struct.
func TestWatchtowerTLSConfig_InsecureField_Default(t *testing.T) {
	var tlsCfg config.WatchtowerTLSConfig
	if tlsCfg.Insecure {
		t.Fatal("WatchtowerTLSConfig.Insecure should default to false (TLS on by default)")
	}
}

// TestResolveAgentID_ExplicitOverride verifies the config field takes
// precedence over os.Hostname(). Regression test for issue #365.
func TestResolveAgentID_ExplicitOverride(t *testing.T) {
	cfg := config.AuditWatchtowerConfig{AgentID: "agent-edge-001"}
	got := server.ResolveAgentIDForTest(cfg)
	if got != "agent-edge-001" {
		t.Errorf("ResolveAgentIDForTest = %q, want %q", got, "agent-edge-001")
	}
}

// TestResolveAgentID_EmptyFallsBackToHostnamePID verifies the empty
// string triggers the "<hostname>-<pid>" fallback. The PID suffix
// disambiguates multiple aep-caw processes co-resident on the same
// host.
func TestResolveAgentID_EmptyFallsBackToHostnamePID(t *testing.T) {
	cfg := config.AuditWatchtowerConfig{AgentID: ""}
	got := server.ResolveAgentIDForTest(cfg)
	hostname, err := os.Hostname()
	if err != nil || hostname == "" {
		hostname = "unknown"
	}
	want := fmt.Sprintf("%s-%d", hostname, os.Getpid())
	if got != want {
		t.Errorf("ResolveAgentIDForTest = %q, want %q", got, want)
	}
}

// TestResolveAgentID_WhitespaceTreatedAsEmpty verifies whitespace-only
// values fall back to the hostname-PID identity (same path as empty).
func TestResolveAgentID_WhitespaceTreatedAsEmpty(t *testing.T) {
	cfg := config.AuditWatchtowerConfig{AgentID: "   "}
	got := server.ResolveAgentIDForTest(cfg)
	hostname, err := os.Hostname()
	if err != nil || hostname == "" {
		hostname = "unknown"
	}
	want := fmt.Sprintf("%s-%d", hostname, os.Getpid())
	if got != want {
		t.Errorf("ResolveAgentIDForTest(whitespace) = %q, want %q", got, want)
	}
}

// TestResolveAgentID_TrimsLeadingTrailingWhitespace verifies a
// well-formed-but-padded value is trimmed before use.
func TestResolveAgentID_TrimsLeadingTrailingWhitespace(t *testing.T) {
	cfg := config.AuditWatchtowerConfig{AgentID: "  agent-x  "}
	got := server.ResolveAgentIDForTest(cfg)
	if got != "agent-x" {
		t.Errorf("ResolveAgentIDForTest = %q, want %q (trimmed)", got, "agent-x")
	}
}
