// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aepcaw/wtp/v1/ocsf/application_activity.proto

package ocsfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApplicationActivity (class_uid 6005). OCSF v1.8.0 subset, with aep-caw
// extensions for infrastructure events tagged via agent_internal.
//
// OCSF activities used (1..7):
//
//	1 = Open
//	2 = Close
//	3 = Update
//	6 = Other (used for misc agent actions like secret_access)
//
// aep-caw internal activities (>=100, see AppActivity enum):
//
//	100 = EBPF Attached
//	101 = FUSE Mounted
//	102 = Cgroup Applied
//	103 = LLM Proxy Started
//	104 = Net Proxy Started
//	105 = MCP Tool Called
//	106 = MCP Tool Seen
//	107 = MCP Tools List Changed
//	108 = MCP Sampling Request
//	109 = MCP Tool Result Inspected
//	110 = Integrity Chain Rotated
//	111 = Wrap Init
//	112 = FSEvents Error
//	120 = Policy Created
//	121 = Policy Updated
//	122 = Policy Deleted
//	130 = Session Created
//	131 = Session Destroyed
//	132 = Session Expired
//	133 = Session Updated
//	140 = Cgroup Apply Failed
//	141 = Cgroup Cleanup Failed
//	142 = FUSE Mount Failed
//	143 = EBPF Attach Failed
//	144 = EBPF Collector Failed
//	145 = EBPF Enforce Disabled
//	146 = EBPF Enforce Non-Strict
//	147 = EBPF Enforce Refresh Failed
//	148 = EBPF Unavailable
//	149 = LLM Proxy Failed
//	150 = Net Proxy Failed
//	153 = MCP Tool Changed
type ApplicationActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassUid      *uint32                `protobuf:"varint,1,opt,name=class_uid,json=classUid,proto3,oneof" json:"class_uid,omitempty"` // 6005
	ActivityId    *uint32                `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3,oneof" json:"activity_id,omitempty"`
	CategoryUid   *uint32                `protobuf:"varint,3,opt,name=category_uid,json=categoryUid,proto3,oneof" json:"category_uid,omitempty"` // 6 = Application Activity
	TypeUid       *uint32                `protobuf:"varint,4,opt,name=type_uid,json=typeUid,proto3,oneof" json:"type_uid,omitempty"`
	Time          *uint64                `protobuf:"varint,5,opt,name=time,proto3,oneof" json:"time,omitempty"`
	Severity      *string                `protobuf:"bytes,6,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,8,opt,name=actor,proto3,oneof" json:"actor,omitempty"`
	AppName       *string                `protobuf:"bytes,9,opt,name=app_name,json=appName,proto3,oneof" json:"app_name,omitempty"`
	ResourceUid   *string                `protobuf:"bytes,10,opt,name=resource_uid,json=resourceUid,proto3,oneof" json:"resource_uid,omitempty"`        // generic per-event identifier (tool name, secret name, …)
	AgentInternal *bool                  `protobuf:"varint,50,opt,name=agent_internal,json=agentInternal,proto3,oneof" json:"agent_internal,omitempty"` // load-bearing  -  server-side filter signal
	// Generic enrichments slot for class 6005 only  -  values projected from
	// ev.Fields by the per-Type allowlist. The map's key set is bounded by
	// the registry; values are pre-stringified by the projector.
	Enrichments   map[string]string `protobuf:"bytes,51,rep,name=enrichments,proto3" json:"enrichments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationActivity) Reset() {
	*x = ApplicationActivity{}
	mi := &file_aepcaw_wtp_v1_ocsf_application_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationActivity) ProtoMessage() {}

func (x *ApplicationActivity) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_application_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationActivity.ProtoReflect.Descriptor instead.
func (*ApplicationActivity) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationActivity) GetClassUid() uint32 {
	if x != nil && x.ClassUid != nil {
		return *x.ClassUid
	}
	return 0
}

func (x *ApplicationActivity) GetActivityId() uint32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *ApplicationActivity) GetCategoryUid() uint32 {
	if x != nil && x.CategoryUid != nil {
		return *x.CategoryUid
	}
	return 0
}

func (x *ApplicationActivity) GetTypeUid() uint32 {
	if x != nil && x.TypeUid != nil {
		return *x.TypeUid
	}
	return 0
}

func (x *ApplicationActivity) GetTime() uint64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *ApplicationActivity) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *ApplicationActivity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ApplicationActivity) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ApplicationActivity) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	return ""
}

func (x *ApplicationActivity) GetResourceUid() string {
	if x != nil && x.ResourceUid != nil {
		return *x.ResourceUid
	}
	return ""
}

func (x *ApplicationActivity) GetAgentInternal() bool {
	if x != nil && x.AgentInternal != nil {
		return *x.AgentInternal
	}
	return false
}

func (x *ApplicationActivity) GetEnrichments() map[string]string {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

var File_aepcaw_wtp_v1_ocsf_application_activity_proto protoreflect.FileDescriptor

const file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDesc = "" +
	"\n" +
	"-aepcaw/wtp/v1/ocsf/application_activity.proto\x12\x12aepcaw.wtp.v1.ocsf\x1a\x1faepcaw/wtp/v1/ocsf/common.proto\"\xfe\x05\n" +
	"\x13ApplicationActivity\x12 \n" +
	"\tclass_uid\x18\x01 \x01(\rH\x00R\bclassUid\x88\x01\x01\x12$\n" +
	"\vactivity_id\x18\x02 \x01(\rH\x01R\n" +
	"activityId\x88\x01\x01\x12&\n" +
	"\fcategory_uid\x18\x03 \x01(\rH\x02R\vcategoryUid\x88\x01\x01\x12\x1e\n" +
	"\btype_uid\x18\x04 \x01(\rH\x03R\atypeUid\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\x05 \x01(\x04H\x04R\x04time\x88\x01\x01\x12\x1f\n" +
	"\bseverity\x18\x06 \x01(\tH\x05R\bseverity\x88\x01\x01\x12=\n" +
	"\bmetadata\x18\a \x01(\v2\x1c.aepcaw.wtp.v1.ocsf.MetadataH\x06R\bmetadata\x88\x01\x01\x124\n" +
	"\x05actor\x18\b \x01(\v2\x19.aepcaw.wtp.v1.ocsf.ActorH\aR\x05actor\x88\x01\x01\x12\x1e\n" +
	"\bapp_name\x18\t \x01(\tH\bR\aappName\x88\x01\x01\x12&\n" +
	"\fresource_uid\x18\n" +
	" \x01(\tH\tR\vresourceUid\x88\x01\x01\x12*\n" +
	"\x0eagent_internal\x182 \x01(\bH\n" +
	"R\ragentInternal\x88\x01\x01\x12Z\n" +
	"\venrichments\x183 \x03(\v28.aepcaw.wtp.v1.ocsf.ApplicationActivity.EnrichmentsEntryR\venrichments\x1a>\n" +
	"\x10EnrichmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_class_uidB\x0e\n" +
	"\f_activity_idB\x0f\n" +
	"\r_category_uidB\v\n" +
	"\t_type_uidB\a\n" +
	"\x05_timeB\v\n" +
	"\t_severityB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_actorB\v\n" +
	"\t_app_nameB\x0f\n" +
	"\r_resource_uidB\x11\n" +
	"\x0f_agent_internalBFZDgithub.com/nla-aep/aep-caw-framework/proto/aepcaw/wtp/v1/ocsf;ocsfpbb\x06proto3"

var (
	file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDescOnce sync.Once
	file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDescData []byte
)

func file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDescGZIP() []byte {
	file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDescOnce.Do(func() {
		file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDesc)))
	})
	return file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDescData
}

var file_aepcaw_wtp_v1_ocsf_application_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aepcaw_wtp_v1_ocsf_application_activity_proto_goTypes = []any{
	(*ApplicationActivity)(nil), // 0: aepcaw.wtp.v1.ocsf.ApplicationActivity
	nil,                         // 1: aepcaw.wtp.v1.ocsf.ApplicationActivity.EnrichmentsEntry
	(*Metadata)(nil),            // 2: aepcaw.wtp.v1.ocsf.Metadata
	(*Actor)(nil),               // 3: aepcaw.wtp.v1.ocsf.Actor
}
var file_aepcaw_wtp_v1_ocsf_application_activity_proto_depIdxs = []int32{
	2, // 0: aepcaw.wtp.v1.ocsf.ApplicationActivity.metadata:type_name -> aepcaw.wtp.v1.ocsf.Metadata
	3, // 1: aepcaw.wtp.v1.ocsf.ApplicationActivity.actor:type_name -> aepcaw.wtp.v1.ocsf.Actor
	1, // 2: aepcaw.wtp.v1.ocsf.ApplicationActivity.enrichments:type_name -> aepcaw.wtp.v1.ocsf.ApplicationActivity.EnrichmentsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aepcaw_wtp_v1_ocsf_application_activity_proto_init() }
func file_aepcaw_wtp_v1_ocsf_application_activity_proto_init() {
	if File_aepcaw_wtp_v1_ocsf_application_activity_proto != nil {
		return
	}
	file_aepcaw_wtp_v1_ocsf_common_proto_init()
	file_aepcaw_wtp_v1_ocsf_application_activity_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_application_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aepcaw_wtp_v1_ocsf_application_activity_proto_goTypes,
		DependencyIndexes: file_aepcaw_wtp_v1_ocsf_application_activity_proto_depIdxs,
		MessageInfos:      file_aepcaw_wtp_v1_ocsf_application_activity_proto_msgTypes,
	}.Build()
	File_aepcaw_wtp_v1_ocsf_application_activity_proto = out.File
	file_aepcaw_wtp_v1_ocsf_application_activity_proto_goTypes = nil
	file_aepcaw_wtp_v1_ocsf_application_activity_proto_depIdxs = nil
}
