// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aepcaw/wtp/v1/ocsf/detection_finding.proto

package ocsfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DetectionFinding (class_uid 2004). OCSF v1.8.0 subset.
//
// Activities used:
//
//	1 = Create
//	2 = Update
//	3 = Close
type DetectionFinding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClassUid       *uint32                `protobuf:"varint,1,opt,name=class_uid,json=classUid,proto3,oneof" json:"class_uid,omitempty"` // 2004
	ActivityId     *uint32                `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3,oneof" json:"activity_id,omitempty"`
	CategoryUid    *uint32                `protobuf:"varint,3,opt,name=category_uid,json=categoryUid,proto3,oneof" json:"category_uid,omitempty"` // 2 = Findings
	TypeUid        *uint32                `protobuf:"varint,4,opt,name=type_uid,json=typeUid,proto3,oneof" json:"type_uid,omitempty"`
	Time           *uint64                `protobuf:"varint,5,opt,name=time,proto3,oneof" json:"time,omitempty"`
	Severity       *string                `protobuf:"bytes,6,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	Metadata       *Metadata              `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Actor          *Actor                 `protobuf:"bytes,8,opt,name=actor,proto3,oneof" json:"actor,omitempty"`
	FindingInfo    *FindingInfo           `protobuf:"bytes,9,opt,name=finding_info,json=findingInfo,proto3,oneof" json:"finding_info,omitempty"`
	PolicyDecision *string                `protobuf:"bytes,10,opt,name=policy_decision,json=policyDecision,proto3,oneof" json:"policy_decision,omitempty"`
	PolicyRule     *string                `protobuf:"bytes,11,opt,name=policy_rule,json=policyRule,proto3,oneof" json:"policy_rule,omitempty"`
	ThreatFeed     *string                `protobuf:"bytes,12,opt,name=threat_feed,json=threatFeed,proto3,oneof" json:"threat_feed,omitempty"`
	ThreatMatch    *string                `protobuf:"bytes,13,opt,name=threat_match,json=threatMatch,proto3,oneof" json:"threat_match,omitempty"`
	ThreatAction   *string                `protobuf:"bytes,14,opt,name=threat_action,json=threatAction,proto3,oneof" json:"threat_action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetectionFinding) Reset() {
	*x = DetectionFinding{}
	mi := &file_aepcaw_wtp_v1_ocsf_detection_finding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionFinding) ProtoMessage() {}

func (x *DetectionFinding) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_detection_finding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionFinding.ProtoReflect.Descriptor instead.
func (*DetectionFinding) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDescGZIP(), []int{0}
}

func (x *DetectionFinding) GetClassUid() uint32 {
	if x != nil && x.ClassUid != nil {
		return *x.ClassUid
	}
	return 0
}

func (x *DetectionFinding) GetActivityId() uint32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *DetectionFinding) GetCategoryUid() uint32 {
	if x != nil && x.CategoryUid != nil {
		return *x.CategoryUid
	}
	return 0
}

func (x *DetectionFinding) GetTypeUid() uint32 {
	if x != nil && x.TypeUid != nil {
		return *x.TypeUid
	}
	return 0
}

func (x *DetectionFinding) GetTime() uint64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *DetectionFinding) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *DetectionFinding) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DetectionFinding) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *DetectionFinding) GetFindingInfo() *FindingInfo {
	if x != nil {
		return x.FindingInfo
	}
	return nil
}

func (x *DetectionFinding) GetPolicyDecision() string {
	if x != nil && x.PolicyDecision != nil {
		return *x.PolicyDecision
	}
	return ""
}

func (x *DetectionFinding) GetPolicyRule() string {
	if x != nil && x.PolicyRule != nil {
		return *x.PolicyRule
	}
	return ""
}

func (x *DetectionFinding) GetThreatFeed() string {
	if x != nil && x.ThreatFeed != nil {
		return *x.ThreatFeed
	}
	return ""
}

func (x *DetectionFinding) GetThreatMatch() string {
	if x != nil && x.ThreatMatch != nil {
		return *x.ThreatMatch
	}
	return ""
}

func (x *DetectionFinding) GetThreatAction() string {
	if x != nil && x.ThreatAction != nil {
		return *x.ThreatAction
	}
	return ""
}

type FindingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`                             // human-readable summary
	Desc          *string                `protobuf:"bytes,2,opt,name=desc,proto3,oneof" json:"desc,omitempty"`                               // ev.Policy.Message when present
	FindingUid    *string                `protobuf:"bytes,3,opt,name=finding_uid,json=findingUid,proto3,oneof" json:"finding_uid,omitempty"` // ev.ID
	Types         *string                `protobuf:"bytes,4,opt,name=types,proto3,oneof" json:"types,omitempty"`                             // "policy_decision" | "threat" | "agent_self_detected" | …
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingInfo) Reset() {
	*x = FindingInfo{}
	mi := &file_aepcaw_wtp_v1_ocsf_detection_finding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingInfo) ProtoMessage() {}

func (x *FindingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_detection_finding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingInfo.ProtoReflect.Descriptor instead.
func (*FindingInfo) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDescGZIP(), []int{1}
}

func (x *FindingInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *FindingInfo) GetDesc() string {
	if x != nil && x.Desc != nil {
		return *x.Desc
	}
	return ""
}

func (x *FindingInfo) GetFindingUid() string {
	if x != nil && x.FindingUid != nil {
		return *x.FindingUid
	}
	return ""
}

func (x *FindingInfo) GetTypes() string {
	if x != nil && x.Types != nil {
		return *x.Types
	}
	return ""
}

var File_aepcaw_wtp_v1_ocsf_detection_finding_proto protoreflect.FileDescriptor

const file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDesc = "" +
	"\n" +
	"*aepcaw/wtp/v1/ocsf/detection_finding.proto\x12\x12aepcaw.wtp.v1.ocsf\x1a\x1faepcaw/wtp/v1/ocsf/common.proto\"\xb7\x06\n" +
	"\x10DetectionFinding\x12 \n" +
	"\tclass_uid\x18\x01 \x01(\rH\x00R\bclassUid\x88\x01\x01\x12$\n" +
	"\vactivity_id\x18\x02 \x01(\rH\x01R\n" +
	"activityId\x88\x01\x01\x12&\n" +
	"\fcategory_uid\x18\x03 \x01(\rH\x02R\vcategoryUid\x88\x01\x01\x12\x1e\n" +
	"\btype_uid\x18\x04 \x01(\rH\x03R\atypeUid\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\x05 \x01(\x04H\x04R\x04time\x88\x01\x01\x12\x1f\n" +
	"\bseverity\x18\x06 \x01(\tH\x05R\bseverity\x88\x01\x01\x12=\n" +
	"\bmetadata\x18\a \x01(\v2\x1c.aepcaw.wtp.v1.ocsf.MetadataH\x06R\bmetadata\x88\x01\x01\x124\n" +
	"\x05actor\x18\b \x01(\v2\x19.aepcaw.wtp.v1.ocsf.ActorH\aR\x05actor\x88\x01\x01\x12G\n" +
	"\ffinding_info\x18\t \x01(\v2\x1f.aepcaw.wtp.v1.ocsf.FindingInfoH\bR\vfindingInfo\x88\x01\x01\x12,\n" +
	"\x0fpolicy_decision\x18\n" +
	" \x01(\tH\tR\x0epolicyDecision\x88\x01\x01\x12$\n" +
	"\vpolicy_rule\x18\v \x01(\tH\n" +
	"R\n" +
	"policyRule\x88\x01\x01\x12$\n" +
	"\vthreat_feed\x18\f \x01(\tH\vR\n" +
	"threatFeed\x88\x01\x01\x12&\n" +
	"\fthreat_match\x18\r \x01(\tH\fR\vthreatMatch\x88\x01\x01\x12(\n" +
	"\rthreat_action\x18\x0e \x01(\tH\rR\fthreatAction\x88\x01\x01B\f\n" +
	"\n" +
	"_class_uidB\x0e\n" +
	"\f_activity_idB\x0f\n" +
	"\r_category_uidB\v\n" +
	"\t_type_uidB\a\n" +
	"\x05_timeB\v\n" +
	"\t_severityB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_actorB\x0f\n" +
	"\r_finding_infoB\x12\n" +
	"\x10_policy_decisionB\x0e\n" +
	"\f_policy_ruleB\x0e\n" +
	"\f_threat_feedB\x0f\n" +
	"\r_threat_matchB\x10\n" +
	"\x0e_threat_action\"\xaf\x01\n" +
	"\vFindingInfo\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04desc\x18\x02 \x01(\tH\x01R\x04desc\x88\x01\x01\x12$\n" +
	"\vfinding_uid\x18\x03 \x01(\tH\x02R\n" +
	"findingUid\x88\x01\x01\x12\x19\n" +
	"\x05types\x18\x04 \x01(\tH\x03R\x05types\x88\x01\x01B\b\n" +
	"\x06_titleB\a\n" +
	"\x05_descB\x0e\n" +
	"\f_finding_uidB\b\n" +
	"\x06_typesBFZDgithub.com/thePM001/AEP-agent-element-protocol/AEP-CAW/proto/aepcaw/wtp/v1/ocsf;ocsfpbb\x06proto3"

var (
	file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDescOnce sync.Once
	file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDescData []byte
)

func file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDescGZIP() []byte {
	file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDescOnce.Do(func() {
		file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDesc)))
	})
	return file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDescData
}

var file_aepcaw_wtp_v1_ocsf_detection_finding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aepcaw_wtp_v1_ocsf_detection_finding_proto_goTypes = []any{
	(*DetectionFinding)(nil), // 0: aepcaw.wtp.v1.ocsf.DetectionFinding
	(*FindingInfo)(nil),      // 1: aepcaw.wtp.v1.ocsf.FindingInfo
	(*Metadata)(nil),         // 2: aepcaw.wtp.v1.ocsf.Metadata
	(*Actor)(nil),            // 3: aepcaw.wtp.v1.ocsf.Actor
}
var file_aepcaw_wtp_v1_ocsf_detection_finding_proto_depIdxs = []int32{
	2, // 0: aepcaw.wtp.v1.ocsf.DetectionFinding.metadata:type_name -> aepcaw.wtp.v1.ocsf.Metadata
	3, // 1: aepcaw.wtp.v1.ocsf.DetectionFinding.actor:type_name -> aepcaw.wtp.v1.ocsf.Actor
	1, // 2: aepcaw.wtp.v1.ocsf.DetectionFinding.finding_info:type_name -> aepcaw.wtp.v1.ocsf.FindingInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aepcaw_wtp_v1_ocsf_detection_finding_proto_init() }
func file_aepcaw_wtp_v1_ocsf_detection_finding_proto_init() {
	if File_aepcaw_wtp_v1_ocsf_detection_finding_proto != nil {
		return
	}
	file_aepcaw_wtp_v1_ocsf_common_proto_init()
	file_aepcaw_wtp_v1_ocsf_detection_finding_proto_msgTypes[0].OneofWrappers = []any{}
	file_aepcaw_wtp_v1_ocsf_detection_finding_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_detection_finding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aepcaw_wtp_v1_ocsf_detection_finding_proto_goTypes,
		DependencyIndexes: file_aepcaw_wtp_v1_ocsf_detection_finding_proto_depIdxs,
		MessageInfos:      file_aepcaw_wtp_v1_ocsf_detection_finding_proto_msgTypes,
	}.Build()
	File_aepcaw_wtp_v1_ocsf_detection_finding_proto = out.File
	file_aepcaw_wtp_v1_ocsf_detection_finding_proto_goTypes = nil
	file_aepcaw_wtp_v1_ocsf_detection_finding_proto_depIdxs = nil
}
