// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aepcaw/wtp/v1/ocsf/dns_activity.proto

package ocsfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DNSActivity (class_uid 4003). OCSF v1.8.0 subset.
//
// Activities used:
//
//	1 = Query
//	2 = Response
//	6 = Traffic
type DNSActivity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClassUid       *uint32                `protobuf:"varint,1,opt,name=class_uid,json=classUid,proto3,oneof" json:"class_uid,omitempty"` // 4003
	ActivityId     *uint32                `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3,oneof" json:"activity_id,omitempty"`
	CategoryUid    *uint32                `protobuf:"varint,3,opt,name=category_uid,json=categoryUid,proto3,oneof" json:"category_uid,omitempty"` // 4
	TypeUid        *uint32                `protobuf:"varint,4,opt,name=type_uid,json=typeUid,proto3,oneof" json:"type_uid,omitempty"`
	Time           *uint64                `protobuf:"varint,5,opt,name=time,proto3,oneof" json:"time,omitempty"`
	Severity       *string                `protobuf:"bytes,6,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	Metadata       *Metadata              `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Actor          *Actor                 `protobuf:"bytes,8,opt,name=actor,proto3,oneof" json:"actor,omitempty"`
	Query          *DNSQuery              `protobuf:"bytes,9,opt,name=query,proto3,oneof" json:"query,omitempty"`
	RedirectTarget *string                `protobuf:"bytes,10,opt,name=redirect_target,json=redirectTarget,proto3,oneof" json:"redirect_target,omitempty"`
	PolicyDecision *string                `protobuf:"bytes,11,opt,name=policy_decision,json=policyDecision,proto3,oneof" json:"policy_decision,omitempty"`
	PolicyRule     *string                `protobuf:"bytes,12,opt,name=policy_rule,json=policyRule,proto3,oneof" json:"policy_rule,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DNSActivity) Reset() {
	*x = DNSActivity{}
	mi := &file_aepcaw_wtp_v1_ocsf_dns_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSActivity) ProtoMessage() {}

func (x *DNSActivity) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_dns_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSActivity.ProtoReflect.Descriptor instead.
func (*DNSActivity) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDescGZIP(), []int{0}
}

func (x *DNSActivity) GetClassUid() uint32 {
	if x != nil && x.ClassUid != nil {
		return *x.ClassUid
	}
	return 0
}

func (x *DNSActivity) GetActivityId() uint32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *DNSActivity) GetCategoryUid() uint32 {
	if x != nil && x.CategoryUid != nil {
		return *x.CategoryUid
	}
	return 0
}

func (x *DNSActivity) GetTypeUid() uint32 {
	if x != nil && x.TypeUid != nil {
		return *x.TypeUid
	}
	return 0
}

func (x *DNSActivity) GetTime() uint64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *DNSActivity) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *DNSActivity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DNSActivity) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *DNSActivity) GetQuery() *DNSQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *DNSActivity) GetRedirectTarget() string {
	if x != nil && x.RedirectTarget != nil {
		return *x.RedirectTarget
	}
	return ""
}

func (x *DNSActivity) GetPolicyDecision() string {
	if x != nil && x.PolicyDecision != nil {
		return *x.PolicyDecision
	}
	return ""
}

func (x *DNSActivity) GetPolicyRule() string {
	if x != nil && x.PolicyRule != nil {
		return *x.PolicyRule
	}
	return ""
}

type DNSQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      *string                `protobuf:"bytes,1,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`                 // ev.Domain or ev.Fields["hostname"]
	Type          *uint32                `protobuf:"varint,2,opt,name=type,proto3,oneof" json:"type,omitempty"`                        // dns rrtype number when known
	TypeName      *string                `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3,oneof" json:"type_name,omitempty"` // "A" | "AAAA" | "TXT" | …
	Class         *string                `protobuf:"bytes,4,opt,name=class,proto3,oneof" json:"class,omitempty"`                       // "IN"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSQuery) Reset() {
	*x = DNSQuery{}
	mi := &file_aepcaw_wtp_v1_ocsf_dns_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSQuery) ProtoMessage() {}

func (x *DNSQuery) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_dns_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSQuery.ProtoReflect.Descriptor instead.
func (*DNSQuery) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDescGZIP(), []int{1}
}

func (x *DNSQuery) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *DNSQuery) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *DNSQuery) GetTypeName() string {
	if x != nil && x.TypeName != nil {
		return *x.TypeName
	}
	return ""
}

func (x *DNSQuery) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

var File_aepcaw_wtp_v1_ocsf_dns_activity_proto protoreflect.FileDescriptor

const file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDesc = "" +
	"\n" +
	"%aepcaw/wtp/v1/ocsf/dns_activity.proto\x12\x12aepcaw.wtp.v1.ocsf\x1a\x1faepcaw/wtp/v1/ocsf/common.proto\"\xb2\x05\n" +
	"\vDNSActivity\x12 \n" +
	"\tclass_uid\x18\x01 \x01(\rH\x00R\bclassUid\x88\x01\x01\x12$\n" +
	"\vactivity_id\x18\x02 \x01(\rH\x01R\n" +
	"activityId\x88\x01\x01\x12&\n" +
	"\fcategory_uid\x18\x03 \x01(\rH\x02R\vcategoryUid\x88\x01\x01\x12\x1e\n" +
	"\btype_uid\x18\x04 \x01(\rH\x03R\atypeUid\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\x05 \x01(\x04H\x04R\x04time\x88\x01\x01\x12\x1f\n" +
	"\bseverity\x18\x06 \x01(\tH\x05R\bseverity\x88\x01\x01\x12=\n" +
	"\bmetadata\x18\a \x01(\v2\x1c.aepcaw.wtp.v1.ocsf.MetadataH\x06R\bmetadata\x88\x01\x01\x124\n" +
	"\x05actor\x18\b \x01(\v2\x19.aepcaw.wtp.v1.ocsf.ActorH\aR\x05actor\x88\x01\x01\x127\n" +
	"\x05query\x18\t \x01(\v2\x1c.aepcaw.wtp.v1.ocsf.DNSQueryH\bR\x05query\x88\x01\x01\x12,\n" +
	"\x0fredirect_target\x18\n" +
	" \x01(\tH\tR\x0eredirectTarget\x88\x01\x01\x12,\n" +
	"\x0fpolicy_decision\x18\v \x01(\tH\n" +
	"R\x0epolicyDecision\x88\x01\x01\x12$\n" +
	"\vpolicy_rule\x18\f \x01(\tH\vR\n" +
	"policyRule\x88\x01\x01B\f\n" +
	"\n" +
	"_class_uidB\x0e\n" +
	"\f_activity_idB\x0f\n" +
	"\r_category_uidB\v\n" +
	"\t_type_uidB\a\n" +
	"\x05_timeB\v\n" +
	"\t_severityB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_actorB\b\n" +
	"\x06_queryB\x12\n" +
	"\x10_redirect_targetB\x12\n" +
	"\x10_policy_decisionB\x0e\n" +
	"\f_policy_rule\"\xaf\x01\n" +
	"\bDNSQuery\x12\x1f\n" +
	"\bhostname\x18\x01 \x01(\tH\x00R\bhostname\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x02 \x01(\rH\x01R\x04type\x88\x01\x01\x12 \n" +
	"\ttype_name\x18\x03 \x01(\tH\x02R\btypeName\x88\x01\x01\x12\x19\n" +
	"\x05class\x18\x04 \x01(\tH\x03R\x05class\x88\x01\x01B\v\n" +
	"\t_hostnameB\a\n" +
	"\x05_typeB\f\n" +
	"\n" +
	"_type_nameB\b\n" +
	"\x06_classBFZDgithub.com/thePM001/AEP-agent-element-protocol/AEP-CAW/proto/aepcaw/wtp/v1/ocsf;ocsfpbb\x06proto3"

var (
	file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDescOnce sync.Once
	file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDescData []byte
)

func file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDescGZIP() []byte {
	file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDescOnce.Do(func() {
		file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDesc)))
	})
	return file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDescData
}

var file_aepcaw_wtp_v1_ocsf_dns_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aepcaw_wtp_v1_ocsf_dns_activity_proto_goTypes = []any{
	(*DNSActivity)(nil), // 0: aepcaw.wtp.v1.ocsf.DNSActivity
	(*DNSQuery)(nil),    // 1: aepcaw.wtp.v1.ocsf.DNSQuery
	(*Metadata)(nil),    // 2: aepcaw.wtp.v1.ocsf.Metadata
	(*Actor)(nil),       // 3: aepcaw.wtp.v1.ocsf.Actor
}
var file_aepcaw_wtp_v1_ocsf_dns_activity_proto_depIdxs = []int32{
	2, // 0: aepcaw.wtp.v1.ocsf.DNSActivity.metadata:type_name -> aepcaw.wtp.v1.ocsf.Metadata
	3, // 1: aepcaw.wtp.v1.ocsf.DNSActivity.actor:type_name -> aepcaw.wtp.v1.ocsf.Actor
	1, // 2: aepcaw.wtp.v1.ocsf.DNSActivity.query:type_name -> aepcaw.wtp.v1.ocsf.DNSQuery
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aepcaw_wtp_v1_ocsf_dns_activity_proto_init() }
func file_aepcaw_wtp_v1_ocsf_dns_activity_proto_init() {
	if File_aepcaw_wtp_v1_ocsf_dns_activity_proto != nil {
		return
	}
	file_aepcaw_wtp_v1_ocsf_common_proto_init()
	file_aepcaw_wtp_v1_ocsf_dns_activity_proto_msgTypes[0].OneofWrappers = []any{}
	file_aepcaw_wtp_v1_ocsf_dns_activity_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_dns_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aepcaw_wtp_v1_ocsf_dns_activity_proto_goTypes,
		DependencyIndexes: file_aepcaw_wtp_v1_ocsf_dns_activity_proto_depIdxs,
		MessageInfos:      file_aepcaw_wtp_v1_ocsf_dns_activity_proto_msgTypes,
	}.Build()
	File_aepcaw_wtp_v1_ocsf_dns_activity_proto = out.File
	file_aepcaw_wtp_v1_ocsf_dns_activity_proto_goTypes = nil
	file_aepcaw_wtp_v1_ocsf_dns_activity_proto_depIdxs = nil
}
