// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aepcaw/wtp/v1/ocsf/http_activity.proto

package ocsfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HTTPActivity (class_uid 4002). OCSF v1.8.0 subset.
//
// Activities used:
//
//	1 = Request
//	2 = Response
//	6 = Traffic
type HTTPActivity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClassUid       *uint32                `protobuf:"varint,1,opt,name=class_uid,json=classUid,proto3,oneof" json:"class_uid,omitempty"` // 4002
	ActivityId     *uint32                `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3,oneof" json:"activity_id,omitempty"`
	CategoryUid    *uint32                `protobuf:"varint,3,opt,name=category_uid,json=categoryUid,proto3,oneof" json:"category_uid,omitempty"` // 4
	TypeUid        *uint32                `protobuf:"varint,4,opt,name=type_uid,json=typeUid,proto3,oneof" json:"type_uid,omitempty"`
	Time           *uint64                `protobuf:"varint,5,opt,name=time,proto3,oneof" json:"time,omitempty"`
	Severity       *string                `protobuf:"bytes,6,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	Metadata       *Metadata              `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Actor          *Actor                 `protobuf:"bytes,8,opt,name=actor,proto3,oneof" json:"actor,omitempty"`
	SrcEndpoint    *Endpoint              `protobuf:"bytes,9,opt,name=src_endpoint,json=srcEndpoint,proto3,oneof" json:"src_endpoint,omitempty"`
	DstEndpoint    *Endpoint              `protobuf:"bytes,10,opt,name=dst_endpoint,json=dstEndpoint,proto3,oneof" json:"dst_endpoint,omitempty"`
	HttpRequest    *HTTPRequest           `protobuf:"bytes,11,opt,name=http_request,json=httpRequest,proto3,oneof" json:"http_request,omitempty"`
	HttpResponse   *HTTPResponse          `protobuf:"bytes,12,opt,name=http_response,json=httpResponse,proto3,oneof" json:"http_response,omitempty"`
	PolicyDecision *string                `protobuf:"bytes,13,opt,name=policy_decision,json=policyDecision,proto3,oneof" json:"policy_decision,omitempty"`
	PolicyRule     *string                `protobuf:"bytes,14,opt,name=policy_rule,json=policyRule,proto3,oneof" json:"policy_rule,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HTTPActivity) Reset() {
	*x = HTTPActivity{}
	mi := &file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPActivity) ProtoMessage() {}

func (x *HTTPActivity) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPActivity.ProtoReflect.Descriptor instead.
func (*HTTPActivity) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPActivity) GetClassUid() uint32 {
	if x != nil && x.ClassUid != nil {
		return *x.ClassUid
	}
	return 0
}

func (x *HTTPActivity) GetActivityId() uint32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *HTTPActivity) GetCategoryUid() uint32 {
	if x != nil && x.CategoryUid != nil {
		return *x.CategoryUid
	}
	return 0
}

func (x *HTTPActivity) GetTypeUid() uint32 {
	if x != nil && x.TypeUid != nil {
		return *x.TypeUid
	}
	return 0
}

func (x *HTTPActivity) GetTime() uint64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *HTTPActivity) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *HTTPActivity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HTTPActivity) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *HTTPActivity) GetSrcEndpoint() *Endpoint {
	if x != nil {
		return x.SrcEndpoint
	}
	return nil
}

func (x *HTTPActivity) GetDstEndpoint() *Endpoint {
	if x != nil {
		return x.DstEndpoint
	}
	return nil
}

func (x *HTTPActivity) GetHttpRequest() *HTTPRequest {
	if x != nil {
		return x.HttpRequest
	}
	return nil
}

func (x *HTTPActivity) GetHttpResponse() *HTTPResponse {
	if x != nil {
		return x.HttpResponse
	}
	return nil
}

func (x *HTTPActivity) GetPolicyDecision() string {
	if x != nil && x.PolicyDecision != nil {
		return *x.PolicyDecision
	}
	return ""
}

func (x *HTTPActivity) GetPolicyRule() string {
	if x != nil && x.PolicyRule != nil {
		return *x.PolicyRule
	}
	return ""
}

type HTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpMethod    *string                `protobuf:"bytes,1,opt,name=http_method,json=httpMethod,proto3,oneof" json:"http_method,omitempty"` // ev.Fields["method"]
	Url           *string                `protobuf:"bytes,2,opt,name=url,proto3,oneof" json:"url,omitempty"`                                 // ev.Fields["url"]
	UserAgent     *string                `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`    // ev.Fields["user_agent"]
	Version       *string                `protobuf:"bytes,4,opt,name=version,proto3,oneof" json:"version,omitempty"`                         // ev.Fields["http_version"]
	Host          *string                `protobuf:"bytes,5,opt,name=host,proto3,oneof" json:"host,omitempty"`                               // ev.Fields["host"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPRequest) GetHttpMethod() string {
	if x != nil && x.HttpMethod != nil {
		return *x.HttpMethod
	}
	return ""
}

func (x *HTTPRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *HTTPRequest) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *HTTPRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *HTTPRequest) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

type HTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    *uint32                `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,oneof" json:"status_code,omitempty"` // ev.Fields["status_code"]
	Length        *uint64                `protobuf:"varint,2,opt,name=length,proto3,oneof" json:"length,omitempty"`                           // ev.Fields["response_bytes"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	mi := &file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPResponse) GetStatusCode() uint32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return 0
}

func (x *HTTPResponse) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

var File_aepcaw_wtp_v1_ocsf_http_activity_proto protoreflect.FileDescriptor

const file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDesc = "" +
	"\n" +
	"&aepcaw/wtp/v1/ocsf/http_activity.proto\x12\x12aepcaw.wtp.v1.ocsf\x1a\x1faepcaw/wtp/v1/ocsf/common.proto\"\x94\a\n" +
	"\fHTTPActivity\x12 \n" +
	"\tclass_uid\x18\x01 \x01(\rH\x00R\bclassUid\x88\x01\x01\x12$\n" +
	"\vactivity_id\x18\x02 \x01(\rH\x01R\n" +
	"activityId\x88\x01\x01\x12&\n" +
	"\fcategory_uid\x18\x03 \x01(\rH\x02R\vcategoryUid\x88\x01\x01\x12\x1e\n" +
	"\btype_uid\x18\x04 \x01(\rH\x03R\atypeUid\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\x05 \x01(\x04H\x04R\x04time\x88\x01\x01\x12\x1f\n" +
	"\bseverity\x18\x06 \x01(\tH\x05R\bseverity\x88\x01\x01\x12=\n" +
	"\bmetadata\x18\a \x01(\v2\x1c.aepcaw.wtp.v1.ocsf.MetadataH\x06R\bmetadata\x88\x01\x01\x124\n" +
	"\x05actor\x18\b \x01(\v2\x19.aepcaw.wtp.v1.ocsf.ActorH\aR\x05actor\x88\x01\x01\x12D\n" +
	"\fsrc_endpoint\x18\t \x01(\v2\x1c.aepcaw.wtp.v1.ocsf.EndpointH\bR\vsrcEndpoint\x88\x01\x01\x12D\n" +
	"\fdst_endpoint\x18\n" +
	" \x01(\v2\x1c.aepcaw.wtp.v1.ocsf.EndpointH\tR\vdstEndpoint\x88\x01\x01\x12G\n" +
	"\fhttp_request\x18\v \x01(\v2\x1f.aepcaw.wtp.v1.ocsf.HTTPRequestH\n" +
	"R\vhttpRequest\x88\x01\x01\x12J\n" +
	"\rhttp_response\x18\f \x01(\v2 .aepcaw.wtp.v1.ocsf.HTTPResponseH\vR\fhttpResponse\x88\x01\x01\x12,\n" +
	"\x0fpolicy_decision\x18\r \x01(\tH\fR\x0epolicyDecision\x88\x01\x01\x12$\n" +
	"\vpolicy_rule\x18\x0e \x01(\tH\rR\n" +
	"policyRule\x88\x01\x01B\f\n" +
	"\n" +
	"_class_uidB\x0e\n" +
	"\f_activity_idB\x0f\n" +
	"\r_category_uidB\v\n" +
	"\t_type_uidB\a\n" +
	"\x05_timeB\v\n" +
	"\t_severityB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_actorB\x0f\n" +
	"\r_src_endpointB\x0f\n" +
	"\r_dst_endpointB\x0f\n" +
	"\r_http_requestB\x10\n" +
	"\x0e_http_responseB\x12\n" +
	"\x10_policy_decisionB\x0e\n" +
	"\f_policy_rule\"\xe2\x01\n" +
	"\vHTTPRequest\x12$\n" +
	"\vhttp_method\x18\x01 \x01(\tH\x00R\n" +
	"httpMethod\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x02 \x01(\tH\x01R\x03url\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tH\x02R\tuserAgent\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x04 \x01(\tH\x03R\aversion\x88\x01\x01\x12\x17\n" +
	"\x04host\x18\x05 \x01(\tH\x04R\x04host\x88\x01\x01B\x0e\n" +
	"\f_http_methodB\x06\n" +
	"\x04_urlB\r\n" +
	"\v_user_agentB\n" +
	"\n" +
	"\b_versionB\a\n" +
	"\x05_host\"l\n" +
	"\fHTTPResponse\x12$\n" +
	"\vstatus_code\x18\x01 \x01(\rH\x00R\n" +
	"statusCode\x88\x01\x01\x12\x1b\n" +
	"\x06length\x18\x02 \x01(\x04H\x01R\x06length\x88\x01\x01B\x0e\n" +
	"\f_status_codeB\t\n" +
	"\a_lengthBFZDgithub.com/thePM001/AEP-agent-element-protocol/AEP-CAW/proto/aepcaw/wtp/v1/ocsf;ocsfpbb\x06proto3"

var (
	file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescOnce sync.Once
	file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescData []byte
)

func file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescGZIP() []byte {
	file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescOnce.Do(func() {
		file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDesc)))
	})
	return file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDescData
}

var file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aepcaw_wtp_v1_ocsf_http_activity_proto_goTypes = []any{
	(*HTTPActivity)(nil), // 0: aepcaw.wtp.v1.ocsf.HTTPActivity
	(*HTTPRequest)(nil),  // 1: aepcaw.wtp.v1.ocsf.HTTPRequest
	(*HTTPResponse)(nil), // 2: aepcaw.wtp.v1.ocsf.HTTPResponse
	(*Metadata)(nil),     // 3: aepcaw.wtp.v1.ocsf.Metadata
	(*Actor)(nil),        // 4: aepcaw.wtp.v1.ocsf.Actor
	(*Endpoint)(nil),     // 5: aepcaw.wtp.v1.ocsf.Endpoint
}
var file_aepcaw_wtp_v1_ocsf_http_activity_proto_depIdxs = []int32{
	3, // 0: aepcaw.wtp.v1.ocsf.HTTPActivity.metadata:type_name -> aepcaw.wtp.v1.ocsf.Metadata
	4, // 1: aepcaw.wtp.v1.ocsf.HTTPActivity.actor:type_name -> aepcaw.wtp.v1.ocsf.Actor
	5, // 2: aepcaw.wtp.v1.ocsf.HTTPActivity.src_endpoint:type_name -> aepcaw.wtp.v1.ocsf.Endpoint
	5, // 3: aepcaw.wtp.v1.ocsf.HTTPActivity.dst_endpoint:type_name -> aepcaw.wtp.v1.ocsf.Endpoint
	1, // 4: aepcaw.wtp.v1.ocsf.HTTPActivity.http_request:type_name -> aepcaw.wtp.v1.ocsf.HTTPRequest
	2, // 5: aepcaw.wtp.v1.ocsf.HTTPActivity.http_response:type_name -> aepcaw.wtp.v1.ocsf.HTTPResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_aepcaw_wtp_v1_ocsf_http_activity_proto_init() }
func file_aepcaw_wtp_v1_ocsf_http_activity_proto_init() {
	if File_aepcaw_wtp_v1_ocsf_http_activity_proto != nil {
		return
	}
	file_aepcaw_wtp_v1_ocsf_common_proto_init()
	file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[0].OneofWrappers = []any{}
	file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[1].OneofWrappers = []any{}
	file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_http_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aepcaw_wtp_v1_ocsf_http_activity_proto_goTypes,
		DependencyIndexes: file_aepcaw_wtp_v1_ocsf_http_activity_proto_depIdxs,
		MessageInfos:      file_aepcaw_wtp_v1_ocsf_http_activity_proto_msgTypes,
	}.Build()
	File_aepcaw_wtp_v1_ocsf_http_activity_proto = out.File
	file_aepcaw_wtp_v1_ocsf_http_activity_proto_goTypes = nil
	file_aepcaw_wtp_v1_ocsf_http_activity_proto_depIdxs = nil
}
