// proto/aepcaw/wtp/v1/ocsf/process_activity.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aepcaw/wtp/v1/ocsf/process_activity.proto

package ocsfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessActivity (class_uid 1007). OCSF v1.8.0 subset.
//
// Activities used by aep-caw:
//
//	1 = Launch
//	2 = Terminate
//	3 = Open      (used for exec_intercept)
//	4 = Inject    (reserved; not currently emitted)
//
// Sources mapping to this class: execve, exec, exec_intercept, exec.start,
// ptrace_execve, command_started, command_executed, command_finished,
// command_killed, command_redirected, command_redirect, process_start, exit.
type ProcessActivity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClassUid       *uint32                `protobuf:"varint,1,opt,name=class_uid,json=classUid,proto3,oneof" json:"class_uid,omitempty"` // 1007
	ActivityId     *uint32                `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3,oneof" json:"activity_id,omitempty"`
	CategoryUid    *uint32                `protobuf:"varint,3,opt,name=category_uid,json=categoryUid,proto3,oneof" json:"category_uid,omitempty"` // 1 = System Activity
	TypeUid        *uint32                `protobuf:"varint,4,opt,name=type_uid,json=typeUid,proto3,oneof" json:"type_uid,omitempty"`             // class_uid * 100 + activity_id
	Time           *uint64                `protobuf:"varint,5,opt,name=time,proto3,oneof" json:"time,omitempty"`                                  // ev.Timestamp.UTC().UnixNano()
	Severity       *string                `protobuf:"bytes,6,opt,name=severity,proto3,oneof" json:"severity,omitempty"`                           // "Informational" | "Low" | …
	Metadata       *Metadata              `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Actor          *Actor                 `protobuf:"bytes,8,opt,name=actor,proto3,oneof" json:"actor,omitempty"`     // parent process
	Process        *Process               `protobuf:"bytes,9,opt,name=process,proto3,oneof" json:"process,omitempty"` // child / target process
	ExitCode       *uint32                `protobuf:"varint,10,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	PolicyDecision *string                `protobuf:"bytes,11,opt,name=policy_decision,json=policyDecision,proto3,oneof" json:"policy_decision,omitempty"` // ev.Policy.Decision when present
	PolicyRule     *string                `protobuf:"bytes,12,opt,name=policy_rule,json=policyRule,proto3,oneof" json:"policy_rule,omitempty"`
	UnwrappedFrom  *string                `protobuf:"bytes,13,opt,name=unwrapped_from,json=unwrappedFrom,proto3,oneof" json:"unwrapped_from,omitempty"`
	PayloadCommand *string                `protobuf:"bytes,14,opt,name=payload_command,json=payloadCommand,proto3,oneof" json:"payload_command,omitempty"`
	Truncated      *bool                  `protobuf:"varint,15,opt,name=truncated,proto3,oneof" json:"truncated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessActivity) Reset() {
	*x = ProcessActivity{}
	mi := &file_aepcaw_wtp_v1_ocsf_process_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessActivity) ProtoMessage() {}

func (x *ProcessActivity) ProtoReflect() protoreflect.Message {
	mi := &file_aepcaw_wtp_v1_ocsf_process_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessActivity.ProtoReflect.Descriptor instead.
func (*ProcessActivity) Descriptor() ([]byte, []int) {
	return file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessActivity) GetClassUid() uint32 {
	if x != nil && x.ClassUid != nil {
		return *x.ClassUid
	}
	return 0
}

func (x *ProcessActivity) GetActivityId() uint32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *ProcessActivity) GetCategoryUid() uint32 {
	if x != nil && x.CategoryUid != nil {
		return *x.CategoryUid
	}
	return 0
}

func (x *ProcessActivity) GetTypeUid() uint32 {
	if x != nil && x.TypeUid != nil {
		return *x.TypeUid
	}
	return 0
}

func (x *ProcessActivity) GetTime() uint64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *ProcessActivity) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *ProcessActivity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProcessActivity) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ProcessActivity) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *ProcessActivity) GetExitCode() uint32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ProcessActivity) GetPolicyDecision() string {
	if x != nil && x.PolicyDecision != nil {
		return *x.PolicyDecision
	}
	return ""
}

func (x *ProcessActivity) GetPolicyRule() string {
	if x != nil && x.PolicyRule != nil {
		return *x.PolicyRule
	}
	return ""
}

func (x *ProcessActivity) GetUnwrappedFrom() string {
	if x != nil && x.UnwrappedFrom != nil {
		return *x.UnwrappedFrom
	}
	return ""
}

func (x *ProcessActivity) GetPayloadCommand() string {
	if x != nil && x.PayloadCommand != nil {
		return *x.PayloadCommand
	}
	return ""
}

func (x *ProcessActivity) GetTruncated() bool {
	if x != nil && x.Truncated != nil {
		return *x.Truncated
	}
	return false
}

var File_aepcaw_wtp_v1_ocsf_process_activity_proto protoreflect.FileDescriptor

const file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDesc = "" +
	"\n" +
	")aepcaw/wtp/v1/ocsf/process_activity.proto\x12\x12aepcaw.wtp.v1.ocsf\x1a\x1faepcaw/wtp/v1/ocsf/common.proto\"\xdb\x06\n" +
	"\x0fProcessActivity\x12 \n" +
	"\tclass_uid\x18\x01 \x01(\rH\x00R\bclassUid\x88\x01\x01\x12$\n" +
	"\vactivity_id\x18\x02 \x01(\rH\x01R\n" +
	"activityId\x88\x01\x01\x12&\n" +
	"\fcategory_uid\x18\x03 \x01(\rH\x02R\vcategoryUid\x88\x01\x01\x12\x1e\n" +
	"\btype_uid\x18\x04 \x01(\rH\x03R\atypeUid\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\x05 \x01(\x04H\x04R\x04time\x88\x01\x01\x12\x1f\n" +
	"\bseverity\x18\x06 \x01(\tH\x05R\bseverity\x88\x01\x01\x12=\n" +
	"\bmetadata\x18\a \x01(\v2\x1c.aepcaw.wtp.v1.ocsf.MetadataH\x06R\bmetadata\x88\x01\x01\x124\n" +
	"\x05actor\x18\b \x01(\v2\x19.aepcaw.wtp.v1.ocsf.ActorH\aR\x05actor\x88\x01\x01\x12:\n" +
	"\aprocess\x18\t \x01(\v2\x1b.aepcaw.wtp.v1.ocsf.ProcessH\bR\aprocess\x88\x01\x01\x12 \n" +
	"\texit_code\x18\n" +
	" \x01(\rH\tR\bexitCode\x88\x01\x01\x12,\n" +
	"\x0fpolicy_decision\x18\v \x01(\tH\n" +
	"R\x0epolicyDecision\x88\x01\x01\x12$\n" +
	"\vpolicy_rule\x18\f \x01(\tH\vR\n" +
	"policyRule\x88\x01\x01\x12*\n" +
	"\x0eunwrapped_from\x18\r \x01(\tH\fR\runwrappedFrom\x88\x01\x01\x12,\n" +
	"\x0fpayload_command\x18\x0e \x01(\tH\rR\x0epayloadCommand\x88\x01\x01\x12!\n" +
	"\ttruncated\x18\x0f \x01(\bH\x0eR\ttruncated\x88\x01\x01B\f\n" +
	"\n" +
	"_class_uidB\x0e\n" +
	"\f_activity_idB\x0f\n" +
	"\r_category_uidB\v\n" +
	"\t_type_uidB\a\n" +
	"\x05_timeB\v\n" +
	"\t_severityB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_actorB\n" +
	"\n" +
	"\b_processB\f\n" +
	"\n" +
	"_exit_codeB\x12\n" +
	"\x10_policy_decisionB\x0e\n" +
	"\f_policy_ruleB\x11\n" +
	"\x0f_unwrapped_fromB\x12\n" +
	"\x10_payload_commandB\f\n" +
	"\n" +
	"_truncatedBFZDgithub.com/thePM001/AEP-agent-element-protocol/AEP-CAW/proto/aepcaw/wtp/v1/ocsf;ocsfpbb\x06proto3"

var (
	file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDescOnce sync.Once
	file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDescData []byte
)

func file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDescGZIP() []byte {
	file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDescOnce.Do(func() {
		file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDesc)))
	})
	return file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDescData
}

var file_aepcaw_wtp_v1_ocsf_process_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aepcaw_wtp_v1_ocsf_process_activity_proto_goTypes = []any{
	(*ProcessActivity)(nil), // 0: aepcaw.wtp.v1.ocsf.ProcessActivity
	(*Metadata)(nil),        // 1: aepcaw.wtp.v1.ocsf.Metadata
	(*Actor)(nil),           // 2: aepcaw.wtp.v1.ocsf.Actor
	(*Process)(nil),         // 3: aepcaw.wtp.v1.ocsf.Process
}
var file_aepcaw_wtp_v1_ocsf_process_activity_proto_depIdxs = []int32{
	1, // 0: aepcaw.wtp.v1.ocsf.ProcessActivity.metadata:type_name -> aepcaw.wtp.v1.ocsf.Metadata
	2, // 1: aepcaw.wtp.v1.ocsf.ProcessActivity.actor:type_name -> aepcaw.wtp.v1.ocsf.Actor
	3, // 2: aepcaw.wtp.v1.ocsf.ProcessActivity.process:type_name -> aepcaw.wtp.v1.ocsf.Process
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aepcaw_wtp_v1_ocsf_process_activity_proto_init() }
func file_aepcaw_wtp_v1_ocsf_process_activity_proto_init() {
	if File_aepcaw_wtp_v1_ocsf_process_activity_proto != nil {
		return
	}
	file_aepcaw_wtp_v1_ocsf_common_proto_init()
	file_aepcaw_wtp_v1_ocsf_process_activity_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDesc), len(file_aepcaw_wtp_v1_ocsf_process_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aepcaw_wtp_v1_ocsf_process_activity_proto_goTypes,
		DependencyIndexes: file_aepcaw_wtp_v1_ocsf_process_activity_proto_depIdxs,
		MessageInfos:      file_aepcaw_wtp_v1_ocsf_process_activity_proto_msgTypes,
	}.Build()
	File_aepcaw_wtp_v1_ocsf_process_activity_proto = out.File
	file_aepcaw_wtp_v1_ocsf_process_activity_proto_goTypes = nil
	file_aepcaw_wtp_v1_ocsf_process_activity_proto_depIdxs = nil
}
